import { ActionFeedbackHeader } from '../hako_action_msgs/pdu_jstype_ActionFeedbackHeader.js';
import { FibonacciFeedback } from '../sample_action_msgs/pdu_jstype_FibonacciFeedback.js';


/**
 * ROS message: sample_action_msgs/FibonacciActionFeedback
 * Generated by hakoniwa-ros2pdu.
 */
export class FibonacciActionFeedback {
/** @type { ActionFeedbackHeader } */
    header;
/** @type { FibonacciFeedback } */
    body;


    constructor() {
        this.header = new ActionFeedbackHeader();
        this.body = new FibonacciFeedback();
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'header'
            const field_val = this.header;
            if (typeof field_val?.toDict === 'function') {
                d['header'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['header'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['header'] = field_val.toString();
            } else {
                d['header'] = field_val;
            }
        }
        {
            // handle field 'body'
            const field_val = this.body;
            if (typeof field_val?.toDict === 'function') {
                d['body'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['body'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['body'] = field_val.toString();
            } else {
                d['body'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { FibonacciActionFeedback }
     */
    static fromDict(d) {
        const obj = new FibonacciActionFeedback();
        if (d.hasOwnProperty('header')) {
            const field_class = ActionFeedbackHeader;
            if (d.header) {
                obj.header = field_class.fromDict(d.header);
            }
        }
        if (d.hasOwnProperty('body')) {
            const field_class = FibonacciFeedback;
            if (d.body) {
                obj.body = field_class.fromDict(d.body);
            }
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { FibonacciActionFeedback }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
