

/**
 * ROS message: sample_action_msgs/FibonacciFeedback
 * Generated by hakoniwa-ros2pdu.
 */
export class FibonacciFeedback {
/** @type { Array<number> } */
    partial_sequence;


    constructor() {
        this.partial_sequence = [];
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'partial_sequence'
            const field_val = this.partial_sequence;
            if (typeof field_val?.toDict === 'function') {
                d['partial_sequence'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['partial_sequence'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['partial_sequence'] = field_val.toString();
            } else {
                d['partial_sequence'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { FibonacciFeedback }
     */
    static fromDict(d) {
        const obj = new FibonacciFeedback();
        if (d.hasOwnProperty('partial_sequence')) {
            obj.partial_sequence = d.partial_sequence;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { FibonacciFeedback }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
