

/**
 * ROS message: sample_action_msgs/FibonacciGoal
 * Generated by hakoniwa-ros2pdu.
 */
export class FibonacciGoal {
/** @type { number } */
    order;


    constructor() {
        this.order = 0;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'order'
            const field_val = this.order;
            if (typeof field_val?.toDict === 'function') {
                d['order'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['order'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['order'] = field_val.toString();
            } else {
                d['order'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { FibonacciGoal }
     */
    static fromDict(d) {
        const obj = new FibonacciGoal();
        if (d.hasOwnProperty('order')) {
            obj.order = d.order;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { FibonacciGoal }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
