{% for item in container.ruby_imports -%}
require_relative '../{{ item.dep_pkg }}/{{ item.file }}'
{% endfor -%}
require 'json'

module HakoPdu
  module {{ container.ruby_pkg_module_name }}
    # ROS message: {{ container.pkg_name }}/{{ container.msg_type_name }}
    # Generated by hakoniwa-ros2pdu.
    class {{ container.class_name }}
      attr_accessor{% for field in container.json_data["fields"] %} :{{ field.name }}{% if not loop.last %},{% endif %}{% endfor %}

      def initialize({% for field in container.json_data["fields"] %}{{ field.name }}: {{ container.get_ruby_default_value(field.type) }}{% if not loop.last %}, {% endif %}{% endfor %})
{% for field in container.json_data["fields"] %}
        @{{ field.name }} = {{ field.name }}
{% endfor %}
      end

      def to_h
        {
{% for field in container.json_data["fields"] %}
          '{{ field.name }}' => self.class.encode_value(@{{ field.name }}){% if not loop.last %},{% endif %}
{% endfor %}
        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(
{% for field in container.json_data["fields"] %}
          {{ field.name }}: decode_{{ field.name }}(hash.fetch('{{ field.name }}', {{ container.get_ruby_default_value(field.type) }})){% if not loop.last %},{% endif %}
{% endfor %}
        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end

{% for field in container.json_data["fields"] %}
      def self.decode_{{ field.name }}(value)
{%- if container.is_array(field.type) and not container.is_primitive(container.get_array_type(field.type)) and not container.is_string(container.get_array_type(field.type)) %}
        return [] if value.nil?
        value.map { |item| {{ container.get_ruby_type_ref(field.type) }}.from_h(item) }
{%- elif not container.is_array(field.type) and not container.is_primitive(field.type) and not container.is_string(field.type) %}
        value.is_a?(Hash) ? {{ container.get_ruby_type_ref(field.type) }}.from_h(value) : value
{%- else %}
        value
{%- endif %}
      end

{% endfor -%}
    end
  end
end
