defmodule HakoPdu.Ev3Msgs.Ev3PduColorSensor do
  @moduledoc """
  ROS message: ev3_msgs/Ev3PduColorSensor

  Generated by hakoniwa-ros2pdu.
  """

  defstruct [

    color: 0,

    reflect: 0,

    rgb_r: 0,

    rgb_g: 0,

    rgb_b: 0

  ]

  def new(attrs \\ %{}) when is_map(attrs) do
    struct(__MODULE__, attrs)
  end

  def to_map(%__MODULE__{} = msg) do
    %{

      "color" => encode_value(msg.color),

      "reflect" => encode_value(msg.reflect),

      "rgb_r" => encode_value(msg.rgb_r),

      "rgb_g" => encode_value(msg.rgb_g),

      "rgb_b" => encode_value(msg.rgb_b)

    }
  end

  def from_map(map) when is_map(map) do
    %__MODULE__{

      color: map |> get_value(:color, "color", 0) |> decode_color(),

      reflect: map |> get_value(:reflect, "reflect", 0) |> decode_reflect(),

      rgb_r: map |> get_value(:rgb_r, "rgb_r", 0) |> decode_rgb_r(),

      rgb_g: map |> get_value(:rgb_g, "rgb_g", 0) |> decode_rgb_g(),

      rgb_b: map |> get_value(:rgb_b, "rgb_b", 0) |> decode_rgb_b()

    }
  end

  def to_json(%__MODULE__{} = msg) do
    msg
    |> to_map()
    |> json_encode()
  end

  def from_json(json) when is_binary(json) do
    json
    |> json_decode()
    |> from_map()
  end

  defp get_value(map, atom_key, string_key, default) do
    Map.get(map, atom_key, Map.get(map, string_key, default))
  end

  defp encode_value(values) when is_list(values), do: Enum.map(values, &encode_value/1)
  defp encode_value(%{__struct__: module} = value) do
    if function_exported?(module, :to_map, 1), do: module.to_map(value), else: value
  end
  defp encode_value(value), do: value

  defp json_encode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :encode!, 1) -> apply(Jason, :encode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :encode!, 1) -> apply(JSON, :encode!, [value])
      true -> raise "No JSON encoder found. Add Jason or JSON to use to_json/1."
    end
  end

  defp json_decode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :decode!, 1) -> apply(Jason, :decode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :decode!, 1) -> apply(JSON, :decode!, [value])
      true -> raise "No JSON decoder found. Add Jason or JSON to use from_json/1."
    end
  end


  defp decode_color(value) do
    value
  end


  defp decode_reflect(value) do
    value
  end


  defp decode_rgb_r(value) do
    value
  end


  defp decode_rgb_g(value) do
    value
  end


  defp decode_rgb_b(value) do
    value
  end

end
