defmodule HakoPdu.Ev3Msgs.Ev3PduActuatorHeader do
  @moduledoc """
  ROS message: ev3_msgs/Ev3PduActuatorHeader

  Generated by hakoniwa-ros2pdu.
  """

  defstruct [

    name: "",

    version: 0,

    asset_time: 0,

    ext_off: 0,

    ext_size: 0

  ]

  def new(attrs \\ %{}) when is_map(attrs) do
    struct(__MODULE__, attrs)
  end

  def to_map(%__MODULE__{} = msg) do
    %{

      "name" => encode_value(msg.name),

      "version" => encode_value(msg.version),

      "asset_time" => encode_value(msg.asset_time),

      "ext_off" => encode_value(msg.ext_off),

      "ext_size" => encode_value(msg.ext_size)

    }
  end

  def from_map(map) when is_map(map) do
    %__MODULE__{

      name: map |> get_value(:name, "name", "") |> decode_name(),

      version: map |> get_value(:version, "version", 0) |> decode_version(),

      asset_time: map |> get_value(:asset_time, "asset_time", 0) |> decode_asset_time(),

      ext_off: map |> get_value(:ext_off, "ext_off", 0) |> decode_ext_off(),

      ext_size: map |> get_value(:ext_size, "ext_size", 0) |> decode_ext_size()

    }
  end

  def to_json(%__MODULE__{} = msg) do
    msg
    |> to_map()
    |> json_encode()
  end

  def from_json(json) when is_binary(json) do
    json
    |> json_decode()
    |> from_map()
  end

  defp get_value(map, atom_key, string_key, default) do
    Map.get(map, atom_key, Map.get(map, string_key, default))
  end

  defp encode_value(values) when is_list(values), do: Enum.map(values, &encode_value/1)
  defp encode_value(%{__struct__: module} = value) do
    if function_exported?(module, :to_map, 1), do: module.to_map(value), else: value
  end
  defp encode_value(value), do: value

  defp json_encode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :encode!, 1) -> apply(Jason, :encode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :encode!, 1) -> apply(JSON, :encode!, [value])
      true -> raise "No JSON encoder found. Add Jason or JSON to use to_json/1."
    end
  end

  defp json_decode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :decode!, 1) -> apply(Jason, :decode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :decode!, 1) -> apply(JSON, :decode!, [value])
      true -> raise "No JSON decoder found. Add Jason or JSON to use from_json/1."
    end
  end


  defp decode_name(value) do
    value
  end


  defp decode_version(value) do
    value
  end


  defp decode_asset_time(value) do
    value
  end


  defp decode_ext_off(value) do
    value
  end


  defp decode_ext_size(value) do
    value
  end

end
