from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class FibonacciGoal:
    """
    ROS message: sample_action_msgs/FibonacciGoal
    Generated by hakoniwa-ros2pdu.
    """

    order: int

    def __init__(self):
        self.order = 0

    def __str__(self):
        return f"FibonacciGoal(" + ", ".join([
            f"order={self.order}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'order'
        field_val = self.order
        if isinstance(field_val, bytearray):
            d['order'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['order'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['order'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['order'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'order'
        if 'order' in d:
            field_type = cls.__annotations__.get('order')
            value = d['order']
            
            if field_type is bytearray:
                obj.order = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.order = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.order = value
            elif hasattr(field_type, 'from_dict'):
                obj.order = field_type.from_dict(value)
            else:
                obj.order = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
