

/**
 * ROS message: builtin_interfaces/Duration
 * Generated by hakoniwa-ros2pdu.
 */
export class Duration {
/** @type { number } */
    sec;
/** @type { number } */
    nanosec;


    constructor() {
        this.sec = 0;
        this.nanosec = 0;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'sec'
            const field_val = this.sec;
            if (typeof field_val?.toDict === 'function') {
                d['sec'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['sec'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['sec'] = field_val.toString();
            } else {
                d['sec'] = field_val;
            }
        }
        {
            // handle field 'nanosec'
            const field_val = this.nanosec;
            if (typeof field_val?.toDict === 'function') {
                d['nanosec'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['nanosec'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['nanosec'] = field_val.toString();
            } else {
                d['nanosec'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { Duration }
     */
    static fromDict(d) {
        const obj = new Duration();
        if (d.hasOwnProperty('sec')) {
            obj.sec = d.sec;
        }
        if (d.hasOwnProperty('nanosec')) {
            obj.nanosec = d.nanosec;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { Duration }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
