require 'json'

module HakoPdu
  module SensorMsgs
    # ROS message: sensor_msgs/NavSatStatus
    # Generated by hakoniwa-ros2pdu.
    class NavSatStatus
      attr_accessor :status, :service

      def initialize(status: 0, service: 0)

        @status = status

        @service = service

      end

      def to_h
        {

          'status' => self.class.encode_value(@status),

          'service' => self.class.encode_value(@service)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          status: decode_status(hash.fetch('status', 0)),

          service: decode_service(hash.fetch('service', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_status(value)
        value
      end


      def self.decode_service(value)
        value
      end

end
  end
end
