require_relative '../std_msgs/pdu_type_Header'
require_relative '../sensor_msgs/pdu_type_NavSatStatus'
require_relative '../builtin_interfaces/pdu_type_Time'
require 'json'

module HakoPdu
  module SensorMsgs
    # ROS message: sensor_msgs/NavSatFix
    # Generated by hakoniwa-ros2pdu.
    class NavSatFix
      attr_accessor :header, :status, :latitude, :longitude, :altitude, :position_covariance, :position_covariance_type

      def initialize(header: HakoPdu::StdMsgs::Header.new, status: HakoPdu::SensorMsgs::NavSatStatus.new, latitude: 0.0, longitude: 0.0, altitude: 0.0, position_covariance: [], position_covariance_type: 0)

        @header = header

        @status = status

        @latitude = latitude

        @longitude = longitude

        @altitude = altitude

        @position_covariance = position_covariance

        @position_covariance_type = position_covariance_type

      end

      def to_h
        {

          'header' => self.class.encode_value(@header),

          'status' => self.class.encode_value(@status),

          'latitude' => self.class.encode_value(@latitude),

          'longitude' => self.class.encode_value(@longitude),

          'altitude' => self.class.encode_value(@altitude),

          'position_covariance' => self.class.encode_value(@position_covariance),

          'position_covariance_type' => self.class.encode_value(@position_covariance_type)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          header: decode_header(hash.fetch('header', HakoPdu::StdMsgs::Header.new)),

          status: decode_status(hash.fetch('status', HakoPdu::SensorMsgs::NavSatStatus.new)),

          latitude: decode_latitude(hash.fetch('latitude', 0.0)),

          longitude: decode_longitude(hash.fetch('longitude', 0.0)),

          altitude: decode_altitude(hash.fetch('altitude', 0.0)),

          position_covariance: decode_position_covariance(hash.fetch('position_covariance', [])),

          position_covariance_type: decode_position_covariance_type(hash.fetch('position_covariance_type', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_header(value)
        value.is_a?(Hash) ? HakoPdu::StdMsgs::Header.from_h(value) : value
      end


      def self.decode_status(value)
        value.is_a?(Hash) ? HakoPdu::SensorMsgs::NavSatStatus.from_h(value) : value
      end


      def self.decode_latitude(value)
        value
      end


      def self.decode_longitude(value)
        value
      end


      def self.decode_altitude(value)
        value
      end


      def self.decode_position_covariance(value)
        value
      end


      def self.decode_position_covariance_type(value)
        value
      end

end
  end
end
