require 'json'

module HakoPdu
  module SensorMsgs
    # ROS message: sensor_msgs/LaserEcho
    # Generated by hakoniwa-ros2pdu.
    class LaserEcho
      attr_accessor :echoes

      def initialize(echoes: [])

        @echoes = echoes

      end

      def to_h
        {

          'echoes' => self.class.encode_value(@echoes)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          echoes: decode_echoes(hash.fetch('echoes', []))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_echoes(value)
        value
      end

end
  end
end
