require_relative '../sensor_msgs/pdu_type_ChannelFloat32'
require_relative '../std_msgs/pdu_type_Header'
require_relative '../geometry_msgs/pdu_type_Point32'
require_relative '../builtin_interfaces/pdu_type_Time'
require 'json'

module HakoPdu
  module SensorMsgs
    # ROS message: sensor_msgs/PointCloud
    # Generated by hakoniwa-ros2pdu.
    class PointCloud
      attr_accessor :header, :points, :channels

      def initialize(header: HakoPdu::StdMsgs::Header.new, points: [], channels: [])

        @header = header

        @points = points

        @channels = channels

      end

      def to_h
        {

          'header' => self.class.encode_value(@header),

          'points' => self.class.encode_value(@points),

          'channels' => self.class.encode_value(@channels)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          header: decode_header(hash.fetch('header', HakoPdu::StdMsgs::Header.new)),

          points: decode_points(hash.fetch('points', [])),

          channels: decode_channels(hash.fetch('channels', []))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_header(value)
        value.is_a?(Hash) ? HakoPdu::StdMsgs::Header.from_h(value) : value
      end


      def self.decode_points(value)
        return [] if value.nil?
        value.map { |item| HakoPdu::GeometryMsgs::Point32.from_h(item) }
      end


      def self.decode_channels(value)
        return [] if value.nil?
        value.map { |item| HakoPdu::SensorMsgs::ChannelFloat32.from_h(item) }
      end

end
  end
end
