require_relative '../std_msgs/pdu_type_Header'
require_relative '../geometry_msgs/pdu_type_Quaternion'
require_relative '../builtin_interfaces/pdu_type_Time'
require_relative '../geometry_msgs/pdu_type_Vector3'
require 'json'

module HakoPdu
  module SensorMsgs
    # ROS message: sensor_msgs/Imu
    # Generated by hakoniwa-ros2pdu.
    class Imu
      attr_accessor :header, :orientation, :orientation_covariance, :angular_velocity, :angular_velocity_covariance, :linear_acceleration, :linear_acceleration_covariance

      def initialize(header: HakoPdu::StdMsgs::Header.new, orientation: HakoPdu::GeometryMsgs::Quaternion.new, orientation_covariance: [], angular_velocity: HakoPdu::GeometryMsgs::Vector3.new, angular_velocity_covariance: [], linear_acceleration: HakoPdu::GeometryMsgs::Vector3.new, linear_acceleration_covariance: [])

        @header = header

        @orientation = orientation

        @orientation_covariance = orientation_covariance

        @angular_velocity = angular_velocity

        @angular_velocity_covariance = angular_velocity_covariance

        @linear_acceleration = linear_acceleration

        @linear_acceleration_covariance = linear_acceleration_covariance

      end

      def to_h
        {

          'header' => self.class.encode_value(@header),

          'orientation' => self.class.encode_value(@orientation),

          'orientation_covariance' => self.class.encode_value(@orientation_covariance),

          'angular_velocity' => self.class.encode_value(@angular_velocity),

          'angular_velocity_covariance' => self.class.encode_value(@angular_velocity_covariance),

          'linear_acceleration' => self.class.encode_value(@linear_acceleration),

          'linear_acceleration_covariance' => self.class.encode_value(@linear_acceleration_covariance)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          header: decode_header(hash.fetch('header', HakoPdu::StdMsgs::Header.new)),

          orientation: decode_orientation(hash.fetch('orientation', HakoPdu::GeometryMsgs::Quaternion.new)),

          orientation_covariance: decode_orientation_covariance(hash.fetch('orientation_covariance', [])),

          angular_velocity: decode_angular_velocity(hash.fetch('angular_velocity', HakoPdu::GeometryMsgs::Vector3.new)),

          angular_velocity_covariance: decode_angular_velocity_covariance(hash.fetch('angular_velocity_covariance', [])),

          linear_acceleration: decode_linear_acceleration(hash.fetch('linear_acceleration', HakoPdu::GeometryMsgs::Vector3.new)),

          linear_acceleration_covariance: decode_linear_acceleration_covariance(hash.fetch('linear_acceleration_covariance', []))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_header(value)
        value.is_a?(Hash) ? HakoPdu::StdMsgs::Header.from_h(value) : value
      end


      def self.decode_orientation(value)
        value.is_a?(Hash) ? HakoPdu::GeometryMsgs::Quaternion.from_h(value) : value
      end


      def self.decode_orientation_covariance(value)
        value
      end


      def self.decode_angular_velocity(value)
        value.is_a?(Hash) ? HakoPdu::GeometryMsgs::Vector3.from_h(value) : value
      end


      def self.decode_angular_velocity_covariance(value)
        value
      end


      def self.decode_linear_acceleration(value)
        value.is_a?(Hash) ? HakoPdu::GeometryMsgs::Vector3.from_h(value) : value
      end


      def self.decode_linear_acceleration_covariance(value)
        value
      end

end
  end
end
