require_relative '../std_msgs/pdu_type_Header'
require_relative '../geometry_msgs/pdu_type_Quaternion'
require_relative '../builtin_interfaces/pdu_type_Time'
require_relative '../geometry_msgs/pdu_type_Transform'
require_relative '../geometry_msgs/pdu_type_Twist'
require_relative '../geometry_msgs/pdu_type_Vector3'
require_relative '../geometry_msgs/pdu_type_Wrench'
require 'json'

module HakoPdu
  module SensorMsgs
    # ROS message: sensor_msgs/MultiDOFJointState
    # Generated by hakoniwa-ros2pdu.
    class MultiDOFJointState
      attr_accessor :header, :joint_names, :transforms, :twist, :wrench

      def initialize(header: HakoPdu::StdMsgs::Header.new, joint_names: [], transforms: [], twist: [], wrench: [])

        @header = header

        @joint_names = joint_names

        @transforms = transforms

        @twist = twist

        @wrench = wrench

      end

      def to_h
        {

          'header' => self.class.encode_value(@header),

          'joint_names' => self.class.encode_value(@joint_names),

          'transforms' => self.class.encode_value(@transforms),

          'twist' => self.class.encode_value(@twist),

          'wrench' => self.class.encode_value(@wrench)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          header: decode_header(hash.fetch('header', HakoPdu::StdMsgs::Header.new)),

          joint_names: decode_joint_names(hash.fetch('joint_names', [])),

          transforms: decode_transforms(hash.fetch('transforms', [])),

          twist: decode_twist(hash.fetch('twist', [])),

          wrench: decode_wrench(hash.fetch('wrench', []))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_header(value)
        value.is_a?(Hash) ? HakoPdu::StdMsgs::Header.from_h(value) : value
      end


      def self.decode_joint_names(value)
        value
      end


      def self.decode_transforms(value)
        return [] if value.nil?
        value.map { |item| HakoPdu::GeometryMsgs::Transform.from_h(item) }
      end


      def self.decode_twist(value)
        return [] if value.nil?
        value.map { |item| HakoPdu::GeometryMsgs::Twist.from_h(item) }
      end


      def self.decode_wrench(value)
        return [] if value.nil?
        value.map { |item| HakoPdu::GeometryMsgs::Wrench.from_h(item) }
      end

end
  end
end
