require_relative '../std_msgs/pdu_type_Header'
require_relative '../builtin_interfaces/pdu_type_Time'
require 'json'

module HakoPdu
  module SensorMsgs
    # ROS message: sensor_msgs/RelativeHumidity
    # Generated by hakoniwa-ros2pdu.
    class RelativeHumidity
      attr_accessor :header, :relative_humidity, :variance

      def initialize(header: HakoPdu::StdMsgs::Header.new, relative_humidity: 0.0, variance: 0.0)

        @header = header

        @relative_humidity = relative_humidity

        @variance = variance

      end

      def to_h
        {

          'header' => self.class.encode_value(@header),

          'relative_humidity' => self.class.encode_value(@relative_humidity),

          'variance' => self.class.encode_value(@variance)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          header: decode_header(hash.fetch('header', HakoPdu::StdMsgs::Header.new)),

          relative_humidity: decode_relative_humidity(hash.fetch('relative_humidity', 0.0)),

          variance: decode_variance(hash.fetch('variance', 0.0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_header(value)
        value.is_a?(Hash) ? HakoPdu::StdMsgs::Header.from_h(value) : value
      end


      def self.decode_relative_humidity(value)
        value
      end


      def self.decode_variance(value)
        value
      end

end
  end
end
