require 'json'

module HakoPdu
  module SensorMsgs
    # ROS message: sensor_msgs/RegionOfInterest
    # Generated by hakoniwa-ros2pdu.
    class RegionOfInterest
      attr_accessor :x_offset, :y_offset, :height, :width, :do_rectify

      def initialize(x_offset: 0, y_offset: 0, height: 0, width: 0, do_rectify: false)

        @x_offset = x_offset

        @y_offset = y_offset

        @height = height

        @width = width

        @do_rectify = do_rectify

      end

      def to_h
        {

          'x_offset' => self.class.encode_value(@x_offset),

          'y_offset' => self.class.encode_value(@y_offset),

          'height' => self.class.encode_value(@height),

          'width' => self.class.encode_value(@width),

          'do_rectify' => self.class.encode_value(@do_rectify)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          x_offset: decode_x_offset(hash.fetch('x_offset', 0)),

          y_offset: decode_y_offset(hash.fetch('y_offset', 0)),

          height: decode_height(hash.fetch('height', 0)),

          width: decode_width(hash.fetch('width', 0)),

          do_rectify: decode_do_rectify(hash.fetch('do_rectify', false))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_x_offset(value)
        value
      end


      def self.decode_y_offset(value)
        value
      end


      def self.decode_height(value)
        value
      end


      def self.decode_width(value)
        value
      end


      def self.decode_do_rectify(value)
        value
      end

end
  end
end
