require_relative '../std_msgs/pdu_type_Header'
require_relative '../sensor_msgs/pdu_type_RegionOfInterest'
require_relative '../builtin_interfaces/pdu_type_Time'
require 'json'

module HakoPdu
  module SensorMsgs
    # ROS message: sensor_msgs/CameraInfo
    # Generated by hakoniwa-ros2pdu.
    class CameraInfo
      attr_accessor :header, :height, :width, :distortion_model, :d, :k, :r, :p, :binning_x, :binning_y, :roi

      def initialize(header: HakoPdu::StdMsgs::Header.new, height: 0, width: 0, distortion_model: "", d: [], k: [], r: [], p: [], binning_x: 0, binning_y: 0, roi: HakoPdu::SensorMsgs::RegionOfInterest.new)

        @header = header

        @height = height

        @width = width

        @distortion_model = distortion_model

        @d = d

        @k = k

        @r = r

        @p = p

        @binning_x = binning_x

        @binning_y = binning_y

        @roi = roi

      end

      def to_h
        {

          'header' => self.class.encode_value(@header),

          'height' => self.class.encode_value(@height),

          'width' => self.class.encode_value(@width),

          'distortion_model' => self.class.encode_value(@distortion_model),

          'd' => self.class.encode_value(@d),

          'k' => self.class.encode_value(@k),

          'r' => self.class.encode_value(@r),

          'p' => self.class.encode_value(@p),

          'binning_x' => self.class.encode_value(@binning_x),

          'binning_y' => self.class.encode_value(@binning_y),

          'roi' => self.class.encode_value(@roi)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          header: decode_header(hash.fetch('header', HakoPdu::StdMsgs::Header.new)),

          height: decode_height(hash.fetch('height', 0)),

          width: decode_width(hash.fetch('width', 0)),

          distortion_model: decode_distortion_model(hash.fetch('distortion_model', "")),

          d: decode_d(hash.fetch('d', [])),

          k: decode_k(hash.fetch('k', [])),

          r: decode_r(hash.fetch('r', [])),

          p: decode_p(hash.fetch('p', [])),

          binning_x: decode_binning_x(hash.fetch('binning_x', 0)),

          binning_y: decode_binning_y(hash.fetch('binning_y', 0)),

          roi: decode_roi(hash.fetch('roi', HakoPdu::SensorMsgs::RegionOfInterest.new))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_header(value)
        value.is_a?(Hash) ? HakoPdu::StdMsgs::Header.from_h(value) : value
      end


      def self.decode_height(value)
        value
      end


      def self.decode_width(value)
        value
      end


      def self.decode_distortion_model(value)
        value
      end


      def self.decode_d(value)
        value
      end


      def self.decode_k(value)
        value
      end


      def self.decode_r(value)
        value
      end


      def self.decode_p(value)
        value
      end


      def self.decode_binning_x(value)
        value
      end


      def self.decode_binning_y(value)
        value
      end


      def self.decode_roi(value)
        value.is_a?(Hash) ? HakoPdu::SensorMsgs::RegionOfInterest.from_h(value) : value
      end

end
  end
end
