require 'json'

module HakoPdu
  module SensorMsgs
    # ROS message: sensor_msgs/PointField
    # Generated by hakoniwa-ros2pdu.
    class PointField
      attr_accessor :name, :offset, :datatype, :count

      def initialize(name: "", offset: 0, datatype: 0, count: 0)

        @name = name

        @offset = offset

        @datatype = datatype

        @count = count

      end

      def to_h
        {

          'name' => self.class.encode_value(@name),

          'offset' => self.class.encode_value(@offset),

          'datatype' => self.class.encode_value(@datatype),

          'count' => self.class.encode_value(@count)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          name: decode_name(hash.fetch('name', "")),

          offset: decode_offset(hash.fetch('offset', 0)),

          datatype: decode_datatype(hash.fetch('datatype', 0)),

          count: decode_count(hash.fetch('count', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_name(value)
        value
      end


      def self.decode_offset(value)
        value
      end


      def self.decode_datatype(value)
        value
      end


      def self.decode_count(value)
        value
      end

end
  end
end
