require 'json'

module HakoPdu
  module SensorMsgs
    # ROS message: sensor_msgs/ChannelFloat32
    # Generated by hakoniwa-ros2pdu.
    class ChannelFloat32
      attr_accessor :name, :values

      def initialize(name: "", values: [])

        @name = name

        @values = values

      end

      def to_h
        {

          'name' => self.class.encode_value(@name),

          'values' => self.class.encode_value(@values)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          name: decode_name(hash.fetch('name', "")),

          values: decode_values(hash.fetch('values', []))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_name(value)
        value
      end


      def self.decode_values(value)
        value
      end

end
  end
end
