require_relative '../std_msgs/pdu_type_Header'
require_relative '../builtin_interfaces/pdu_type_Time'
require 'json'

module HakoPdu
  module SensorMsgs
    # ROS message: sensor_msgs/BatteryState
    # Generated by hakoniwa-ros2pdu.
    class BatteryState
      attr_accessor :header, :voltage, :temperature, :current, :charge, :capacity, :design_capacity, :percentage, :power_supply_status, :power_supply_health, :power_supply_technology, :present, :cell_voltage, :cell_temperature, :location, :serial_number

      def initialize(header: HakoPdu::StdMsgs::Header.new, voltage: 0.0, temperature: 0.0, current: 0.0, charge: 0.0, capacity: 0.0, design_capacity: 0.0, percentage: 0.0, power_supply_status: 0, power_supply_health: 0, power_supply_technology: 0, present: false, cell_voltage: [], cell_temperature: [], location: "", serial_number: "")

        @header = header

        @voltage = voltage

        @temperature = temperature

        @current = current

        @charge = charge

        @capacity = capacity

        @design_capacity = design_capacity

        @percentage = percentage

        @power_supply_status = power_supply_status

        @power_supply_health = power_supply_health

        @power_supply_technology = power_supply_technology

        @present = present

        @cell_voltage = cell_voltage

        @cell_temperature = cell_temperature

        @location = location

        @serial_number = serial_number

      end

      def to_h
        {

          'header' => self.class.encode_value(@header),

          'voltage' => self.class.encode_value(@voltage),

          'temperature' => self.class.encode_value(@temperature),

          'current' => self.class.encode_value(@current),

          'charge' => self.class.encode_value(@charge),

          'capacity' => self.class.encode_value(@capacity),

          'design_capacity' => self.class.encode_value(@design_capacity),

          'percentage' => self.class.encode_value(@percentage),

          'power_supply_status' => self.class.encode_value(@power_supply_status),

          'power_supply_health' => self.class.encode_value(@power_supply_health),

          'power_supply_technology' => self.class.encode_value(@power_supply_technology),

          'present' => self.class.encode_value(@present),

          'cell_voltage' => self.class.encode_value(@cell_voltage),

          'cell_temperature' => self.class.encode_value(@cell_temperature),

          'location' => self.class.encode_value(@location),

          'serial_number' => self.class.encode_value(@serial_number)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          header: decode_header(hash.fetch('header', HakoPdu::StdMsgs::Header.new)),

          voltage: decode_voltage(hash.fetch('voltage', 0.0)),

          temperature: decode_temperature(hash.fetch('temperature', 0.0)),

          current: decode_current(hash.fetch('current', 0.0)),

          charge: decode_charge(hash.fetch('charge', 0.0)),

          capacity: decode_capacity(hash.fetch('capacity', 0.0)),

          design_capacity: decode_design_capacity(hash.fetch('design_capacity', 0.0)),

          percentage: decode_percentage(hash.fetch('percentage', 0.0)),

          power_supply_status: decode_power_supply_status(hash.fetch('power_supply_status', 0)),

          power_supply_health: decode_power_supply_health(hash.fetch('power_supply_health', 0)),

          power_supply_technology: decode_power_supply_technology(hash.fetch('power_supply_technology', 0)),

          present: decode_present(hash.fetch('present', false)),

          cell_voltage: decode_cell_voltage(hash.fetch('cell_voltage', [])),

          cell_temperature: decode_cell_temperature(hash.fetch('cell_temperature', [])),

          location: decode_location(hash.fetch('location', "")),

          serial_number: decode_serial_number(hash.fetch('serial_number', ""))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_header(value)
        value.is_a?(Hash) ? HakoPdu::StdMsgs::Header.from_h(value) : value
      end


      def self.decode_voltage(value)
        value
      end


      def self.decode_temperature(value)
        value
      end


      def self.decode_current(value)
        value
      end


      def self.decode_charge(value)
        value
      end


      def self.decode_capacity(value)
        value
      end


      def self.decode_design_capacity(value)
        value
      end


      def self.decode_percentage(value)
        value
      end


      def self.decode_power_supply_status(value)
        value
      end


      def self.decode_power_supply_health(value)
        value
      end


      def self.decode_power_supply_technology(value)
        value
      end


      def self.decode_present(value)
        value
      end


      def self.decode_cell_voltage(value)
        value
      end


      def self.decode_cell_temperature(value)
        value
      end


      def self.decode_location(value)
        value
      end


      def self.decode_serial_number(value)
        value
      end

end
  end
end
