require_relative '../std_msgs/pdu_type_Header'
require_relative '../builtin_interfaces/pdu_type_Time'
require 'json'

module HakoPdu
  module SensorMsgs
    # ROS message: sensor_msgs/JointState
    # Generated by hakoniwa-ros2pdu.
    class JointState
      attr_accessor :header, :name, :position, :velocity, :effort

      def initialize(header: HakoPdu::StdMsgs::Header.new, name: [], position: [], velocity: [], effort: [])

        @header = header

        @name = name

        @position = position

        @velocity = velocity

        @effort = effort

      end

      def to_h
        {

          'header' => self.class.encode_value(@header),

          'name' => self.class.encode_value(@name),

          'position' => self.class.encode_value(@position),

          'velocity' => self.class.encode_value(@velocity),

          'effort' => self.class.encode_value(@effort)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          header: decode_header(hash.fetch('header', HakoPdu::StdMsgs::Header.new)),

          name: decode_name(hash.fetch('name', [])),

          position: decode_position(hash.fetch('position', [])),

          velocity: decode_velocity(hash.fetch('velocity', [])),

          effort: decode_effort(hash.fetch('effort', []))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_header(value)
        value.is_a?(Hash) ? HakoPdu::StdMsgs::Header.from_h(value) : value
      end


      def self.decode_name(value)
        value
      end


      def self.decode_position(value)
        value
      end


      def self.decode_velocity(value)
        value
      end


      def self.decode_effort(value)
        value
      end

end
  end
end
