require_relative '../std_msgs/pdu_type_Header'
require_relative '../builtin_interfaces/pdu_type_Time'
require 'json'

module HakoPdu
  module SensorMsgs
    # ROS message: sensor_msgs/TimeReference
    # Generated by hakoniwa-ros2pdu.
    class TimeReference
      attr_accessor :header, :time_ref, :source

      def initialize(header: HakoPdu::StdMsgs::Header.new, time_ref: HakoPdu::BuiltinInterfaces::Time.new, source: "")

        @header = header

        @time_ref = time_ref

        @source = source

      end

      def to_h
        {

          'header' => self.class.encode_value(@header),

          'time_ref' => self.class.encode_value(@time_ref),

          'source' => self.class.encode_value(@source)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          header: decode_header(hash.fetch('header', HakoPdu::StdMsgs::Header.new)),

          time_ref: decode_time_ref(hash.fetch('time_ref', HakoPdu::BuiltinInterfaces::Time.new)),

          source: decode_source(hash.fetch('source', ""))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_header(value)
        value.is_a?(Hash) ? HakoPdu::StdMsgs::Header.from_h(value) : value
      end


      def self.decode_time_ref(value)
        value.is_a?(Hash) ? HakoPdu::BuiltinInterfaces::Time.from_h(value) : value
      end


      def self.decode_source(value)
        value
      end

end
  end
end
