import { Header } from '../std_msgs/pdu_jstype_Header.js';
import { Quaternion } from '../geometry_msgs/pdu_jstype_Quaternion.js';
import { Time } from '../builtin_interfaces/pdu_jstype_Time.js';
import { Transform } from '../geometry_msgs/pdu_jstype_Transform.js';
import { Twist } from '../geometry_msgs/pdu_jstype_Twist.js';
import { Vector3 } from '../geometry_msgs/pdu_jstype_Vector3.js';
import { Wrench } from '../geometry_msgs/pdu_jstype_Wrench.js';


/**
 * ROS message: sensor_msgs/MultiDOFJointState
 * Generated by hakoniwa-ros2pdu.
 */
export class MultiDOFJointState {
/** @type { Header } */
    header;
/** @type { Array<string> } */
    joint_names;
/** @type { Array<Transform> } */
    transforms;
/** @type { Array<Twist> } */
    twist;
/** @type { Array<Wrench> } */
    wrench;


    constructor() {
        this.header = new Header();
        this.joint_names = [];
        this.transforms = [];
        this.twist = [];
        this.wrench = [];
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'header'
            const field_val = this.header;
            if (typeof field_val?.toDict === 'function') {
                d['header'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['header'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['header'] = field_val;
            }
        }
        {
            // handle field 'joint_names'
            const field_val = this.joint_names;
            if (typeof field_val?.toDict === 'function') {
                d['joint_names'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['joint_names'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['joint_names'] = field_val;
            }
        }
        {
            // handle field 'transforms'
            const field_val = this.transforms;
            if (typeof field_val?.toDict === 'function') {
                d['transforms'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['transforms'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['transforms'] = field_val;
            }
        }
        {
            // handle field 'twist'
            const field_val = this.twist;
            if (typeof field_val?.toDict === 'function') {
                d['twist'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['twist'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['twist'] = field_val;
            }
        }
        {
            // handle field 'wrench'
            const field_val = this.wrench;
            if (typeof field_val?.toDict === 'function') {
                d['wrench'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['wrench'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['wrench'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { MultiDOFJointState }
     */
    static fromDict(d) {
        const obj = new MultiDOFJointState();
        if (d.hasOwnProperty('header')) {
            const field_class = Header;
            if (d.header) {
                obj.header = field_class.fromDict(d.header);
            }
        }
        if (d.hasOwnProperty('joint_names')) {
            obj.joint_names = d.joint_names;
        }
        if (d.hasOwnProperty('transforms')) {
            const item_class = Transform;
            if (Array.isArray(d.transforms)) {
                obj.transforms = d.transforms.map(item => item_class.fromDict(item));
            }
        }
        if (d.hasOwnProperty('twist')) {
            const item_class = Twist;
            if (Array.isArray(d.twist)) {
                obj.twist = d.twist.map(item => item_class.fromDict(item));
            }
        }
        if (d.hasOwnProperty('wrench')) {
            const item_class = Wrench;
            if (Array.isArray(d.wrench)) {
                obj.wrench = d.wrench.map(item => item_class.fromDict(item));
            }
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { MultiDOFJointState }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
