import { Header } from '../std_msgs/pdu_jstype_Header.js';
import { Time } from '../builtin_interfaces/pdu_jstype_Time.js';
import { Vector3 } from '../geometry_msgs/pdu_jstype_Vector3.js';


/**
 * ROS message: sensor_msgs/MagneticField
 * Generated by hakoniwa-ros2pdu.
 */
export class MagneticField {
/** @type { Header } */
    header;
/** @type { Vector3 } */
    magnetic_field;
/** @type { Array<number> } */
    magnetic_field_covariance;


    constructor() {
        this.header = new Header();
        this.magnetic_field = new Vector3();
        this.magnetic_field_covariance = [];
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'header'
            const field_val = this.header;
            if (typeof field_val?.toDict === 'function') {
                d['header'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['header'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['header'] = field_val;
            }
        }
        {
            // handle field 'magnetic_field'
            const field_val = this.magnetic_field;
            if (typeof field_val?.toDict === 'function') {
                d['magnetic_field'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['magnetic_field'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['magnetic_field'] = field_val;
            }
        }
        {
            // handle field 'magnetic_field_covariance'
            const field_val = this.magnetic_field_covariance;
            if (typeof field_val?.toDict === 'function') {
                d['magnetic_field_covariance'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['magnetic_field_covariance'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['magnetic_field_covariance'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { MagneticField }
     */
    static fromDict(d) {
        const obj = new MagneticField();
        if (d.hasOwnProperty('header')) {
            const field_class = Header;
            if (d.header) {
                obj.header = field_class.fromDict(d.header);
            }
        }
        if (d.hasOwnProperty('magnetic_field')) {
            const field_class = Vector3;
            if (d.magnetic_field) {
                obj.magnetic_field = field_class.fromDict(d.magnetic_field);
            }
        }
        if (d.hasOwnProperty('magnetic_field_covariance')) {
            obj.magnetic_field_covariance = d.magnetic_field_covariance;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { MagneticField }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
