import { ChannelFloat32 } from '../sensor_msgs/pdu_jstype_ChannelFloat32.js';
import { Header } from '../std_msgs/pdu_jstype_Header.js';
import { Point32 } from '../geometry_msgs/pdu_jstype_Point32.js';
import { Time } from '../builtin_interfaces/pdu_jstype_Time.js';


/**
 * ROS message: sensor_msgs/PointCloud
 * Generated by hakoniwa-ros2pdu.
 */
export class PointCloud {
/** @type { Header } */
    header;
/** @type { Array<Point32> } */
    points;
/** @type { Array<ChannelFloat32> } */
    channels;


    constructor() {
        this.header = new Header();
        this.points = [];
        this.channels = [];
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'header'
            const field_val = this.header;
            if (typeof field_val?.toDict === 'function') {
                d['header'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['header'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['header'] = field_val;
            }
        }
        {
            // handle field 'points'
            const field_val = this.points;
            if (typeof field_val?.toDict === 'function') {
                d['points'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['points'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['points'] = field_val;
            }
        }
        {
            // handle field 'channels'
            const field_val = this.channels;
            if (typeof field_val?.toDict === 'function') {
                d['channels'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['channels'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['channels'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { PointCloud }
     */
    static fromDict(d) {
        const obj = new PointCloud();
        if (d.hasOwnProperty('header')) {
            const field_class = Header;
            if (d.header) {
                obj.header = field_class.fromDict(d.header);
            }
        }
        if (d.hasOwnProperty('points')) {
            const item_class = Point32;
            if (Array.isArray(d.points)) {
                obj.points = d.points.map(item => item_class.fromDict(item));
            }
        }
        if (d.hasOwnProperty('channels')) {
            const item_class = ChannelFloat32;
            if (Array.isArray(d.channels)) {
                obj.channels = d.channels.map(item => item_class.fromDict(item));
            }
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { PointCloud }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
