import { Header } from '../std_msgs/pdu_jstype_Header.js';
import { NavSatStatus } from '../sensor_msgs/pdu_jstype_NavSatStatus.js';
import { Time } from '../builtin_interfaces/pdu_jstype_Time.js';


/**
 * ROS message: sensor_msgs/NavSatFix
 * Generated by hakoniwa-ros2pdu.
 */
export class NavSatFix {
/** @type { Header } */
    header;
/** @type { NavSatStatus } */
    status;
/** @type { number } */
    latitude;
/** @type { number } */
    longitude;
/** @type { number } */
    altitude;
/** @type { Array<number> } */
    position_covariance;
/** @type { number } */
    position_covariance_type;


    constructor() {
        this.header = new Header();
        this.status = new NavSatStatus();
        this.latitude = 0.0;
        this.longitude = 0.0;
        this.altitude = 0.0;
        this.position_covariance = [];
        this.position_covariance_type = 0;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'header'
            const field_val = this.header;
            if (typeof field_val?.toDict === 'function') {
                d['header'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['header'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['header'] = field_val;
            }
        }
        {
            // handle field 'status'
            const field_val = this.status;
            if (typeof field_val?.toDict === 'function') {
                d['status'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['status'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['status'] = field_val;
            }
        }
        {
            // handle field 'latitude'
            const field_val = this.latitude;
            if (typeof field_val?.toDict === 'function') {
                d['latitude'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['latitude'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['latitude'] = field_val;
            }
        }
        {
            // handle field 'longitude'
            const field_val = this.longitude;
            if (typeof field_val?.toDict === 'function') {
                d['longitude'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['longitude'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['longitude'] = field_val;
            }
        }
        {
            // handle field 'altitude'
            const field_val = this.altitude;
            if (typeof field_val?.toDict === 'function') {
                d['altitude'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['altitude'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['altitude'] = field_val;
            }
        }
        {
            // handle field 'position_covariance'
            const field_val = this.position_covariance;
            if (typeof field_val?.toDict === 'function') {
                d['position_covariance'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['position_covariance'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['position_covariance'] = field_val;
            }
        }
        {
            // handle field 'position_covariance_type'
            const field_val = this.position_covariance_type;
            if (typeof field_val?.toDict === 'function') {
                d['position_covariance_type'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['position_covariance_type'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['position_covariance_type'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { NavSatFix }
     */
    static fromDict(d) {
        const obj = new NavSatFix();
        if (d.hasOwnProperty('header')) {
            const field_class = Header;
            if (d.header) {
                obj.header = field_class.fromDict(d.header);
            }
        }
        if (d.hasOwnProperty('status')) {
            const field_class = NavSatStatus;
            if (d.status) {
                obj.status = field_class.fromDict(d.status);
            }
        }
        if (d.hasOwnProperty('latitude')) {
            obj.latitude = d.latitude;
        }
        if (d.hasOwnProperty('longitude')) {
            obj.longitude = d.longitude;
        }
        if (d.hasOwnProperty('altitude')) {
            obj.altitude = d.altitude;
        }
        if (d.hasOwnProperty('position_covariance')) {
            obj.position_covariance = d.position_covariance;
        }
        if (d.hasOwnProperty('position_covariance_type')) {
            obj.position_covariance_type = d.position_covariance_type;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { NavSatFix }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
