require 'json'

module HakoPdu
  module BuiltinInterfaces
    # ROS message: builtin_interfaces/Time
    # Generated by hakoniwa-ros2pdu.
    class Time
      attr_accessor :sec, :nanosec

      def initialize(sec: 0, nanosec: 0)

        @sec = sec

        @nanosec = nanosec

      end

      def to_h
        {

          'sec' => self.class.encode_value(@sec),

          'nanosec' => self.class.encode_value(@nanosec)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          sec: decode_sec(hash.fetch('sec', 0)),

          nanosec: decode_nanosec(hash.fetch('nanosec', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_sec(value)
        value
      end


      def self.decode_nanosec(value)
        value
      end

end
  end
end
