defmodule HakoPdu.StdMsgs.ColorRGBA do
  @moduledoc """
  ROS message: std_msgs/ColorRGBA

  Generated by hakoniwa-ros2pdu.
  """

  defstruct [

    r: 0.0,

    g: 0.0,

    b: 0.0,

    a: 0.0

  ]

  def new(attrs \\ %{}) when is_map(attrs) do
    struct(__MODULE__, attrs)
  end

  def to_map(%__MODULE__{} = msg) do
    %{

      "r" => encode_value(msg.r),

      "g" => encode_value(msg.g),

      "b" => encode_value(msg.b),

      "a" => encode_value(msg.a)

    }
  end

  def from_map(map) when is_map(map) do
    %__MODULE__{

      r: map |> get_value(:r, "r", 0.0) |> decode_r(),

      g: map |> get_value(:g, "g", 0.0) |> decode_g(),

      b: map |> get_value(:b, "b", 0.0) |> decode_b(),

      a: map |> get_value(:a, "a", 0.0) |> decode_a()

    }
  end

  def to_json(%__MODULE__{} = msg) do
    msg
    |> to_map()
    |> json_encode()
  end

  def from_json(json) when is_binary(json) do
    json
    |> json_decode()
    |> from_map()
  end

  defp get_value(map, atom_key, string_key, default) do
    Map.get(map, atom_key, Map.get(map, string_key, default))
  end

  defp encode_value(values) when is_list(values), do: Enum.map(values, &encode_value/1)
  defp encode_value(%{__struct__: module} = value) do
    if function_exported?(module, :to_map, 1), do: module.to_map(value), else: value
  end
  defp encode_value(value), do: value

  defp json_encode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :encode!, 1) -> apply(Jason, :encode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :encode!, 1) -> apply(JSON, :encode!, [value])
      true -> raise "No JSON encoder found. Add Jason or JSON to use to_json/1."
    end
  end

  defp json_decode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :decode!, 1) -> apply(Jason, :decode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :decode!, 1) -> apply(JSON, :decode!, [value])
      true -> raise "No JSON decoder found. Add Jason or JSON to use from_json/1."
    end
  end


  defp decode_r(value) do
    value
  end


  defp decode_g(value) do
    value
  end


  defp decode_b(value) do
    value
  end


  defp decode_a(value) do
    value
  end

end
