from typing import List

# dependencies for the generated Python class
from ..hako_srv_msgs.pdu_pytype_LogicalTime import LogicalTime


# class definition for the ROS message
class GetWorldTimeResponse:
    """
    ROS message: hako_srv_msgs/GetWorldTimeResponse
    Generated by hakoniwa-ros2pdu.
    """

    result_code: int
    world_time: LogicalTime

    def __init__(self):
        self.result_code = 0
        self.world_time = LogicalTime()

    def __str__(self):
        return f"GetWorldTimeResponse(" + ", ".join([
            f"result_code={self.result_code}"
            f"world_time={self.world_time}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'result_code'
        field_val = self.result_code
        if isinstance(field_val, bytearray):
            d['result_code'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['result_code'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['result_code'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['result_code'] = field_val
        # handle field 'world_time'
        field_val = self.world_time
        if isinstance(field_val, bytearray):
            d['world_time'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['world_time'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['world_time'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['world_time'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'result_code'
        if 'result_code' in d:
            field_type = cls.__annotations__.get('result_code')
            value = d['result_code']
            
            if field_type is bytearray:
                obj.result_code = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.result_code = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.result_code = value
            elif hasattr(field_type, 'from_dict'):
                obj.result_code = field_type.from_dict(value)
            else:
                obj.result_code = value
        # handle field 'world_time'
        if 'world_time' in d:
            field_type = cls.__annotations__.get('world_time')
            value = d['world_time']
            
            if field_type is bytearray:
                obj.world_time = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.world_time = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.world_time = value
            elif hasattr(field_type, 'from_dict'):
                obj.world_time = field_type.from_dict(value)
            else:
                obj.world_time = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
