const assert = require('assert');

async function main() {
    const { CdrError, PduCdrWriter, PduCdrReader } = await import('../pdu/javascript/pdu_cdr_runtime.js');

    function deepEqual(a, b) {
        if (a.length !== b.length) return false;
        for (let i = 0; i < a.length; i++) {
            if (a[i] !== b[i]) return false;
        }
        return true;
    }

    function runTests() {
        console.log("Running CDR compatibility tests...");

        // --- 1. Writer Test (Main Scenario) ---
        const writer = new PduCdrWriter();
        const str_val = "abc";
        const f64_val = 1.5;
        const u32_val = 0x11223344;
        const u8_val = 1;

        writer.write_encapsulation();
        writer.write_uint8(u8_val);
        writer.write_uint32(u32_val);
        writer.write_string(str_val);
        writer.write_float64(f64_val);

        const writtenBuffer = writer.get_buf();
        const writtenArray = new Uint8Array(writtenBuffer);
        
        const expectedMainScenarioBytes = new Uint8Array([
            0x00, 0x01, 0x00, 0x00, // Encapsulation
            0x01,                   // uint8(1)
            0x00, 0x00, 0x00,       // Padding for uint32
            0x44, 0x33, 0x22, 0x11, // uint32(0x11223344)
            0x04, 0x00, 0x00, 0x00, // String length (4)
            0x61, 0x62, 0x63, 0x00, // "abc\0"
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf8, 0x3f // float64(1.5)
        ]);

        assert.ok(deepEqual(writtenArray, expectedMainScenarioBytes), "Writer Test (Main Scenario): Generated byte sequence is incorrect.");
        console.log("✓ Writer Test (Main Scenario) Passed");

        // --- 2. Reader Test (Main Scenario) ---
        const reader = new PduCdrReader(writtenBuffer);
        reader.read_encapsulation();
        assert.strictEqual(reader.read_uint8(), u8_val, "Reader Test (Main Scenario): uint8 mismatch");
        assert.strictEqual(reader.read_uint32(), u32_val, "Reader Test (Main Scenario): uint32 mismatch");
        assert.strictEqual(reader.read_string(), str_val, "Reader Test (Main Scenario): string mismatch");
        assert.strictEqual(reader.read_float64(), f64_val, "Reader Test (Main Scenario): float64 mismatch");
        console.log("✓ Reader Test (Main Scenario) Passed");

        // --- 3. Error Handling Tests ---
        assert.throws(() => new PduCdrReader(new Uint8Array([0, 1, 0])).read_encapsulation(), CdrError, "Error Test: Short encapsulation should throw");
        assert.throws(() => new PduCdrReader(new Uint8Array([0, 0, 0, 0])).read_encapsulation(), CdrError, "Error Test: Bad encapsulation should throw");
        
        const shortReader = new PduCdrReader(expectedMainScenarioBytes.slice(0, 15));
        shortReader.read_encapsulation();
        shortReader.read_uint8();
        shortReader.read_uint32(); // reads length
        assert.throws(() => shortReader.read_string(), CdrError, "Error Test: Unexpected end of buffer should throw");
        console.log("✓ Error Handling Tests Passed");
        
        // --- 4. Additional Feature Tests ---
        // Test write_uint8 with string input (char code)
        const writerUint8String = new PduCdrWriter();
        writerUint8String.write_encapsulation(); // Encapsulation for alignmentBase
        writerUint8String.write_uint8('A');
        const bufUint8String = writerUint8String.get_buf();
        assert.strictEqual(new Uint8Array(bufUint8String)[4], 65, "Feature Test: write_uint8 from string failed"); // [0,1,0,0,65]
        console.log("✓ write_uint8 from string test Passed");


        // Test PduCdrReader constructor with Uint8Array
        const readerUint8Array = new PduCdrReader(new Uint8Array([0, 1, 0, 0, 10])); // Encapsulation + 10
        readerUint8Array.read_encapsulation();
        assert.strictEqual(readerUint8Array.read_uint8(), 10, "Feature Test: Reader from Uint8Array failed");
        console.log("✓ Reader constructor with Uint8Array test Passed");

        // Test write_bool / read_bool alias
        const writerBool = new PduCdrWriter();
        writerBool.write_encapsulation();
        writerBool.write_bool(true);
        writerBool.write_bool(false);
        const readerBool = new PduCdrReader(writerBool.get_buf());
        readerBool.read_encapsulation();
        assert.strictEqual(readerBool.read_bool(), true, "Feature Test: read_bool(true) alias failed");
        assert.strictEqual(readerBool.read_bool(), false, "Feature Test: read_bool(false) alias failed");
        console.log("✓ Boolean alias tests Passed");

        // Test write_string with non-string input
        const writerStringNonString = new PduCdrWriter();
        writerStringNonString.write_encapsulation();
        writerStringNonString.write_string(123);
        writerStringNonString.write_string(true);
        writerStringNonString.write_string(null);
        writerStringNonString.write_string(undefined);
        const readerStringNonString = new PduCdrReader(writerStringNonString.get_buf());
        readerStringNonString.read_encapsulation();
        assert.strictEqual(readerStringNonString.read_string(), "123", "Feature Test: write_string(123) failed");
        assert.strictEqual(readerStringNonString.read_string(), "true", "Feature Test: write_string(true) failed");
        assert.strictEqual(readerStringNonString.read_string(), "null", "Feature Test: write_string(null) failed");
        assert.strictEqual(readerStringNonString.read_string(), "undefined", "Feature Test: write_string(undefined) failed");
        console.log("✓ write_string non-string input tests Passed");

        console.log("✓ All Additional Feature Tests Passed");
    }

    try {
        runTests();
        console.log("All tests passed successfully!");
    } catch (error) {
        console.error("Test failed:", error);
        process.exit(1);
    }
}

main();
