defmodule HakoPdu.HakoMsgs.ExecutionUnitRuntimeContext do
  @moduledoc """
  ROS message: hako_msgs/ExecutionUnitRuntimeContext

  Generated by hakoniwa-ros2pdu.
  """

  defstruct [

    config_hash: 0,

    epoch: 0,

    owner_id: 0,

    context: []

  ]

  def new(attrs \\ %{}) when is_map(attrs) do
    struct(__MODULE__, attrs)
  end

  def to_map(%__MODULE__{} = msg) do
    %{

      "config_hash" => encode_value(msg.config_hash),

      "epoch" => encode_value(msg.epoch),

      "owner_id" => encode_value(msg.owner_id),

      "context" => encode_value(msg.context)

    }
  end

  def from_map(map) when is_map(map) do
    %__MODULE__{

      config_hash: map |> get_value(:config_hash, "config_hash", 0) |> decode_config_hash(),

      epoch: map |> get_value(:epoch, "epoch", 0) |> decode_epoch(),

      owner_id: map |> get_value(:owner_id, "owner_id", 0) |> decode_owner_id(),

      context: map |> get_value(:context, "context", []) |> decode_context()

    }
  end

  def to_json(%__MODULE__{} = msg) do
    msg
    |> to_map()
    |> json_encode()
  end

  def from_json(json) when is_binary(json) do
    json
    |> json_decode()
    |> from_map()
  end

  defp get_value(map, atom_key, string_key, default) do
    Map.get(map, atom_key, Map.get(map, string_key, default))
  end

  defp encode_value(values) when is_list(values), do: Enum.map(values, &encode_value/1)
  defp encode_value(%{__struct__: module} = value) do
    if function_exported?(module, :to_map, 1), do: module.to_map(value), else: value
  end
  defp encode_value(value), do: value

  defp json_encode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :encode!, 1) -> apply(Jason, :encode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :encode!, 1) -> apply(JSON, :encode!, [value])
      true -> raise "No JSON encoder found. Add Jason or JSON to use to_json/1."
    end
  end

  defp json_decode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :decode!, 1) -> apply(Jason, :decode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :decode!, 1) -> apply(JSON, :decode!, [value])
      true -> raise "No JSON decoder found. Add Jason or JSON to use from_json/1."
    end
  end


  defp decode_config_hash(value) do
    value
  end


  defp decode_epoch(value) do
    value
  end


  defp decode_owner_id(value) do
    value
  end


  defp decode_context(value) do
    value
  end

end
