defmodule HakoPdu.HakoMsgs.MetaPdu do
  @moduledoc """
  ROS message: hako_msgs/MetaPdu

  Generated by hakoniwa-ros2pdu.
  """

  defstruct [

    total_len: 0,

    magicno: 0,

    version: 0,

    flags: 0,

    meta_request_type: 0,

    hako_time_us: 0,

    asset_time_us: 0,

    real_time_us: 0,

    robot_name: "",

    channel_id: 0,

    body_len: 0

  ]

  def new(attrs \\ %{}) when is_map(attrs) do
    struct(__MODULE__, attrs)
  end

  def to_map(%__MODULE__{} = msg) do
    %{

      "total_len" => encode_value(msg.total_len),

      "magicno" => encode_value(msg.magicno),

      "version" => encode_value(msg.version),

      "flags" => encode_value(msg.flags),

      "meta_request_type" => encode_value(msg.meta_request_type),

      "hako_time_us" => encode_value(msg.hako_time_us),

      "asset_time_us" => encode_value(msg.asset_time_us),

      "real_time_us" => encode_value(msg.real_time_us),

      "robot_name" => encode_value(msg.robot_name),

      "channel_id" => encode_value(msg.channel_id),

      "body_len" => encode_value(msg.body_len)

    }
  end

  def from_map(map) when is_map(map) do
    %__MODULE__{

      total_len: map |> get_value(:total_len, "total_len", 0) |> decode_total_len(),

      magicno: map |> get_value(:magicno, "magicno", 0) |> decode_magicno(),

      version: map |> get_value(:version, "version", 0) |> decode_version(),

      flags: map |> get_value(:flags, "flags", 0) |> decode_flags(),

      meta_request_type: map |> get_value(:meta_request_type, "meta_request_type", 0) |> decode_meta_request_type(),

      hako_time_us: map |> get_value(:hako_time_us, "hako_time_us", 0) |> decode_hako_time_us(),

      asset_time_us: map |> get_value(:asset_time_us, "asset_time_us", 0) |> decode_asset_time_us(),

      real_time_us: map |> get_value(:real_time_us, "real_time_us", 0) |> decode_real_time_us(),

      robot_name: map |> get_value(:robot_name, "robot_name", "") |> decode_robot_name(),

      channel_id: map |> get_value(:channel_id, "channel_id", 0) |> decode_channel_id(),

      body_len: map |> get_value(:body_len, "body_len", 0) |> decode_body_len()

    }
  end

  def to_json(%__MODULE__{} = msg) do
    msg
    |> to_map()
    |> json_encode()
  end

  def from_json(json) when is_binary(json) do
    json
    |> json_decode()
    |> from_map()
  end

  defp get_value(map, atom_key, string_key, default) do
    Map.get(map, atom_key, Map.get(map, string_key, default))
  end

  defp encode_value(values) when is_list(values), do: Enum.map(values, &encode_value/1)
  defp encode_value(%{__struct__: module} = value) do
    if function_exported?(module, :to_map, 1), do: module.to_map(value), else: value
  end
  defp encode_value(value), do: value

  defp json_encode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :encode!, 1) -> apply(Jason, :encode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :encode!, 1) -> apply(JSON, :encode!, [value])
      true -> raise "No JSON encoder found. Add Jason or JSON to use to_json/1."
    end
  end

  defp json_decode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :decode!, 1) -> apply(Jason, :decode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :decode!, 1) -> apply(JSON, :decode!, [value])
      true -> raise "No JSON decoder found. Add Jason or JSON to use from_json/1."
    end
  end


  defp decode_total_len(value) do
    value
  end


  defp decode_magicno(value) do
    value
  end


  defp decode_version(value) do
    value
  end


  defp decode_flags(value) do
    value
  end


  defp decode_meta_request_type(value) do
    value
  end


  defp decode_hako_time_us(value) do
    value
  end


  defp decode_asset_time_us(value) do
    value
  end


  defp decode_real_time_us(value) do
    value
  end


  defp decode_robot_name(value) do
    value
  end


  defp decode_channel_id(value) do
    value
  end


  defp decode_body_len(value) do
    value
  end

end
