defmodule HakoPdu.HakoMsgs.ShareObjectOwnerResponse do
  @moduledoc """
  ROS message: hako_msgs/ShareObjectOwnerResponse

  Generated by hakoniwa-ros2pdu.
  """

  defstruct [

    object_name: "",

    request_type: 0,

    owner_id: 0,

    accepted: false

  ]

  def new(attrs \\ %{}) when is_map(attrs) do
    struct(__MODULE__, attrs)
  end

  def to_map(%__MODULE__{} = msg) do
    %{

      "object_name" => encode_value(msg.object_name),

      "request_type" => encode_value(msg.request_type),

      "owner_id" => encode_value(msg.owner_id),

      "accepted" => encode_value(msg.accepted)

    }
  end

  def from_map(map) when is_map(map) do
    %__MODULE__{

      object_name: map |> get_value(:object_name, "object_name", "") |> decode_object_name(),

      request_type: map |> get_value(:request_type, "request_type", 0) |> decode_request_type(),

      owner_id: map |> get_value(:owner_id, "owner_id", 0) |> decode_owner_id(),

      accepted: map |> get_value(:accepted, "accepted", false) |> decode_accepted()

    }
  end

  def to_json(%__MODULE__{} = msg) do
    msg
    |> to_map()
    |> json_encode()
  end

  def from_json(json) when is_binary(json) do
    json
    |> json_decode()
    |> from_map()
  end

  defp get_value(map, atom_key, string_key, default) do
    Map.get(map, atom_key, Map.get(map, string_key, default))
  end

  defp encode_value(values) when is_list(values), do: Enum.map(values, &encode_value/1)
  defp encode_value(%{__struct__: module} = value) do
    if function_exported?(module, :to_map, 1), do: module.to_map(value), else: value
  end
  defp encode_value(value), do: value

  defp json_encode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :encode!, 1) -> apply(Jason, :encode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :encode!, 1) -> apply(JSON, :encode!, [value])
      true -> raise "No JSON encoder found. Add Jason or JSON to use to_json/1."
    end
  end

  defp json_decode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :decode!, 1) -> apply(Jason, :decode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :decode!, 1) -> apply(JSON, :decode!, [value])
      true -> raise "No JSON decoder found. Add Jason or JSON to use from_json/1."
    end
  end


  defp decode_object_name(value) do
    value
  end


  defp decode_request_type(value) do
    value
  end


  defp decode_owner_id(value) do
    value
  end


  defp decode_accepted(value) do
    value
  end

end
