defmodule HakoPdu.HakoMsgs.HakoDroneCmdMove do
  @moduledoc """
  ROS message: hako_msgs/HakoDroneCmdMove

  Generated by hakoniwa-ros2pdu.
  """

  defstruct [

    header: HakoPdu.HakoMsgs.HakoDroneCmdHeader.new(),

    x: 0.0,

    y: 0.0,

    z: 0.0,

    speed: 0.0,

    yaw_deg: 0.0

  ]

  def new(attrs \\ %{}) when is_map(attrs) do
    struct(__MODULE__, attrs)
  end

  def to_map(%__MODULE__{} = msg) do
    %{

      "header" => encode_value(msg.header),

      "x" => encode_value(msg.x),

      "y" => encode_value(msg.y),

      "z" => encode_value(msg.z),

      "speed" => encode_value(msg.speed),

      "yaw_deg" => encode_value(msg.yaw_deg)

    }
  end

  def from_map(map) when is_map(map) do
    %__MODULE__{

      header: map |> get_value(:header, "header", HakoPdu.HakoMsgs.HakoDroneCmdHeader.new()) |> decode_header(),

      x: map |> get_value(:x, "x", 0.0) |> decode_x(),

      y: map |> get_value(:y, "y", 0.0) |> decode_y(),

      z: map |> get_value(:z, "z", 0.0) |> decode_z(),

      speed: map |> get_value(:speed, "speed", 0.0) |> decode_speed(),

      yaw_deg: map |> get_value(:yaw_deg, "yaw_deg", 0.0) |> decode_yaw_deg()

    }
  end

  def to_json(%__MODULE__{} = msg) do
    msg
    |> to_map()
    |> json_encode()
  end

  def from_json(json) when is_binary(json) do
    json
    |> json_decode()
    |> from_map()
  end

  defp get_value(map, atom_key, string_key, default) do
    Map.get(map, atom_key, Map.get(map, string_key, default))
  end

  defp encode_value(values) when is_list(values), do: Enum.map(values, &encode_value/1)
  defp encode_value(%{__struct__: module} = value) do
    if function_exported?(module, :to_map, 1), do: module.to_map(value), else: value
  end
  defp encode_value(value), do: value

  defp json_encode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :encode!, 1) -> apply(Jason, :encode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :encode!, 1) -> apply(JSON, :encode!, [value])
      true -> raise "No JSON encoder found. Add Jason or JSON to use to_json/1."
    end
  end

  defp json_decode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :decode!, 1) -> apply(Jason, :decode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :decode!, 1) -> apply(JSON, :decode!, [value])
      true -> raise "No JSON decoder found. Add Jason or JSON to use from_json/1."
    end
  end


  defp decode_header(value) do
    if is_map(value), do: HakoPdu.HakoMsgs.HakoDroneCmdHeader.from_map(value), else: value
  end


  defp decode_x(value) do
    value
  end


  defp decode_y(value) do
    value
  end


  defp decode_z(value) do
    value
  end


  defp decode_speed(value) do
    value
  end


  defp decode_yaw_deg(value) do
    value
  end

end
