defmodule HakoPdu.HakoMsgs.DroneVisualStateArray do
  @moduledoc """
  ROS message: hako_msgs/DroneVisualStateArray

  Generated by hakoniwa-ros2pdu.
  """

  defstruct [

    sequence_id: 0,

    chunk_index: 0,

    chunk_count: 0,

    start_index: 0,

    valid_count: 0,

    drones: []

  ]

  def new(attrs \\ %{}) when is_map(attrs) do
    struct(__MODULE__, attrs)
  end

  def to_map(%__MODULE__{} = msg) do
    %{

      "sequence_id" => encode_value(msg.sequence_id),

      "chunk_index" => encode_value(msg.chunk_index),

      "chunk_count" => encode_value(msg.chunk_count),

      "start_index" => encode_value(msg.start_index),

      "valid_count" => encode_value(msg.valid_count),

      "drones" => encode_value(msg.drones)

    }
  end

  def from_map(map) when is_map(map) do
    %__MODULE__{

      sequence_id: map |> get_value(:sequence_id, "sequence_id", 0) |> decode_sequence_id(),

      chunk_index: map |> get_value(:chunk_index, "chunk_index", 0) |> decode_chunk_index(),

      chunk_count: map |> get_value(:chunk_count, "chunk_count", 0) |> decode_chunk_count(),

      start_index: map |> get_value(:start_index, "start_index", 0) |> decode_start_index(),

      valid_count: map |> get_value(:valid_count, "valid_count", 0) |> decode_valid_count(),

      drones: map |> get_value(:drones, "drones", []) |> decode_drones()

    }
  end

  def to_json(%__MODULE__{} = msg) do
    msg
    |> to_map()
    |> json_encode()
  end

  def from_json(json) when is_binary(json) do
    json
    |> json_decode()
    |> from_map()
  end

  defp get_value(map, atom_key, string_key, default) do
    Map.get(map, atom_key, Map.get(map, string_key, default))
  end

  defp encode_value(values) when is_list(values), do: Enum.map(values, &encode_value/1)
  defp encode_value(%{__struct__: module} = value) do
    if function_exported?(module, :to_map, 1), do: module.to_map(value), else: value
  end
  defp encode_value(value), do: value

  defp json_encode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :encode!, 1) -> apply(Jason, :encode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :encode!, 1) -> apply(JSON, :encode!, [value])
      true -> raise "No JSON encoder found. Add Jason or JSON to use to_json/1."
    end
  end

  defp json_decode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :decode!, 1) -> apply(Jason, :decode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :decode!, 1) -> apply(JSON, :decode!, [value])
      true -> raise "No JSON decoder found. Add Jason or JSON to use from_json/1."
    end
  end


  defp decode_sequence_id(value) do
    value
  end


  defp decode_chunk_index(value) do
    value
  end


  defp decode_chunk_count(value) do
    value
  end


  defp decode_start_index(value) do
    value
  end


  defp decode_valid_count(value) do
    value
  end


  defp decode_drones(value) do
    Enum.map(value || [], &HakoPdu.HakoMsgs.DroneVisualState.from_map/1)
  end

end
