defmodule HakoPdu.HakoSrvMsgs.GetSimStateResponse do
  @moduledoc """
  ROS message: hako_srv_msgs/GetSimStateResponse

  Generated by hakoniwa-ros2pdu.
  """

  defstruct [

    sim_state: 0,

    master_time: 0,

    is_pdu_created: false,

    is_simulation_mode: false,

    is_pdu_sync_mode: false

  ]

  def new(attrs \\ %{}) when is_map(attrs) do
    struct(__MODULE__, attrs)
  end

  def to_map(%__MODULE__{} = msg) do
    %{

      "sim_state" => encode_value(msg.sim_state),

      "master_time" => encode_value(msg.master_time),

      "is_pdu_created" => encode_value(msg.is_pdu_created),

      "is_simulation_mode" => encode_value(msg.is_simulation_mode),

      "is_pdu_sync_mode" => encode_value(msg.is_pdu_sync_mode)

    }
  end

  def from_map(map) when is_map(map) do
    %__MODULE__{

      sim_state: map |> get_value(:sim_state, "sim_state", 0) |> decode_sim_state(),

      master_time: map |> get_value(:master_time, "master_time", 0) |> decode_master_time(),

      is_pdu_created: map |> get_value(:is_pdu_created, "is_pdu_created", false) |> decode_is_pdu_created(),

      is_simulation_mode: map |> get_value(:is_simulation_mode, "is_simulation_mode", false) |> decode_is_simulation_mode(),

      is_pdu_sync_mode: map |> get_value(:is_pdu_sync_mode, "is_pdu_sync_mode", false) |> decode_is_pdu_sync_mode()

    }
  end

  def to_json(%__MODULE__{} = msg) do
    msg
    |> to_map()
    |> json_encode()
  end

  def from_json(json) when is_binary(json) do
    json
    |> json_decode()
    |> from_map()
  end

  defp get_value(map, atom_key, string_key, default) do
    Map.get(map, atom_key, Map.get(map, string_key, default))
  end

  defp encode_value(values) when is_list(values), do: Enum.map(values, &encode_value/1)
  defp encode_value(%{__struct__: module} = value) do
    if function_exported?(module, :to_map, 1), do: module.to_map(value), else: value
  end
  defp encode_value(value), do: value

  defp json_encode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :encode!, 1) -> apply(Jason, :encode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :encode!, 1) -> apply(JSON, :encode!, [value])
      true -> raise "No JSON encoder found. Add Jason or JSON to use to_json/1."
    end
  end

  defp json_decode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :decode!, 1) -> apply(Jason, :decode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :decode!, 1) -> apply(JSON, :decode!, [value])
      true -> raise "No JSON decoder found. Add Jason or JSON to use from_json/1."
    end
  end


  defp decode_sim_state(value) do
    value
  end


  defp decode_master_time(value) do
    value
  end


  defp decode_is_pdu_created(value) do
    value
  end


  defp decode_is_simulation_mode(value) do
    value
  end


  defp decode_is_pdu_sync_mode(value) do
    value
  end

end
