defmodule HakoPdu.HakoSrvMsgs.ServiceResponseHeader do
  @moduledoc """
  ROS message: hako_srv_msgs/ServiceResponseHeader

  Generated by hakoniwa-ros2pdu.
  """

  defstruct [

    request_id: 0,

    service_name: "",

    client_name: "",

    status: 0,

    processing_percentage: 0,

    result_code: 0

  ]

  def new(attrs \\ %{}) when is_map(attrs) do
    struct(__MODULE__, attrs)
  end

  def to_map(%__MODULE__{} = msg) do
    %{

      "request_id" => encode_value(msg.request_id),

      "service_name" => encode_value(msg.service_name),

      "client_name" => encode_value(msg.client_name),

      "status" => encode_value(msg.status),

      "processing_percentage" => encode_value(msg.processing_percentage),

      "result_code" => encode_value(msg.result_code)

    }
  end

  def from_map(map) when is_map(map) do
    %__MODULE__{

      request_id: map |> get_value(:request_id, "request_id", 0) |> decode_request_id(),

      service_name: map |> get_value(:service_name, "service_name", "") |> decode_service_name(),

      client_name: map |> get_value(:client_name, "client_name", "") |> decode_client_name(),

      status: map |> get_value(:status, "status", 0) |> decode_status(),

      processing_percentage: map |> get_value(:processing_percentage, "processing_percentage", 0) |> decode_processing_percentage(),

      result_code: map |> get_value(:result_code, "result_code", 0) |> decode_result_code()

    }
  end

  def to_json(%__MODULE__{} = msg) do
    msg
    |> to_map()
    |> json_encode()
  end

  def from_json(json) when is_binary(json) do
    json
    |> json_decode()
    |> from_map()
  end

  defp get_value(map, atom_key, string_key, default) do
    Map.get(map, atom_key, Map.get(map, string_key, default))
  end

  defp encode_value(values) when is_list(values), do: Enum.map(values, &encode_value/1)
  defp encode_value(%{__struct__: module} = value) do
    if function_exported?(module, :to_map, 1), do: module.to_map(value), else: value
  end
  defp encode_value(value), do: value

  defp json_encode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :encode!, 1) -> apply(Jason, :encode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :encode!, 1) -> apply(JSON, :encode!, [value])
      true -> raise "No JSON encoder found. Add Jason or JSON to use to_json/1."
    end
  end

  defp json_decode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :decode!, 1) -> apply(Jason, :decode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :decode!, 1) -> apply(JSON, :decode!, [value])
      true -> raise "No JSON decoder found. Add Jason or JSON to use from_json/1."
    end
  end


  defp decode_request_id(value) do
    value
  end


  defp decode_service_name(value) do
    value
  end


  defp decode_client_name(value) do
    value
  end


  defp decode_status(value) do
    value
  end


  defp decode_processing_percentage(value) do
    value
  end


  defp decode_result_code(value) do
    value
  end

end
