require_relative '../ev3_msgs/pdu_type_Ev3PduColorSensor'
require_relative '../ev3_msgs/pdu_type_Ev3PduSensorHeader'
require_relative '../ev3_msgs/pdu_type_Ev3PduTouchSensor'
require 'json'

module HakoPdu
  module Ev3Msgs
    # ROS message: ev3_msgs/Ev3PduSensor
    # Generated by hakoniwa-ros2pdu.
    class Ev3PduSensor
      attr_accessor :head, :buttons, :color_sensors, :touch_sensors, :motor_angle, :gyro_degree, :gyro_degree_rate, :sensor_ultrasonic, :gps_lat, :gps_lon

      def initialize(head: HakoPdu::Ev3Msgs::Ev3PduSensorHeader.new, buttons: [], color_sensors: [], touch_sensors: [], motor_angle: [], gyro_degree: 0, gyro_degree_rate: 0, sensor_ultrasonic: 0, gps_lat: 0.0, gps_lon: 0.0)

        @head = head

        @buttons = buttons

        @color_sensors = color_sensors

        @touch_sensors = touch_sensors

        @motor_angle = motor_angle

        @gyro_degree = gyro_degree

        @gyro_degree_rate = gyro_degree_rate

        @sensor_ultrasonic = sensor_ultrasonic

        @gps_lat = gps_lat

        @gps_lon = gps_lon

      end

      def to_h
        {

          'head' => self.class.encode_value(@head),

          'buttons' => self.class.encode_value(@buttons),

          'color_sensors' => self.class.encode_value(@color_sensors),

          'touch_sensors' => self.class.encode_value(@touch_sensors),

          'motor_angle' => self.class.encode_value(@motor_angle),

          'gyro_degree' => self.class.encode_value(@gyro_degree),

          'gyro_degree_rate' => self.class.encode_value(@gyro_degree_rate),

          'sensor_ultrasonic' => self.class.encode_value(@sensor_ultrasonic),

          'gps_lat' => self.class.encode_value(@gps_lat),

          'gps_lon' => self.class.encode_value(@gps_lon)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          head: decode_head(hash.fetch('head', HakoPdu::Ev3Msgs::Ev3PduSensorHeader.new)),

          buttons: decode_buttons(hash.fetch('buttons', [])),

          color_sensors: decode_color_sensors(hash.fetch('color_sensors', [])),

          touch_sensors: decode_touch_sensors(hash.fetch('touch_sensors', [])),

          motor_angle: decode_motor_angle(hash.fetch('motor_angle', [])),

          gyro_degree: decode_gyro_degree(hash.fetch('gyro_degree', 0)),

          gyro_degree_rate: decode_gyro_degree_rate(hash.fetch('gyro_degree_rate', 0)),

          sensor_ultrasonic: decode_sensor_ultrasonic(hash.fetch('sensor_ultrasonic', 0)),

          gps_lat: decode_gps_lat(hash.fetch('gps_lat', 0.0)),

          gps_lon: decode_gps_lon(hash.fetch('gps_lon', 0.0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_head(value)
        value.is_a?(Hash) ? HakoPdu::Ev3Msgs::Ev3PduSensorHeader.from_h(value) : value
      end


      def self.decode_buttons(value)
        value
      end


      def self.decode_color_sensors(value)
        return [] if value.nil?
        value.map { |item| HakoPdu::Ev3Msgs::Ev3PduColorSensor.from_h(item) }
      end


      def self.decode_touch_sensors(value)
        return [] if value.nil?
        value.map { |item| HakoPdu::Ev3Msgs::Ev3PduTouchSensor.from_h(item) }
      end


      def self.decode_motor_angle(value)
        value
      end


      def self.decode_gyro_degree(value)
        value
      end


      def self.decode_gyro_degree_rate(value)
        value
      end


      def self.decode_sensor_ultrasonic(value)
        value
      end


      def self.decode_gps_lat(value)
        value
      end


      def self.decode_gps_lon(value)
        value
      end

end
  end
end
