require 'json'

module HakoPdu
  module Ev3Msgs
    # ROS message: ev3_msgs/Ev3PduActuatorHeader
    # Generated by hakoniwa-ros2pdu.
    class Ev3PduActuatorHeader
      attr_accessor :name, :version, :asset_time, :ext_off, :ext_size

      def initialize(name: "", version: 0, asset_time: 0, ext_off: 0, ext_size: 0)

        @name = name

        @version = version

        @asset_time = asset_time

        @ext_off = ext_off

        @ext_size = ext_size

      end

      def to_h
        {

          'name' => self.class.encode_value(@name),

          'version' => self.class.encode_value(@version),

          'asset_time' => self.class.encode_value(@asset_time),

          'ext_off' => self.class.encode_value(@ext_off),

          'ext_size' => self.class.encode_value(@ext_size)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          name: decode_name(hash.fetch('name', "")),

          version: decode_version(hash.fetch('version', 0)),

          asset_time: decode_asset_time(hash.fetch('asset_time', 0)),

          ext_off: decode_ext_off(hash.fetch('ext_off', 0)),

          ext_size: decode_ext_size(hash.fetch('ext_size', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_name(value)
        value
      end


      def self.decode_version(value)
        value
      end


      def self.decode_asset_time(value)
        value
      end


      def self.decode_ext_off(value)
        value
      end


      def self.decode_ext_size(value)
        value
      end

end
  end
end
