require 'json'

module HakoPdu
  module Ev3Msgs
    # ROS message: ev3_msgs/Ev3PduColorSensor
    # Generated by hakoniwa-ros2pdu.
    class Ev3PduColorSensor
      attr_accessor :color, :reflect, :rgb_r, :rgb_g, :rgb_b

      def initialize(color: 0, reflect: 0, rgb_r: 0, rgb_g: 0, rgb_b: 0)

        @color = color

        @reflect = reflect

        @rgb_r = rgb_r

        @rgb_g = rgb_g

        @rgb_b = rgb_b

      end

      def to_h
        {

          'color' => self.class.encode_value(@color),

          'reflect' => self.class.encode_value(@reflect),

          'rgb_r' => self.class.encode_value(@rgb_r),

          'rgb_g' => self.class.encode_value(@rgb_g),

          'rgb_b' => self.class.encode_value(@rgb_b)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          color: decode_color(hash.fetch('color', 0)),

          reflect: decode_reflect(hash.fetch('reflect', 0)),

          rgb_r: decode_rgb_r(hash.fetch('rgb_r', 0)),

          rgb_g: decode_rgb_g(hash.fetch('rgb_g', 0)),

          rgb_b: decode_rgb_b(hash.fetch('rgb_b', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_color(value)
        value
      end


      def self.decode_reflect(value)
        value
      end


      def self.decode_rgb_r(value)
        value
      end


      def self.decode_rgb_g(value)
        value
      end


      def self.decode_rgb_b(value)
        value
      end

end
  end
end
