defmodule HakoPdu.HakoActionMsgs.ActionFeedbackHeader do
  @moduledoc """
  ROS message: hako_action_msgs/ActionFeedbackHeader

  Generated by hakoniwa-ros2pdu.
  """

  defstruct [

    version: 0,

    reserved: [],

    goal_id: [],

    sequence_no: 0

  ]

  def new(attrs \\ %{}) when is_map(attrs) do
    struct(__MODULE__, attrs)
  end

  def to_map(%__MODULE__{} = msg) do
    %{

      "version" => encode_value(msg.version),

      "reserved" => encode_value(msg.reserved),

      "goal_id" => encode_value(msg.goal_id),

      "sequence_no" => encode_value(msg.sequence_no)

    }
  end

  def from_map(map) when is_map(map) do
    %__MODULE__{

      version: map |> get_value(:version, "version", 0) |> decode_version(),

      reserved: map |> get_value(:reserved, "reserved", []) |> decode_reserved(),

      goal_id: map |> get_value(:goal_id, "goal_id", []) |> decode_goal_id(),

      sequence_no: map |> get_value(:sequence_no, "sequence_no", 0) |> decode_sequence_no()

    }
  end

  def to_json(%__MODULE__{} = msg) do
    msg
    |> to_map()
    |> json_encode()
  end

  def from_json(json) when is_binary(json) do
    json
    |> json_decode()
    |> from_map()
  end

  defp get_value(map, atom_key, string_key, default) do
    Map.get(map, atom_key, Map.get(map, string_key, default))
  end

  defp encode_value(values) when is_list(values), do: Enum.map(values, &encode_value/1)
  defp encode_value(%{__struct__: module} = value) do
    if function_exported?(module, :to_map, 1), do: module.to_map(value), else: value
  end
  defp encode_value(value), do: value

  defp json_encode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :encode!, 1) -> apply(Jason, :encode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :encode!, 1) -> apply(JSON, :encode!, [value])
      true -> raise "No JSON encoder found. Add Jason or JSON to use to_json/1."
    end
  end

  defp json_decode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :decode!, 1) -> apply(Jason, :decode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :decode!, 1) -> apply(JSON, :decode!, [value])
      true -> raise "No JSON decoder found. Add Jason or JSON to use from_json/1."
    end
  end


  defp decode_version(value) do
    value
  end


  defp decode_reserved(value) do
    value
  end


  defp decode_goal_id(value) do
    value
  end


  defp decode_sequence_no(value) do
    value
  end

end
