from typing import List

# dependencies for the generated Python class
from ..geometry_msgs.pdu_pytype_Point32 import Point32


# class definition for the ROS message
class Polygon:
    """
    ROS message: geometry_msgs/Polygon
    Generated by hakoniwa-ros2pdu.
    """

    points: List[Point32]

    def __init__(self):
        self.points = []

    def __str__(self):
        return f"Polygon(" + ", ".join([
            f"points={self.points}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'points'
        field_val = self.points
        if isinstance(field_val, bytearray):
            d['points'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['points'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['points'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['points'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'points'
        if 'points' in d:
            field_type = cls.__annotations__.get('points')
            value = d['points']
            
            if field_type is bytearray:
                obj.points = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.points = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.points = value
            elif hasattr(field_type, 'from_dict'):
                obj.points = field_type.from_dict(value)
            else:
                obj.points = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
