from typing import List

# dependencies for the generated Python class
from ..std_msgs.pdu_pytype_Header import Header
from ..builtin_interfaces.pdu_pytype_Time import Time
from ..geometry_msgs.pdu_pytype_Vector3 import Vector3
from ..geometry_msgs.pdu_pytype_Wrench import Wrench


# class definition for the ROS message
class WrenchStamped:
    """
    ROS message: geometry_msgs/WrenchStamped
    Generated by hakoniwa-ros2pdu.
    """

    header: Header
    wrench: Wrench

    def __init__(self):
        self.header = Header()
        self.wrench = Wrench()

    def __str__(self):
        return f"WrenchStamped(" + ", ".join([
            f"header={self.header}"
            f"wrench={self.wrench}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'header'
        field_val = self.header
        if isinstance(field_val, bytearray):
            d['header'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['header'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['header'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['header'] = field_val
        # handle field 'wrench'
        field_val = self.wrench
        if isinstance(field_val, bytearray):
            d['wrench'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['wrench'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['wrench'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['wrench'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'header'
        if 'header' in d:
            field_type = cls.__annotations__.get('header')
            value = d['header']
            
            if field_type is bytearray:
                obj.header = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.header = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.header = value
            elif hasattr(field_type, 'from_dict'):
                obj.header = field_type.from_dict(value)
            else:
                obj.header = value
        # handle field 'wrench'
        if 'wrench' in d:
            field_type = cls.__annotations__.get('wrench')
            value = d['wrench']
            
            if field_type is bytearray:
                obj.wrench = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.wrench = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.wrench = value
            elif hasattr(field_type, 'from_dict'):
                obj.wrench = field_type.from_dict(value)
            else:
                obj.wrench = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
