from typing import List

# dependencies for the generated Python class
from ..geometry_msgs.pdu_pytype_Vector3 import Vector3


# class definition for the ROS message
class Wrench:
    """
    ROS message: geometry_msgs/Wrench
    Generated by hakoniwa-ros2pdu.
    """

    force: Vector3
    torque: Vector3

    def __init__(self):
        self.force = Vector3()
        self.torque = Vector3()

    def __str__(self):
        return f"Wrench(" + ", ".join([
            f"force={self.force}"
            f"torque={self.torque}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'force'
        field_val = self.force
        if isinstance(field_val, bytearray):
            d['force'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['force'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['force'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['force'] = field_val
        # handle field 'torque'
        field_val = self.torque
        if isinstance(field_val, bytearray):
            d['torque'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['torque'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['torque'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['torque'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'force'
        if 'force' in d:
            field_type = cls.__annotations__.get('force')
            value = d['force']
            
            if field_type is bytearray:
                obj.force = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.force = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.force = value
            elif hasattr(field_type, 'from_dict'):
                obj.force = field_type.from_dict(value)
            else:
                obj.force = value
        # handle field 'torque'
        if 'torque' in d:
            field_type = cls.__annotations__.get('torque')
            value = d['torque']
            
            if field_type is bytearray:
                obj.torque = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.torque = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.torque = value
            elif hasattr(field_type, 'from_dict'):
                obj.torque = field_type.from_dict(value)
            else:
                obj.torque = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
