from typing import List

# dependencies for the generated Python class
from ..std_msgs.pdu_pytype_Header import Header
from ..builtin_interfaces.pdu_pytype_Time import Time


# class definition for the ROS message
class TimeReference:
    """
    ROS message: sensor_msgs/TimeReference
    Generated by hakoniwa-ros2pdu.
    """

    header: Header
    time_ref: Time
    source: str

    def __init__(self):
        self.header = Header()
        self.time_ref = Time()
        self.source = ""

    def __str__(self):
        return f"TimeReference(" + ", ".join([
            f"header={self.header}"
            f"time_ref={self.time_ref}"
            f"source={self.source}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'header'
        field_val = self.header
        if isinstance(field_val, bytearray):
            d['header'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['header'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['header'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['header'] = field_val
        # handle field 'time_ref'
        field_val = self.time_ref
        if isinstance(field_val, bytearray):
            d['time_ref'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['time_ref'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['time_ref'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['time_ref'] = field_val
        # handle field 'source'
        field_val = self.source
        if isinstance(field_val, bytearray):
            d['source'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['source'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['source'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['source'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'header'
        if 'header' in d:
            field_type = cls.__annotations__.get('header')
            value = d['header']
            
            if field_type is bytearray:
                obj.header = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.header = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.header = value
            elif hasattr(field_type, 'from_dict'):
                obj.header = field_type.from_dict(value)
            else:
                obj.header = value
        # handle field 'time_ref'
        if 'time_ref' in d:
            field_type = cls.__annotations__.get('time_ref')
            value = d['time_ref']
            
            if field_type is bytearray:
                obj.time_ref = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.time_ref = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.time_ref = value
            elif hasattr(field_type, 'from_dict'):
                obj.time_ref = field_type.from_dict(value)
            else:
                obj.time_ref = value
        # handle field 'source'
        if 'source' in d:
            field_type = cls.__annotations__.get('source')
            value = d['source']
            
            if field_type is bytearray:
                obj.source = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.source = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.source = value
            elif hasattr(field_type, 'from_dict'):
                obj.source = field_type.from_dict(value)
            else:
                obj.source = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
