from typing import List

# dependencies for the generated Python class
from ..std_msgs.pdu_pytype_Header import Header
from ..sensor_msgs.pdu_pytype_NavSatStatus import NavSatStatus
from ..builtin_interfaces.pdu_pytype_Time import Time


# class definition for the ROS message
class NavSatFix:
    """
    ROS message: sensor_msgs/NavSatFix
    Generated by hakoniwa-ros2pdu.
    """

    header: Header
    status: NavSatStatus
    latitude: float
    longitude: float
    altitude: float
    position_covariance: List[float]
    position_covariance_type: int

    def __init__(self):
        self.header = Header()
        self.status = NavSatStatus()
        self.latitude = 0.0
        self.longitude = 0.0
        self.altitude = 0.0
        self.position_covariance = []
        self.position_covariance_type = 0

    def __str__(self):
        return f"NavSatFix(" + ", ".join([
            f"header={self.header}"
            f"status={self.status}"
            f"latitude={self.latitude}"
            f"longitude={self.longitude}"
            f"altitude={self.altitude}"
            f"position_covariance={self.position_covariance}"
            f"position_covariance_type={self.position_covariance_type}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'header'
        field_val = self.header
        if isinstance(field_val, bytearray):
            d['header'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['header'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['header'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['header'] = field_val
        # handle field 'status'
        field_val = self.status
        if isinstance(field_val, bytearray):
            d['status'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['status'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['status'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['status'] = field_val
        # handle field 'latitude'
        field_val = self.latitude
        if isinstance(field_val, bytearray):
            d['latitude'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['latitude'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['latitude'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['latitude'] = field_val
        # handle field 'longitude'
        field_val = self.longitude
        if isinstance(field_val, bytearray):
            d['longitude'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['longitude'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['longitude'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['longitude'] = field_val
        # handle field 'altitude'
        field_val = self.altitude
        if isinstance(field_val, bytearray):
            d['altitude'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['altitude'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['altitude'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['altitude'] = field_val
        # handle field 'position_covariance'
        field_val = self.position_covariance
        if isinstance(field_val, bytearray):
            d['position_covariance'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['position_covariance'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['position_covariance'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['position_covariance'] = field_val
        # handle field 'position_covariance_type'
        field_val = self.position_covariance_type
        if isinstance(field_val, bytearray):
            d['position_covariance_type'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['position_covariance_type'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['position_covariance_type'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['position_covariance_type'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'header'
        if 'header' in d:
            field_type = cls.__annotations__.get('header')
            value = d['header']
            
            if field_type is bytearray:
                obj.header = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.header = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.header = value
            elif hasattr(field_type, 'from_dict'):
                obj.header = field_type.from_dict(value)
            else:
                obj.header = value
        # handle field 'status'
        if 'status' in d:
            field_type = cls.__annotations__.get('status')
            value = d['status']
            
            if field_type is bytearray:
                obj.status = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.status = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.status = value
            elif hasattr(field_type, 'from_dict'):
                obj.status = field_type.from_dict(value)
            else:
                obj.status = value
        # handle field 'latitude'
        if 'latitude' in d:
            field_type = cls.__annotations__.get('latitude')
            value = d['latitude']
            
            if field_type is bytearray:
                obj.latitude = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.latitude = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.latitude = value
            elif hasattr(field_type, 'from_dict'):
                obj.latitude = field_type.from_dict(value)
            else:
                obj.latitude = value
        # handle field 'longitude'
        if 'longitude' in d:
            field_type = cls.__annotations__.get('longitude')
            value = d['longitude']
            
            if field_type is bytearray:
                obj.longitude = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.longitude = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.longitude = value
            elif hasattr(field_type, 'from_dict'):
                obj.longitude = field_type.from_dict(value)
            else:
                obj.longitude = value
        # handle field 'altitude'
        if 'altitude' in d:
            field_type = cls.__annotations__.get('altitude')
            value = d['altitude']
            
            if field_type is bytearray:
                obj.altitude = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.altitude = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.altitude = value
            elif hasattr(field_type, 'from_dict'):
                obj.altitude = field_type.from_dict(value)
            else:
                obj.altitude = value
        # handle field 'position_covariance'
        if 'position_covariance' in d:
            field_type = cls.__annotations__.get('position_covariance')
            value = d['position_covariance']
            
            if field_type is bytearray:
                obj.position_covariance = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.position_covariance = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.position_covariance = value
            elif hasattr(field_type, 'from_dict'):
                obj.position_covariance = field_type.from_dict(value)
            else:
                obj.position_covariance = value
        # handle field 'position_covariance_type'
        if 'position_covariance_type' in d:
            field_type = cls.__annotations__.get('position_covariance_type')
            value = d['position_covariance_type']
            
            if field_type is bytearray:
                obj.position_covariance_type = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.position_covariance_type = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.position_covariance_type = value
            elif hasattr(field_type, 'from_dict'):
                obj.position_covariance_type = field_type.from_dict(value)
            else:
                obj.position_covariance_type = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
