from typing import List

# dependencies for the generated Python class
from ..std_msgs.pdu_pytype_Header import Header
from ..builtin_interfaces.pdu_pytype_Time import Time


# class definition for the ROS message
class BatteryState:
    """
    ROS message: sensor_msgs/BatteryState
    Generated by hakoniwa-ros2pdu.
    """

    header: Header
    voltage: float
    temperature: float
    current: float
    charge: float
    capacity: float
    design_capacity: float
    percentage: float
    power_supply_status: int
    power_supply_health: int
    power_supply_technology: int
    present: bool
    cell_voltage: List[float]
    cell_temperature: List[float]
    location: str
    serial_number: str

    def __init__(self):
        self.header = Header()
        self.voltage = 0.0
        self.temperature = 0.0
        self.current = 0.0
        self.charge = 0.0
        self.capacity = 0.0
        self.design_capacity = 0.0
        self.percentage = 0.0
        self.power_supply_status = 0
        self.power_supply_health = 0
        self.power_supply_technology = 0
        self.present = False
        self.cell_voltage = []
        self.cell_temperature = []
        self.location = ""
        self.serial_number = ""

    def __str__(self):
        return f"BatteryState(" + ", ".join([
            f"header={self.header}"
            f"voltage={self.voltage}"
            f"temperature={self.temperature}"
            f"current={self.current}"
            f"charge={self.charge}"
            f"capacity={self.capacity}"
            f"design_capacity={self.design_capacity}"
            f"percentage={self.percentage}"
            f"power_supply_status={self.power_supply_status}"
            f"power_supply_health={self.power_supply_health}"
            f"power_supply_technology={self.power_supply_technology}"
            f"present={self.present}"
            f"cell_voltage={self.cell_voltage}"
            f"cell_temperature={self.cell_temperature}"
            f"location={self.location}"
            f"serial_number={self.serial_number}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'header'
        field_val = self.header
        if isinstance(field_val, bytearray):
            d['header'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['header'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['header'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['header'] = field_val
        # handle field 'voltage'
        field_val = self.voltage
        if isinstance(field_val, bytearray):
            d['voltage'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['voltage'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['voltage'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['voltage'] = field_val
        # handle field 'temperature'
        field_val = self.temperature
        if isinstance(field_val, bytearray):
            d['temperature'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['temperature'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['temperature'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['temperature'] = field_val
        # handle field 'current'
        field_val = self.current
        if isinstance(field_val, bytearray):
            d['current'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['current'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['current'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['current'] = field_val
        # handle field 'charge'
        field_val = self.charge
        if isinstance(field_val, bytearray):
            d['charge'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['charge'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['charge'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['charge'] = field_val
        # handle field 'capacity'
        field_val = self.capacity
        if isinstance(field_val, bytearray):
            d['capacity'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['capacity'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['capacity'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['capacity'] = field_val
        # handle field 'design_capacity'
        field_val = self.design_capacity
        if isinstance(field_val, bytearray):
            d['design_capacity'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['design_capacity'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['design_capacity'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['design_capacity'] = field_val
        # handle field 'percentage'
        field_val = self.percentage
        if isinstance(field_val, bytearray):
            d['percentage'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['percentage'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['percentage'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['percentage'] = field_val
        # handle field 'power_supply_status'
        field_val = self.power_supply_status
        if isinstance(field_val, bytearray):
            d['power_supply_status'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['power_supply_status'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['power_supply_status'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['power_supply_status'] = field_val
        # handle field 'power_supply_health'
        field_val = self.power_supply_health
        if isinstance(field_val, bytearray):
            d['power_supply_health'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['power_supply_health'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['power_supply_health'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['power_supply_health'] = field_val
        # handle field 'power_supply_technology'
        field_val = self.power_supply_technology
        if isinstance(field_val, bytearray):
            d['power_supply_technology'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['power_supply_technology'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['power_supply_technology'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['power_supply_technology'] = field_val
        # handle field 'present'
        field_val = self.present
        if isinstance(field_val, bytearray):
            d['present'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['present'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['present'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['present'] = field_val
        # handle field 'cell_voltage'
        field_val = self.cell_voltage
        if isinstance(field_val, bytearray):
            d['cell_voltage'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['cell_voltage'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['cell_voltage'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['cell_voltage'] = field_val
        # handle field 'cell_temperature'
        field_val = self.cell_temperature
        if isinstance(field_val, bytearray):
            d['cell_temperature'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['cell_temperature'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['cell_temperature'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['cell_temperature'] = field_val
        # handle field 'location'
        field_val = self.location
        if isinstance(field_val, bytearray):
            d['location'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['location'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['location'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['location'] = field_val
        # handle field 'serial_number'
        field_val = self.serial_number
        if isinstance(field_val, bytearray):
            d['serial_number'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['serial_number'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['serial_number'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['serial_number'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'header'
        if 'header' in d:
            field_type = cls.__annotations__.get('header')
            value = d['header']
            
            if field_type is bytearray:
                obj.header = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.header = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.header = value
            elif hasattr(field_type, 'from_dict'):
                obj.header = field_type.from_dict(value)
            else:
                obj.header = value
        # handle field 'voltage'
        if 'voltage' in d:
            field_type = cls.__annotations__.get('voltage')
            value = d['voltage']
            
            if field_type is bytearray:
                obj.voltage = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.voltage = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.voltage = value
            elif hasattr(field_type, 'from_dict'):
                obj.voltage = field_type.from_dict(value)
            else:
                obj.voltage = value
        # handle field 'temperature'
        if 'temperature' in d:
            field_type = cls.__annotations__.get('temperature')
            value = d['temperature']
            
            if field_type is bytearray:
                obj.temperature = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.temperature = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.temperature = value
            elif hasattr(field_type, 'from_dict'):
                obj.temperature = field_type.from_dict(value)
            else:
                obj.temperature = value
        # handle field 'current'
        if 'current' in d:
            field_type = cls.__annotations__.get('current')
            value = d['current']
            
            if field_type is bytearray:
                obj.current = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.current = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.current = value
            elif hasattr(field_type, 'from_dict'):
                obj.current = field_type.from_dict(value)
            else:
                obj.current = value
        # handle field 'charge'
        if 'charge' in d:
            field_type = cls.__annotations__.get('charge')
            value = d['charge']
            
            if field_type is bytearray:
                obj.charge = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.charge = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.charge = value
            elif hasattr(field_type, 'from_dict'):
                obj.charge = field_type.from_dict(value)
            else:
                obj.charge = value
        # handle field 'capacity'
        if 'capacity' in d:
            field_type = cls.__annotations__.get('capacity')
            value = d['capacity']
            
            if field_type is bytearray:
                obj.capacity = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.capacity = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.capacity = value
            elif hasattr(field_type, 'from_dict'):
                obj.capacity = field_type.from_dict(value)
            else:
                obj.capacity = value
        # handle field 'design_capacity'
        if 'design_capacity' in d:
            field_type = cls.__annotations__.get('design_capacity')
            value = d['design_capacity']
            
            if field_type is bytearray:
                obj.design_capacity = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.design_capacity = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.design_capacity = value
            elif hasattr(field_type, 'from_dict'):
                obj.design_capacity = field_type.from_dict(value)
            else:
                obj.design_capacity = value
        # handle field 'percentage'
        if 'percentage' in d:
            field_type = cls.__annotations__.get('percentage')
            value = d['percentage']
            
            if field_type is bytearray:
                obj.percentage = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.percentage = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.percentage = value
            elif hasattr(field_type, 'from_dict'):
                obj.percentage = field_type.from_dict(value)
            else:
                obj.percentage = value
        # handle field 'power_supply_status'
        if 'power_supply_status' in d:
            field_type = cls.__annotations__.get('power_supply_status')
            value = d['power_supply_status']
            
            if field_type is bytearray:
                obj.power_supply_status = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.power_supply_status = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.power_supply_status = value
            elif hasattr(field_type, 'from_dict'):
                obj.power_supply_status = field_type.from_dict(value)
            else:
                obj.power_supply_status = value
        # handle field 'power_supply_health'
        if 'power_supply_health' in d:
            field_type = cls.__annotations__.get('power_supply_health')
            value = d['power_supply_health']
            
            if field_type is bytearray:
                obj.power_supply_health = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.power_supply_health = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.power_supply_health = value
            elif hasattr(field_type, 'from_dict'):
                obj.power_supply_health = field_type.from_dict(value)
            else:
                obj.power_supply_health = value
        # handle field 'power_supply_technology'
        if 'power_supply_technology' in d:
            field_type = cls.__annotations__.get('power_supply_technology')
            value = d['power_supply_technology']
            
            if field_type is bytearray:
                obj.power_supply_technology = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.power_supply_technology = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.power_supply_technology = value
            elif hasattr(field_type, 'from_dict'):
                obj.power_supply_technology = field_type.from_dict(value)
            else:
                obj.power_supply_technology = value
        # handle field 'present'
        if 'present' in d:
            field_type = cls.__annotations__.get('present')
            value = d['present']
            
            if field_type is bytearray:
                obj.present = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.present = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.present = value
            elif hasattr(field_type, 'from_dict'):
                obj.present = field_type.from_dict(value)
            else:
                obj.present = value
        # handle field 'cell_voltage'
        if 'cell_voltage' in d:
            field_type = cls.__annotations__.get('cell_voltage')
            value = d['cell_voltage']
            
            if field_type is bytearray:
                obj.cell_voltage = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.cell_voltage = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.cell_voltage = value
            elif hasattr(field_type, 'from_dict'):
                obj.cell_voltage = field_type.from_dict(value)
            else:
                obj.cell_voltage = value
        # handle field 'cell_temperature'
        if 'cell_temperature' in d:
            field_type = cls.__annotations__.get('cell_temperature')
            value = d['cell_temperature']
            
            if field_type is bytearray:
                obj.cell_temperature = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.cell_temperature = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.cell_temperature = value
            elif hasattr(field_type, 'from_dict'):
                obj.cell_temperature = field_type.from_dict(value)
            else:
                obj.cell_temperature = value
        # handle field 'location'
        if 'location' in d:
            field_type = cls.__annotations__.get('location')
            value = d['location']
            
            if field_type is bytearray:
                obj.location = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.location = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.location = value
            elif hasattr(field_type, 'from_dict'):
                obj.location = field_type.from_dict(value)
            else:
                obj.location = value
        # handle field 'serial_number'
        if 'serial_number' in d:
            field_type = cls.__annotations__.get('serial_number')
            value = d['serial_number']
            
            if field_type is bytearray:
                obj.serial_number = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.serial_number = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.serial_number = value
            elif hasattr(field_type, 'from_dict'):
                obj.serial_number = field_type.from_dict(value)
            else:
                obj.serial_number = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
