from typing import List

# dependencies for the generated Python class
from ..std_msgs.pdu_pytype_Header import Header
from ..builtin_interfaces.pdu_pytype_Time import Time


# class definition for the ROS message
class Illuminance:
    """
    ROS message: sensor_msgs/Illuminance
    Generated by hakoniwa-ros2pdu.
    """

    header: Header
    illuminance: float
    variance: float

    def __init__(self):
        self.header = Header()
        self.illuminance = 0.0
        self.variance = 0.0

    def __str__(self):
        return f"Illuminance(" + ", ".join([
            f"header={self.header}"
            f"illuminance={self.illuminance}"
            f"variance={self.variance}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'header'
        field_val = self.header
        if isinstance(field_val, bytearray):
            d['header'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['header'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['header'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['header'] = field_val
        # handle field 'illuminance'
        field_val = self.illuminance
        if isinstance(field_val, bytearray):
            d['illuminance'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['illuminance'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['illuminance'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['illuminance'] = field_val
        # handle field 'variance'
        field_val = self.variance
        if isinstance(field_val, bytearray):
            d['variance'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['variance'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['variance'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['variance'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'header'
        if 'header' in d:
            field_type = cls.__annotations__.get('header')
            value = d['header']
            
            if field_type is bytearray:
                obj.header = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.header = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.header = value
            elif hasattr(field_type, 'from_dict'):
                obj.header = field_type.from_dict(value)
            else:
                obj.header = value
        # handle field 'illuminance'
        if 'illuminance' in d:
            field_type = cls.__annotations__.get('illuminance')
            value = d['illuminance']
            
            if field_type is bytearray:
                obj.illuminance = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.illuminance = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.illuminance = value
            elif hasattr(field_type, 'from_dict'):
                obj.illuminance = field_type.from_dict(value)
            else:
                obj.illuminance = value
        # handle field 'variance'
        if 'variance' in d:
            field_type = cls.__annotations__.get('variance')
            value = d['variance']
            
            if field_type is bytearray:
                obj.variance = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.variance = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.variance = value
            elif hasattr(field_type, 'from_dict'):
                obj.variance = field_type.from_dict(value)
            else:
                obj.variance = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
