from typing import List

# dependencies for the generated Python class
from ..std_msgs.pdu_pytype_Header import Header
from ..builtin_interfaces.pdu_pytype_Time import Time


# class definition for the ROS message
class Joy:
    """
    ROS message: sensor_msgs/Joy
    Generated by hakoniwa-ros2pdu.
    """

    header: Header
    axes: List[float]
    buttons: List[int]

    def __init__(self):
        self.header = Header()
        self.axes = []
        self.buttons = []

    def __str__(self):
        return f"Joy(" + ", ".join([
            f"header={self.header}"
            f"axes={self.axes}"
            f"buttons={self.buttons}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'header'
        field_val = self.header
        if isinstance(field_val, bytearray):
            d['header'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['header'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['header'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['header'] = field_val
        # handle field 'axes'
        field_val = self.axes
        if isinstance(field_val, bytearray):
            d['axes'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['axes'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['axes'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['axes'] = field_val
        # handle field 'buttons'
        field_val = self.buttons
        if isinstance(field_val, bytearray):
            d['buttons'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['buttons'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['buttons'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['buttons'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'header'
        if 'header' in d:
            field_type = cls.__annotations__.get('header')
            value = d['header']
            
            if field_type is bytearray:
                obj.header = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.header = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.header = value
            elif hasattr(field_type, 'from_dict'):
                obj.header = field_type.from_dict(value)
            else:
                obj.header = value
        # handle field 'axes'
        if 'axes' in d:
            field_type = cls.__annotations__.get('axes')
            value = d['axes']
            
            if field_type is bytearray:
                obj.axes = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.axes = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.axes = value
            elif hasattr(field_type, 'from_dict'):
                obj.axes = field_type.from_dict(value)
            else:
                obj.axes = value
        # handle field 'buttons'
        if 'buttons' in d:
            field_type = cls.__annotations__.get('buttons')
            value = d['buttons']
            
            if field_type is bytearray:
                obj.buttons = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.buttons = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.buttons = value
            elif hasattr(field_type, 'from_dict'):
                obj.buttons = field_type.from_dict(value)
            else:
                obj.buttons = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
