from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class TF2Error:
    """
    ROS message: tf2_msgs/TF2Error
    Generated by hakoniwa-ros2pdu.
    """

    error: int
    error_string: str

    def __init__(self):
        self.error = 0
        self.error_string = ""

    def __str__(self):
        return f"TF2Error(" + ", ".join([
            f"error={self.error}"
            f"error_string={self.error_string}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'error'
        field_val = self.error
        if isinstance(field_val, bytearray):
            d['error'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['error'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['error'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['error'] = field_val
        # handle field 'error_string'
        field_val = self.error_string
        if isinstance(field_val, bytearray):
            d['error_string'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['error_string'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['error_string'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['error_string'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'error'
        if 'error' in d:
            field_type = cls.__annotations__.get('error')
            value = d['error']
            
            if field_type is bytearray:
                obj.error = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.error = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.error = value
            elif hasattr(field_type, 'from_dict'):
                obj.error = field_type.from_dict(value)
            else:
                obj.error = value
        # handle field 'error_string'
        if 'error_string' in d:
            field_type = cls.__annotations__.get('error_string')
            value = d['error_string']
            
            if field_type is bytearray:
                obj.error_string = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.error_string = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.error_string = value
            elif hasattr(field_type, 'from_dict'):
                obj.error_string = field_type.from_dict(value)
            else:
                obj.error_string = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
