

/**
 * ROS message: tf2_msgs/TF2Error
 * Generated by hakoniwa-ros2pdu.
 */
export class TF2Error {
/** @type { number } */
    error;
/** @type { string } */
    error_string;


    constructor() {
        this.error = 0;
        this.error_string = "";
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'error'
            const field_val = this.error;
            if (typeof field_val?.toDict === 'function') {
                d['error'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['error'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['error'] = field_val;
            }
        }
        {
            // handle field 'error_string'
            const field_val = this.error_string;
            if (typeof field_val?.toDict === 'function') {
                d['error_string'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['error_string'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['error_string'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { TF2Error }
     */
    static fromDict(d) {
        const obj = new TF2Error();
        if (d.hasOwnProperty('error')) {
            obj.error = d.error;
        }
        if (d.hasOwnProperty('error_string')) {
            obj.error_string = d.error_string;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { TF2Error }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
