require_relative '../std_msgs/pdu_type_Header'
require_relative '../builtin_interfaces/pdu_type_Time'
require_relative '../geometry_msgs/pdu_type_Vector3'
require 'json'

module HakoPdu
  module GeometryMsgs
    # ROS message: geometry_msgs/Vector3Stamped
    # Generated by hakoniwa-ros2pdu.
    class Vector3Stamped
      attr_accessor :header, :vector

      def initialize(header: HakoPdu::StdMsgs::Header.new, vector: HakoPdu::GeometryMsgs::Vector3.new)

        @header = header

        @vector = vector

      end

      def to_h
        {

          'header' => self.class.encode_value(@header),

          'vector' => self.class.encode_value(@vector)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          header: decode_header(hash.fetch('header', HakoPdu::StdMsgs::Header.new)),

          vector: decode_vector(hash.fetch('vector', HakoPdu::GeometryMsgs::Vector3.new))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_header(value)
        value.is_a?(Hash) ? HakoPdu::StdMsgs::Header.from_h(value) : value
      end


      def self.decode_vector(value)
        value.is_a?(Hash) ? HakoPdu::GeometryMsgs::Vector3.from_h(value) : value
      end

end
  end
end
