require_relative '../geometry_msgs/pdu_type_Accel'
require_relative '../std_msgs/pdu_type_Header'
require_relative '../builtin_interfaces/pdu_type_Time'
require_relative '../geometry_msgs/pdu_type_Vector3'
require 'json'

module HakoPdu
  module GeometryMsgs
    # ROS message: geometry_msgs/AccelStamped
    # Generated by hakoniwa-ros2pdu.
    class AccelStamped
      attr_accessor :header, :accel

      def initialize(header: HakoPdu::StdMsgs::Header.new, accel: HakoPdu::GeometryMsgs::Accel.new)

        @header = header

        @accel = accel

      end

      def to_h
        {

          'header' => self.class.encode_value(@header),

          'accel' => self.class.encode_value(@accel)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          header: decode_header(hash.fetch('header', HakoPdu::StdMsgs::Header.new)),

          accel: decode_accel(hash.fetch('accel', HakoPdu::GeometryMsgs::Accel.new))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_header(value)
        value.is_a?(Hash) ? HakoPdu::StdMsgs::Header.from_h(value) : value
      end


      def self.decode_accel(value)
        value.is_a?(Hash) ? HakoPdu::GeometryMsgs::Accel.from_h(value) : value
      end

end
  end
end
