require_relative '../std_msgs/pdu_type_Header'
require_relative '../geometry_msgs/pdu_type_Quaternion'
require_relative '../builtin_interfaces/pdu_type_Time'
require 'json'

module HakoPdu
  module GeometryMsgs
    # ROS message: geometry_msgs/QuaternionStamped
    # Generated by hakoniwa-ros2pdu.
    class QuaternionStamped
      attr_accessor :header, :quaternion

      def initialize(header: HakoPdu::StdMsgs::Header.new, quaternion: HakoPdu::GeometryMsgs::Quaternion.new)

        @header = header

        @quaternion = quaternion

      end

      def to_h
        {

          'header' => self.class.encode_value(@header),

          'quaternion' => self.class.encode_value(@quaternion)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          header: decode_header(hash.fetch('header', HakoPdu::StdMsgs::Header.new)),

          quaternion: decode_quaternion(hash.fetch('quaternion', HakoPdu::GeometryMsgs::Quaternion.new))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_header(value)
        value.is_a?(Hash) ? HakoPdu::StdMsgs::Header.from_h(value) : value
      end


      def self.decode_quaternion(value)
        value.is_a?(Hash) ? HakoPdu::GeometryMsgs::Quaternion.from_h(value) : value
      end

end
  end
end
