require 'json'

module HakoPdu
  module GeometryMsgs
    # ROS message: geometry_msgs/Pose2D
    # Generated by hakoniwa-ros2pdu.
    class Pose2D
      attr_accessor :x, :y, :theta

      def initialize(x: 0.0, y: 0.0, theta: 0.0)

        @x = x

        @y = y

        @theta = theta

      end

      def to_h
        {

          'x' => self.class.encode_value(@x),

          'y' => self.class.encode_value(@y),

          'theta' => self.class.encode_value(@theta)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          x: decode_x(hash.fetch('x', 0.0)),

          y: decode_y(hash.fetch('y', 0.0)),

          theta: decode_theta(hash.fetch('theta', 0.0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_x(value)
        value
      end


      def self.decode_y(value)
        value
      end


      def self.decode_theta(value)
        value
      end

end
  end
end
