require_relative '../std_msgs/pdu_type_Header'
require_relative '../geometry_msgs/pdu_type_Quaternion'
require_relative '../builtin_interfaces/pdu_type_Time'
require_relative '../geometry_msgs/pdu_type_Transform'
require_relative '../geometry_msgs/pdu_type_Vector3'
require 'json'

module HakoPdu
  module GeometryMsgs
    # ROS message: geometry_msgs/TransformStamped
    # Generated by hakoniwa-ros2pdu.
    class TransformStamped
      attr_accessor :header, :child_frame_id, :transform

      def initialize(header: HakoPdu::StdMsgs::Header.new, child_frame_id: "", transform: HakoPdu::GeometryMsgs::Transform.new)

        @header = header

        @child_frame_id = child_frame_id

        @transform = transform

      end

      def to_h
        {

          'header' => self.class.encode_value(@header),

          'child_frame_id' => self.class.encode_value(@child_frame_id),

          'transform' => self.class.encode_value(@transform)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          header: decode_header(hash.fetch('header', HakoPdu::StdMsgs::Header.new)),

          child_frame_id: decode_child_frame_id(hash.fetch('child_frame_id', "")),

          transform: decode_transform(hash.fetch('transform', HakoPdu::GeometryMsgs::Transform.new))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_header(value)
        value.is_a?(Hash) ? HakoPdu::StdMsgs::Header.from_h(value) : value
      end


      def self.decode_child_frame_id(value)
        value
      end


      def self.decode_transform(value)
        value.is_a?(Hash) ? HakoPdu::GeometryMsgs::Transform.from_h(value) : value
      end

end
  end
end
