require 'json'

module HakoPdu
  module GeometryMsgs
    # ROS message: geometry_msgs/Quaternion
    # Generated by hakoniwa-ros2pdu.
    class Quaternion
      attr_accessor :x, :y, :z, :w

      def initialize(x: 0.0, y: 0.0, z: 0.0, w: 0.0)

        @x = x

        @y = y

        @z = z

        @w = w

      end

      def to_h
        {

          'x' => self.class.encode_value(@x),

          'y' => self.class.encode_value(@y),

          'z' => self.class.encode_value(@z),

          'w' => self.class.encode_value(@w)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          x: decode_x(hash.fetch('x', 0.0)),

          y: decode_y(hash.fetch('y', 0.0)),

          z: decode_z(hash.fetch('z', 0.0)),

          w: decode_w(hash.fetch('w', 0.0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_x(value)
        value
      end


      def self.decode_y(value)
        value
      end


      def self.decode_z(value)
        value
      end


      def self.decode_w(value)
        value
      end

end
  end
end
