require_relative '../geometry_msgs/pdu_type_Vector3'
require 'json'

module HakoPdu
  module GeometryMsgs
    # ROS message: geometry_msgs/Inertia
    # Generated by hakoniwa-ros2pdu.
    class Inertia
      attr_accessor :m, :com, :ixx, :ixy, :ixz, :iyy, :iyz, :izz

      def initialize(m: 0.0, com: HakoPdu::GeometryMsgs::Vector3.new, ixx: 0.0, ixy: 0.0, ixz: 0.0, iyy: 0.0, iyz: 0.0, izz: 0.0)

        @m = m

        @com = com

        @ixx = ixx

        @ixy = ixy

        @ixz = ixz

        @iyy = iyy

        @iyz = iyz

        @izz = izz

      end

      def to_h
        {

          'm' => self.class.encode_value(@m),

          'com' => self.class.encode_value(@com),

          'ixx' => self.class.encode_value(@ixx),

          'ixy' => self.class.encode_value(@ixy),

          'ixz' => self.class.encode_value(@ixz),

          'iyy' => self.class.encode_value(@iyy),

          'iyz' => self.class.encode_value(@iyz),

          'izz' => self.class.encode_value(@izz)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          m: decode_m(hash.fetch('m', 0.0)),

          com: decode_com(hash.fetch('com', HakoPdu::GeometryMsgs::Vector3.new)),

          ixx: decode_ixx(hash.fetch('ixx', 0.0)),

          ixy: decode_ixy(hash.fetch('ixy', 0.0)),

          ixz: decode_ixz(hash.fetch('ixz', 0.0)),

          iyy: decode_iyy(hash.fetch('iyy', 0.0)),

          iyz: decode_iyz(hash.fetch('iyz', 0.0)),

          izz: decode_izz(hash.fetch('izz', 0.0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_m(value)
        value
      end


      def self.decode_com(value)
        value.is_a?(Hash) ? HakoPdu::GeometryMsgs::Vector3.from_h(value) : value
      end


      def self.decode_ixx(value)
        value
      end


      def self.decode_ixy(value)
        value
      end


      def self.decode_ixz(value)
        value
      end


      def self.decode_iyy(value)
        value
      end


      def self.decode_iyz(value)
        value
      end


      def self.decode_izz(value)
        value
      end

end
  end
end
