require_relative '../geometry_msgs/pdu_type_Vector3'
require 'json'

module HakoPdu
  module GeometryMsgs
    # ROS message: geometry_msgs/Wrench
    # Generated by hakoniwa-ros2pdu.
    class Wrench
      attr_accessor :force, :torque

      def initialize(force: HakoPdu::GeometryMsgs::Vector3.new, torque: HakoPdu::GeometryMsgs::Vector3.new)

        @force = force

        @torque = torque

      end

      def to_h
        {

          'force' => self.class.encode_value(@force),

          'torque' => self.class.encode_value(@torque)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          force: decode_force(hash.fetch('force', HakoPdu::GeometryMsgs::Vector3.new)),

          torque: decode_torque(hash.fetch('torque', HakoPdu::GeometryMsgs::Vector3.new))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_force(value)
        value.is_a?(Hash) ? HakoPdu::GeometryMsgs::Vector3.from_h(value) : value
      end


      def self.decode_torque(value)
        value.is_a?(Hash) ? HakoPdu::GeometryMsgs::Vector3.from_h(value) : value
      end

end
  end
end
