require_relative '../std_msgs/pdu_type_Header'
require_relative '../geometry_msgs/pdu_type_Point'
require_relative '../geometry_msgs/pdu_type_Pose'
require_relative '../geometry_msgs/pdu_type_Quaternion'
require_relative '../builtin_interfaces/pdu_type_Time'
require 'json'

module HakoPdu
  module GeometryMsgs
    # ROS message: geometry_msgs/PoseArray
    # Generated by hakoniwa-ros2pdu.
    class PoseArray
      attr_accessor :header, :poses

      def initialize(header: HakoPdu::StdMsgs::Header.new, poses: [])

        @header = header

        @poses = poses

      end

      def to_h
        {

          'header' => self.class.encode_value(@header),

          'poses' => self.class.encode_value(@poses)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          header: decode_header(hash.fetch('header', HakoPdu::StdMsgs::Header.new)),

          poses: decode_poses(hash.fetch('poses', []))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_header(value)
        value.is_a?(Hash) ? HakoPdu::StdMsgs::Header.from_h(value) : value
      end


      def self.decode_poses(value)
        return [] if value.nil?
        value.map { |item| HakoPdu::GeometryMsgs::Pose.from_h(item) }
      end

end
  end
end
