defmodule HakoPdu.AckermannMsgs.AckermannDrive do
  @moduledoc """
  ROS message: ackermann_msgs/AckermannDrive

  Generated by hakoniwa-ros2pdu.
  """

  defstruct [

    steering_angle: 0.0,

    steering_angle_velocity: 0.0,

    speed: 0.0,

    acceleration: 0.0,

    jerk: 0.0

  ]

  def new(attrs \\ %{}) when is_map(attrs) do
    struct(__MODULE__, attrs)
  end

  def to_map(%__MODULE__{} = msg) do
    %{

      "steering_angle" => encode_value(msg.steering_angle),

      "steering_angle_velocity" => encode_value(msg.steering_angle_velocity),

      "speed" => encode_value(msg.speed),

      "acceleration" => encode_value(msg.acceleration),

      "jerk" => encode_value(msg.jerk)

    }
  end

  def from_map(map) when is_map(map) do
    %__MODULE__{

      steering_angle: map |> get_value(:steering_angle, "steering_angle", 0.0) |> decode_steering_angle(),

      steering_angle_velocity: map |> get_value(:steering_angle_velocity, "steering_angle_velocity", 0.0) |> decode_steering_angle_velocity(),

      speed: map |> get_value(:speed, "speed", 0.0) |> decode_speed(),

      acceleration: map |> get_value(:acceleration, "acceleration", 0.0) |> decode_acceleration(),

      jerk: map |> get_value(:jerk, "jerk", 0.0) |> decode_jerk()

    }
  end

  def to_json(%__MODULE__{} = msg) do
    msg
    |> to_map()
    |> json_encode()
  end

  def from_json(json) when is_binary(json) do
    json
    |> json_decode()
    |> from_map()
  end

  defp get_value(map, atom_key, string_key, default) do
    Map.get(map, atom_key, Map.get(map, string_key, default))
  end

  defp encode_value(values) when is_list(values), do: Enum.map(values, &encode_value/1)
  defp encode_value(%{__struct__: module} = value) do
    if function_exported?(module, :to_map, 1), do: module.to_map(value), else: value
  end
  defp encode_value(value), do: value

  defp json_encode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :encode!, 1) -> apply(Jason, :encode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :encode!, 1) -> apply(JSON, :encode!, [value])
      true -> raise "No JSON encoder found. Add Jason or JSON to use to_json/1."
    end
  end

  defp json_decode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :decode!, 1) -> apply(Jason, :decode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :decode!, 1) -> apply(JSON, :decode!, [value])
      true -> raise "No JSON decoder found. Add Jason or JSON to use from_json/1."
    end
  end


  defp decode_steering_angle(value) do
    value
  end


  defp decode_steering_angle_velocity(value) do
    value
  end


  defp decode_speed(value) do
    value
  end


  defp decode_acceleration(value) do
    value
  end


  defp decode_jerk(value) do
    value
  end

end
