require 'json'

module HakoPdu
  module AckermannMsgs
    # ROS message: ackermann_msgs/AckermannDrive
    # Generated by hakoniwa-ros2pdu.
    class AckermannDrive
      attr_accessor :steering_angle, :steering_angle_velocity, :speed, :acceleration, :jerk

      def initialize(steering_angle: 0.0, steering_angle_velocity: 0.0, speed: 0.0, acceleration: 0.0, jerk: 0.0)

        @steering_angle = steering_angle

        @steering_angle_velocity = steering_angle_velocity

        @speed = speed

        @acceleration = acceleration

        @jerk = jerk

      end

      def to_h
        {

          'steering_angle' => self.class.encode_value(@steering_angle),

          'steering_angle_velocity' => self.class.encode_value(@steering_angle_velocity),

          'speed' => self.class.encode_value(@speed),

          'acceleration' => self.class.encode_value(@acceleration),

          'jerk' => self.class.encode_value(@jerk)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          steering_angle: decode_steering_angle(hash.fetch('steering_angle', 0.0)),

          steering_angle_velocity: decode_steering_angle_velocity(hash.fetch('steering_angle_velocity', 0.0)),

          speed: decode_speed(hash.fetch('speed', 0.0)),

          acceleration: decode_acceleration(hash.fetch('acceleration', 0.0)),

          jerk: decode_jerk(hash.fetch('jerk', 0.0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_steering_angle(value)
        value
      end


      def self.decode_steering_angle_velocity(value)
        value
      end


      def self.decode_speed(value)
        value
      end


      def self.decode_acceleration(value)
        value
      end


      def self.decode_jerk(value)
        value
      end

end
  end
end
