import { Point } from '../geometry_msgs/pdu_jstype_Point.js';
import { Time } from '../builtin_interfaces/pdu_jstype_Time.js';


/**
 * ROS message: hako_msgs/ContactEvent
 * Generated by hakoniwa-ros2pdu.
 */
export class ContactEvent {
/** @type { Time } */
    stamp;
/** @type { string } */
    self_name;
/** @type { string } */
    other_name;
/** @type { string } */
    other_kind;
/** @type { Point } */
    position;
/** @type { number } */
    relative_speed;
/** @type { boolean } */
    started;


    constructor() {
        this.stamp = new Time();
        this.self_name = "";
        this.other_name = "";
        this.other_kind = "";
        this.position = new Point();
        this.relative_speed = 0.0;
        this.started = false;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'stamp'
            const field_val = this.stamp;
            if (typeof field_val?.toDict === 'function') {
                d['stamp'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['stamp'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['stamp'] = field_val.toString();
            } else {
                d['stamp'] = field_val;
            }
        }
        {
            // handle field 'self_name'
            const field_val = this.self_name;
            if (typeof field_val?.toDict === 'function') {
                d['self_name'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['self_name'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['self_name'] = field_val.toString();
            } else {
                d['self_name'] = field_val;
            }
        }
        {
            // handle field 'other_name'
            const field_val = this.other_name;
            if (typeof field_val?.toDict === 'function') {
                d['other_name'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['other_name'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['other_name'] = field_val.toString();
            } else {
                d['other_name'] = field_val;
            }
        }
        {
            // handle field 'other_kind'
            const field_val = this.other_kind;
            if (typeof field_val?.toDict === 'function') {
                d['other_kind'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['other_kind'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['other_kind'] = field_val.toString();
            } else {
                d['other_kind'] = field_val;
            }
        }
        {
            // handle field 'position'
            const field_val = this.position;
            if (typeof field_val?.toDict === 'function') {
                d['position'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['position'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['position'] = field_val.toString();
            } else {
                d['position'] = field_val;
            }
        }
        {
            // handle field 'relative_speed'
            const field_val = this.relative_speed;
            if (typeof field_val?.toDict === 'function') {
                d['relative_speed'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['relative_speed'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['relative_speed'] = field_val.toString();
            } else {
                d['relative_speed'] = field_val;
            }
        }
        {
            // handle field 'started'
            const field_val = this.started;
            if (typeof field_val?.toDict === 'function') {
                d['started'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['started'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['started'] = field_val.toString();
            } else {
                d['started'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { ContactEvent }
     */
    static fromDict(d) {
        const obj = new ContactEvent();
        if (d.hasOwnProperty('stamp')) {
            const field_class = Time;
            if (d.stamp) {
                obj.stamp = field_class.fromDict(d.stamp);
            }
        }
        if (d.hasOwnProperty('self_name')) {
            obj.self_name = d.self_name;
        }
        if (d.hasOwnProperty('other_name')) {
            obj.other_name = d.other_name;
        }
        if (d.hasOwnProperty('other_kind')) {
            obj.other_kind = d.other_kind;
        }
        if (d.hasOwnProperty('position')) {
            const field_class = Point;
            if (d.position) {
                obj.position = field_class.fromDict(d.position);
            }
        }
        if (d.hasOwnProperty('relative_speed')) {
            obj.relative_speed = d.relative_speed;
        }
        if (d.hasOwnProperty('started')) {
            obj.started = d.started;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { ContactEvent }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
