

/**
 * ROS message: hako_msgs/ExecutionUnitRuntimeEpoch
 * Generated by hakoniwa-ros2pdu.
 */
export class ExecutionUnitRuntimeEpoch {
/** @type { Array<number> } */
    epoch;


    constructor() {
        this.epoch = [];
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'epoch'
            const field_val = this.epoch;
            if (typeof field_val?.toDict === 'function') {
                d['epoch'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['epoch'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['epoch'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { ExecutionUnitRuntimeEpoch }
     */
    static fromDict(d) {
        const obj = new ExecutionUnitRuntimeEpoch();
        if (d.hasOwnProperty('epoch')) {
            const item_class = uint8;
            if (Array.isArray(d.epoch)) {
                obj.epoch = d.epoch.map(item => item_class.fromDict(item));
            }
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { ExecutionUnitRuntimeEpoch }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
