import { ContactEvent } from '../hako_msgs/pdu_jstype_ContactEvent.js';
import { Point } from '../geometry_msgs/pdu_jstype_Point.js';
import { Time } from '../builtin_interfaces/pdu_jstype_Time.js';


/**
 * ROS message: hako_msgs/ContactEventArray
 * Generated by hakoniwa-ros2pdu.
 */
export class ContactEventArray {
/** @type { Array<ContactEvent> } */
    events;


    constructor() {
        this.events = [];
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'events'
            const field_val = this.events;
            if (typeof field_val?.toDict === 'function') {
                d['events'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['events'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['events'] = field_val.toString();
            } else {
                d['events'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { ContactEventArray }
     */
    static fromDict(d) {
        const obj = new ContactEventArray();
        if (d.hasOwnProperty('events')) {
            const item_class = ContactEvent;
            if (Array.isArray(d.events)) {
                obj.events = d.events.map(item => item_class.fromDict(item));
            }
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { ContactEventArray }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
