require 'json'

module HakoPdu
  module StdMsgs
    # ROS message: std_msgs/Empty
    # Generated by hakoniwa-ros2pdu.
    class Empty
      attr_accessor :hako_dummy

      def initialize(hako_dummy: 0)

        @hako_dummy = hako_dummy

      end

      def to_h
        {

          'hako_dummy' => self.class.encode_value(@hako_dummy)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          hako_dummy: decode_hako_dummy(hash.fetch('hako_dummy', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_hako_dummy(value)
        value
      end

end
  end
end
