require 'json'

module HakoPdu
  module StdMsgs
    # ROS message: std_msgs/ColorRGBA
    # Generated by hakoniwa-ros2pdu.
    class ColorRGBA
      attr_accessor :r, :g, :b, :a

      def initialize(r: 0.0, g: 0.0, b: 0.0, a: 0.0)

        @r = r

        @g = g

        @b = b

        @a = a

      end

      def to_h
        {

          'r' => self.class.encode_value(@r),

          'g' => self.class.encode_value(@g),

          'b' => self.class.encode_value(@b),

          'a' => self.class.encode_value(@a)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          r: decode_r(hash.fetch('r', 0.0)),

          g: decode_g(hash.fetch('g', 0.0)),

          b: decode_b(hash.fetch('b', 0.0)),

          a: decode_a(hash.fetch('a', 0.0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_r(value)
        value
      end


      def self.decode_g(value)
        value
      end


      def self.decode_b(value)
        value
      end


      def self.decode_a(value)
        value
      end

end
  end
end
