require 'json'

module HakoPdu
  module StdMsgs
    # ROS message: std_msgs/MultiArrayDimension
    # Generated by hakoniwa-ros2pdu.
    class MultiArrayDimension
      attr_accessor :label, :size, :stride

      def initialize(label: "", size: 0, stride: 0)

        @label = label

        @size = size

        @stride = stride

      end

      def to_h
        {

          'label' => self.class.encode_value(@label),

          'size' => self.class.encode_value(@size),

          'stride' => self.class.encode_value(@stride)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          label: decode_label(hash.fetch('label', "")),

          size: decode_size(hash.fetch('size', 0)),

          stride: decode_stride(hash.fetch('stride', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_label(value)
        value
      end


      def self.decode_size(value)
        value
      end


      def self.decode_stride(value)
        value
      end

end
  end
end
