require_relative '../builtin_interfaces/pdu_type_Time'
require 'json'

module HakoPdu
  module StdMsgs
    # ROS message: std_msgs/Header
    # Generated by hakoniwa-ros2pdu.
    class Header
      attr_accessor :stamp, :frame_id

      def initialize(stamp: HakoPdu::BuiltinInterfaces::Time.new, frame_id: "")

        @stamp = stamp

        @frame_id = frame_id

      end

      def to_h
        {

          'stamp' => self.class.encode_value(@stamp),

          'frame_id' => self.class.encode_value(@frame_id)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          stamp: decode_stamp(hash.fetch('stamp', HakoPdu::BuiltinInterfaces::Time.new)),

          frame_id: decode_frame_id(hash.fetch('frame_id', ""))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_stamp(value)
        value.is_a?(Hash) ? HakoPdu::BuiltinInterfaces::Time.from_h(value) : value
      end


      def self.decode_frame_id(value)
        value
      end

end
  end
end
