defmodule HakoPdu.SensorMsgs.Range do
  @moduledoc """
  ROS message: sensor_msgs/Range

  Generated by hakoniwa-ros2pdu.
  """

  defstruct [

    header: HakoPdu.StdMsgs.Header.new(),

    radiation_type: 0,

    field_of_view: 0.0,

    min_range: 0.0,

    max_range: 0.0,

    range: 0.0,

    variance: 0.0

  ]

  def new(attrs \\ %{}) when is_map(attrs) do
    struct(__MODULE__, attrs)
  end

  def to_map(%__MODULE__{} = msg) do
    %{

      "header" => encode_value(msg.header),

      "radiation_type" => encode_value(msg.radiation_type),

      "field_of_view" => encode_value(msg.field_of_view),

      "min_range" => encode_value(msg.min_range),

      "max_range" => encode_value(msg.max_range),

      "range" => encode_value(msg.range),

      "variance" => encode_value(msg.variance)

    }
  end

  def from_map(map) when is_map(map) do
    %__MODULE__{

      header: map |> get_value(:header, "header", HakoPdu.StdMsgs.Header.new()) |> decode_header(),

      radiation_type: map |> get_value(:radiation_type, "radiation_type", 0) |> decode_radiation_type(),

      field_of_view: map |> get_value(:field_of_view, "field_of_view", 0.0) |> decode_field_of_view(),

      min_range: map |> get_value(:min_range, "min_range", 0.0) |> decode_min_range(),

      max_range: map |> get_value(:max_range, "max_range", 0.0) |> decode_max_range(),

      range: map |> get_value(:range, "range", 0.0) |> decode_range(),

      variance: map |> get_value(:variance, "variance", 0.0) |> decode_variance()

    }
  end

  def to_json(%__MODULE__{} = msg) do
    msg
    |> to_map()
    |> json_encode()
  end

  def from_json(json) when is_binary(json) do
    json
    |> json_decode()
    |> from_map()
  end

  defp get_value(map, atom_key, string_key, default) do
    Map.get(map, atom_key, Map.get(map, string_key, default))
  end

  defp encode_value(values) when is_list(values), do: Enum.map(values, &encode_value/1)
  defp encode_value(%{__struct__: module} = value) do
    if function_exported?(module, :to_map, 1), do: module.to_map(value), else: value
  end
  defp encode_value(value), do: value

  defp json_encode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :encode!, 1) -> apply(Jason, :encode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :encode!, 1) -> apply(JSON, :encode!, [value])
      true -> raise "No JSON encoder found. Add Jason or JSON to use to_json/1."
    end
  end

  defp json_decode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :decode!, 1) -> apply(Jason, :decode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :decode!, 1) -> apply(JSON, :decode!, [value])
      true -> raise "No JSON decoder found. Add Jason or JSON to use from_json/1."
    end
  end


  defp decode_header(value) do
    if is_map(value), do: HakoPdu.StdMsgs.Header.from_map(value), else: value
  end


  defp decode_radiation_type(value) do
    value
  end


  defp decode_field_of_view(value) do
    value
  end


  defp decode_min_range(value) do
    value
  end


  defp decode_max_range(value) do
    value
  end


  defp decode_range(value) do
    value
  end


  defp decode_variance(value) do
    value
  end

end
