defmodule HakoPdu.SensorMsgs.Imu do
  @moduledoc """
  ROS message: sensor_msgs/Imu

  Generated by hakoniwa-ros2pdu.
  """

  defstruct [

    header: HakoPdu.StdMsgs.Header.new(),

    orientation: HakoPdu.GeometryMsgs.Quaternion.new(),

    orientation_covariance: [],

    angular_velocity: HakoPdu.GeometryMsgs.Vector3.new(),

    angular_velocity_covariance: [],

    linear_acceleration: HakoPdu.GeometryMsgs.Vector3.new(),

    linear_acceleration_covariance: []

  ]

  def new(attrs \\ %{}) when is_map(attrs) do
    struct(__MODULE__, attrs)
  end

  def to_map(%__MODULE__{} = msg) do
    %{

      "header" => encode_value(msg.header),

      "orientation" => encode_value(msg.orientation),

      "orientation_covariance" => encode_value(msg.orientation_covariance),

      "angular_velocity" => encode_value(msg.angular_velocity),

      "angular_velocity_covariance" => encode_value(msg.angular_velocity_covariance),

      "linear_acceleration" => encode_value(msg.linear_acceleration),

      "linear_acceleration_covariance" => encode_value(msg.linear_acceleration_covariance)

    }
  end

  def from_map(map) when is_map(map) do
    %__MODULE__{

      header: map |> get_value(:header, "header", HakoPdu.StdMsgs.Header.new()) |> decode_header(),

      orientation: map |> get_value(:orientation, "orientation", HakoPdu.GeometryMsgs.Quaternion.new()) |> decode_orientation(),

      orientation_covariance: map |> get_value(:orientation_covariance, "orientation_covariance", []) |> decode_orientation_covariance(),

      angular_velocity: map |> get_value(:angular_velocity, "angular_velocity", HakoPdu.GeometryMsgs.Vector3.new()) |> decode_angular_velocity(),

      angular_velocity_covariance: map |> get_value(:angular_velocity_covariance, "angular_velocity_covariance", []) |> decode_angular_velocity_covariance(),

      linear_acceleration: map |> get_value(:linear_acceleration, "linear_acceleration", HakoPdu.GeometryMsgs.Vector3.new()) |> decode_linear_acceleration(),

      linear_acceleration_covariance: map |> get_value(:linear_acceleration_covariance, "linear_acceleration_covariance", []) |> decode_linear_acceleration_covariance()

    }
  end

  def to_json(%__MODULE__{} = msg) do
    msg
    |> to_map()
    |> json_encode()
  end

  def from_json(json) when is_binary(json) do
    json
    |> json_decode()
    |> from_map()
  end

  defp get_value(map, atom_key, string_key, default) do
    Map.get(map, atom_key, Map.get(map, string_key, default))
  end

  defp encode_value(values) when is_list(values), do: Enum.map(values, &encode_value/1)
  defp encode_value(%{__struct__: module} = value) do
    if function_exported?(module, :to_map, 1), do: module.to_map(value), else: value
  end
  defp encode_value(value), do: value

  defp json_encode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :encode!, 1) -> apply(Jason, :encode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :encode!, 1) -> apply(JSON, :encode!, [value])
      true -> raise "No JSON encoder found. Add Jason or JSON to use to_json/1."
    end
  end

  defp json_decode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :decode!, 1) -> apply(Jason, :decode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :decode!, 1) -> apply(JSON, :decode!, [value])
      true -> raise "No JSON decoder found. Add Jason or JSON to use from_json/1."
    end
  end


  defp decode_header(value) do
    if is_map(value), do: HakoPdu.StdMsgs.Header.from_map(value), else: value
  end


  defp decode_orientation(value) do
    if is_map(value), do: HakoPdu.GeometryMsgs.Quaternion.from_map(value), else: value
  end


  defp decode_orientation_covariance(value) do
    value
  end


  defp decode_angular_velocity(value) do
    if is_map(value), do: HakoPdu.GeometryMsgs.Vector3.from_map(value), else: value
  end


  defp decode_angular_velocity_covariance(value) do
    value
  end


  defp decode_linear_acceleration(value) do
    if is_map(value), do: HakoPdu.GeometryMsgs.Vector3.from_map(value), else: value
  end


  defp decode_linear_acceleration_covariance(value) do
    value
  end

end
