defmodule HakoPdu.SensorMsgs.CameraInfo do
  @moduledoc """
  ROS message: sensor_msgs/CameraInfo

  Generated by hakoniwa-ros2pdu.
  """

  defstruct [

    header: HakoPdu.StdMsgs.Header.new(),

    height: 0,

    width: 0,

    distortion_model: "",

    d: [],

    k: [],

    r: [],

    p: [],

    binning_x: 0,

    binning_y: 0,

    roi: HakoPdu.SensorMsgs.RegionOfInterest.new()

  ]

  def new(attrs \\ %{}) when is_map(attrs) do
    struct(__MODULE__, attrs)
  end

  def to_map(%__MODULE__{} = msg) do
    %{

      "header" => encode_value(msg.header),

      "height" => encode_value(msg.height),

      "width" => encode_value(msg.width),

      "distortion_model" => encode_value(msg.distortion_model),

      "d" => encode_value(msg.d),

      "k" => encode_value(msg.k),

      "r" => encode_value(msg.r),

      "p" => encode_value(msg.p),

      "binning_x" => encode_value(msg.binning_x),

      "binning_y" => encode_value(msg.binning_y),

      "roi" => encode_value(msg.roi)

    }
  end

  def from_map(map) when is_map(map) do
    %__MODULE__{

      header: map |> get_value(:header, "header", HakoPdu.StdMsgs.Header.new()) |> decode_header(),

      height: map |> get_value(:height, "height", 0) |> decode_height(),

      width: map |> get_value(:width, "width", 0) |> decode_width(),

      distortion_model: map |> get_value(:distortion_model, "distortion_model", "") |> decode_distortion_model(),

      d: map |> get_value(:d, "d", []) |> decode_d(),

      k: map |> get_value(:k, "k", []) |> decode_k(),

      r: map |> get_value(:r, "r", []) |> decode_r(),

      p: map |> get_value(:p, "p", []) |> decode_p(),

      binning_x: map |> get_value(:binning_x, "binning_x", 0) |> decode_binning_x(),

      binning_y: map |> get_value(:binning_y, "binning_y", 0) |> decode_binning_y(),

      roi: map |> get_value(:roi, "roi", HakoPdu.SensorMsgs.RegionOfInterest.new()) |> decode_roi()

    }
  end

  def to_json(%__MODULE__{} = msg) do
    msg
    |> to_map()
    |> json_encode()
  end

  def from_json(json) when is_binary(json) do
    json
    |> json_decode()
    |> from_map()
  end

  defp get_value(map, atom_key, string_key, default) do
    Map.get(map, atom_key, Map.get(map, string_key, default))
  end

  defp encode_value(values) when is_list(values), do: Enum.map(values, &encode_value/1)
  defp encode_value(%{__struct__: module} = value) do
    if function_exported?(module, :to_map, 1), do: module.to_map(value), else: value
  end
  defp encode_value(value), do: value

  defp json_encode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :encode!, 1) -> apply(Jason, :encode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :encode!, 1) -> apply(JSON, :encode!, [value])
      true -> raise "No JSON encoder found. Add Jason or JSON to use to_json/1."
    end
  end

  defp json_decode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :decode!, 1) -> apply(Jason, :decode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :decode!, 1) -> apply(JSON, :decode!, [value])
      true -> raise "No JSON decoder found. Add Jason or JSON to use from_json/1."
    end
  end


  defp decode_header(value) do
    if is_map(value), do: HakoPdu.StdMsgs.Header.from_map(value), else: value
  end


  defp decode_height(value) do
    value
  end


  defp decode_width(value) do
    value
  end


  defp decode_distortion_model(value) do
    value
  end


  defp decode_d(value) do
    value
  end


  defp decode_k(value) do
    value
  end


  defp decode_r(value) do
    value
  end


  defp decode_p(value) do
    value
  end


  defp decode_binning_x(value) do
    value
  end


  defp decode_binning_y(value) do
    value
  end


  defp decode_roi(value) do
    if is_map(value), do: HakoPdu.SensorMsgs.RegionOfInterest.from_map(value), else: value
  end

end
