defmodule HakoPdu.MavrosMsgs.GlobalPositionTarget do
  @moduledoc """
  ROS message: mavros_msgs/GlobalPositionTarget

  Generated by hakoniwa-ros2pdu.
  """

  defstruct [

    header: HakoPdu.StdMsgs.Header.new(),

    coordinate_frame: 0,

    type_mask: 0,

    latitude: 0.0,

    longitude: 0.0,

    altitude: 0.0,

    velocity: HakoPdu.GeometryMsgs.Vector3.new(),

    acceleration_or_force: HakoPdu.GeometryMsgs.Vector3.new(),

    yaw: 0.0,

    yaw_rate: 0.0

  ]

  def new(attrs \\ %{}) when is_map(attrs) do
    struct(__MODULE__, attrs)
  end

  def to_map(%__MODULE__{} = msg) do
    %{

      "header" => encode_value(msg.header),

      "coordinate_frame" => encode_value(msg.coordinate_frame),

      "type_mask" => encode_value(msg.type_mask),

      "latitude" => encode_value(msg.latitude),

      "longitude" => encode_value(msg.longitude),

      "altitude" => encode_value(msg.altitude),

      "velocity" => encode_value(msg.velocity),

      "acceleration_or_force" => encode_value(msg.acceleration_or_force),

      "yaw" => encode_value(msg.yaw),

      "yaw_rate" => encode_value(msg.yaw_rate)

    }
  end

  def from_map(map) when is_map(map) do
    %__MODULE__{

      header: map |> get_value(:header, "header", HakoPdu.StdMsgs.Header.new()) |> decode_header(),

      coordinate_frame: map |> get_value(:coordinate_frame, "coordinate_frame", 0) |> decode_coordinate_frame(),

      type_mask: map |> get_value(:type_mask, "type_mask", 0) |> decode_type_mask(),

      latitude: map |> get_value(:latitude, "latitude", 0.0) |> decode_latitude(),

      longitude: map |> get_value(:longitude, "longitude", 0.0) |> decode_longitude(),

      altitude: map |> get_value(:altitude, "altitude", 0.0) |> decode_altitude(),

      velocity: map |> get_value(:velocity, "velocity", HakoPdu.GeometryMsgs.Vector3.new()) |> decode_velocity(),

      acceleration_or_force: map |> get_value(:acceleration_or_force, "acceleration_or_force", HakoPdu.GeometryMsgs.Vector3.new()) |> decode_acceleration_or_force(),

      yaw: map |> get_value(:yaw, "yaw", 0.0) |> decode_yaw(),

      yaw_rate: map |> get_value(:yaw_rate, "yaw_rate", 0.0) |> decode_yaw_rate()

    }
  end

  def to_json(%__MODULE__{} = msg) do
    msg
    |> to_map()
    |> json_encode()
  end

  def from_json(json) when is_binary(json) do
    json
    |> json_decode()
    |> from_map()
  end

  defp get_value(map, atom_key, string_key, default) do
    Map.get(map, atom_key, Map.get(map, string_key, default))
  end

  defp encode_value(values) when is_list(values), do: Enum.map(values, &encode_value/1)
  defp encode_value(%{__struct__: module} = value) do
    if function_exported?(module, :to_map, 1), do: module.to_map(value), else: value
  end
  defp encode_value(value), do: value

  defp json_encode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :encode!, 1) -> apply(Jason, :encode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :encode!, 1) -> apply(JSON, :encode!, [value])
      true -> raise "No JSON encoder found. Add Jason or JSON to use to_json/1."
    end
  end

  defp json_decode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :decode!, 1) -> apply(Jason, :decode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :decode!, 1) -> apply(JSON, :decode!, [value])
      true -> raise "No JSON decoder found. Add Jason or JSON to use from_json/1."
    end
  end


  defp decode_header(value) do
    if is_map(value), do: HakoPdu.StdMsgs.Header.from_map(value), else: value
  end


  defp decode_coordinate_frame(value) do
    value
  end


  defp decode_type_mask(value) do
    value
  end


  defp decode_latitude(value) do
    value
  end


  defp decode_longitude(value) do
    value
  end


  defp decode_altitude(value) do
    value
  end


  defp decode_velocity(value) do
    if is_map(value), do: HakoPdu.GeometryMsgs.Vector3.from_map(value), else: value
  end


  defp decode_acceleration_or_force(value) do
    if is_map(value), do: HakoPdu.GeometryMsgs.Vector3.from_map(value), else: value
  end


  defp decode_yaw(value) do
    value
  end


  defp decode_yaw_rate(value) do
    value
  end

end
