from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class ActionResponseHeader:
    """
    ROS message: hako_action_msgs/ActionResponseHeader
    Generated by hakoniwa-ros2pdu.
    """

    version: int
    response_kind: int
    status: int
    reserved: int
    goal_id: List[int]

    def __init__(self):
        self.version = 0
        self.response_kind = 0
        self.status = 0
        self.reserved = 0
        self.goal_id = []

    def __str__(self):
        return f"ActionResponseHeader(" + ", ".join([
            f"version={self.version}"
            f"response_kind={self.response_kind}"
            f"status={self.status}"
            f"reserved={self.reserved}"
            f"goal_id={self.goal_id}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'version'
        field_val = self.version
        if isinstance(field_val, bytearray):
            d['version'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['version'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['version'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['version'] = field_val
        # handle field 'response_kind'
        field_val = self.response_kind
        if isinstance(field_val, bytearray):
            d['response_kind'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['response_kind'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['response_kind'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['response_kind'] = field_val
        # handle field 'status'
        field_val = self.status
        if isinstance(field_val, bytearray):
            d['status'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['status'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['status'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['status'] = field_val
        # handle field 'reserved'
        field_val = self.reserved
        if isinstance(field_val, bytearray):
            d['reserved'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['reserved'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['reserved'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['reserved'] = field_val
        # handle field 'goal_id'
        field_val = self.goal_id
        if isinstance(field_val, bytearray):
            d['goal_id'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['goal_id'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['goal_id'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['goal_id'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'version'
        if 'version' in d:
            field_type = cls.__annotations__.get('version')
            value = d['version']
            
            if field_type is bytearray:
                obj.version = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.version = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.version = value
            elif hasattr(field_type, 'from_dict'):
                obj.version = field_type.from_dict(value)
            else:
                obj.version = value
        # handle field 'response_kind'
        if 'response_kind' in d:
            field_type = cls.__annotations__.get('response_kind')
            value = d['response_kind']
            
            if field_type is bytearray:
                obj.response_kind = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.response_kind = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.response_kind = value
            elif hasattr(field_type, 'from_dict'):
                obj.response_kind = field_type.from_dict(value)
            else:
                obj.response_kind = value
        # handle field 'status'
        if 'status' in d:
            field_type = cls.__annotations__.get('status')
            value = d['status']
            
            if field_type is bytearray:
                obj.status = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.status = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.status = value
            elif hasattr(field_type, 'from_dict'):
                obj.status = field_type.from_dict(value)
            else:
                obj.status = value
        # handle field 'reserved'
        if 'reserved' in d:
            field_type = cls.__annotations__.get('reserved')
            value = d['reserved']
            
            if field_type is bytearray:
                obj.reserved = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.reserved = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.reserved = value
            elif hasattr(field_type, 'from_dict'):
                obj.reserved = field_type.from_dict(value)
            else:
                obj.reserved = value
        # handle field 'goal_id'
        if 'goal_id' in d:
            field_type = cls.__annotations__.get('goal_id')
            value = d['goal_id']
            
            if field_type is bytearray:
                obj.goal_id = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.goal_id = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.goal_id = value
            elif hasattr(field_type, 'from_dict'):
                obj.goal_id = field_type.from_dict(value)
            else:
                obj.goal_id = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
