from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class ActionFeedbackHeader:
    """
    ROS message: hako_action_msgs/ActionFeedbackHeader
    Generated by hakoniwa-ros2pdu.
    """

    version: int
    reserved: List[int]
    goal_id: List[int]
    sequence_no: int

    def __init__(self):
        self.version = 0
        self.reserved = []
        self.goal_id = []
        self.sequence_no = 0

    def __str__(self):
        return f"ActionFeedbackHeader(" + ", ".join([
            f"version={self.version}"
            f"reserved={self.reserved}"
            f"goal_id={self.goal_id}"
            f"sequence_no={self.sequence_no}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'version'
        field_val = self.version
        if isinstance(field_val, bytearray):
            d['version'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['version'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['version'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['version'] = field_val
        # handle field 'reserved'
        field_val = self.reserved
        if isinstance(field_val, bytearray):
            d['reserved'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['reserved'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['reserved'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['reserved'] = field_val
        # handle field 'goal_id'
        field_val = self.goal_id
        if isinstance(field_val, bytearray):
            d['goal_id'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['goal_id'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['goal_id'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['goal_id'] = field_val
        # handle field 'sequence_no'
        field_val = self.sequence_no
        if isinstance(field_val, bytearray):
            d['sequence_no'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['sequence_no'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['sequence_no'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['sequence_no'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'version'
        if 'version' in d:
            field_type = cls.__annotations__.get('version')
            value = d['version']
            
            if field_type is bytearray:
                obj.version = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.version = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.version = value
            elif hasattr(field_type, 'from_dict'):
                obj.version = field_type.from_dict(value)
            else:
                obj.version = value
        # handle field 'reserved'
        if 'reserved' in d:
            field_type = cls.__annotations__.get('reserved')
            value = d['reserved']
            
            if field_type is bytearray:
                obj.reserved = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.reserved = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.reserved = value
            elif hasattr(field_type, 'from_dict'):
                obj.reserved = field_type.from_dict(value)
            else:
                obj.reserved = value
        # handle field 'goal_id'
        if 'goal_id' in d:
            field_type = cls.__annotations__.get('goal_id')
            value = d['goal_id']
            
            if field_type is bytearray:
                obj.goal_id = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.goal_id = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.goal_id = value
            elif hasattr(field_type, 'from_dict'):
                obj.goal_id = field_type.from_dict(value)
            else:
                obj.goal_id = value
        # handle field 'sequence_no'
        if 'sequence_no' in d:
            field_type = cls.__annotations__.get('sequence_no')
            value = d['sequence_no']
            
            if field_type is bytearray:
                obj.sequence_no = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.sequence_no = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.sequence_no = value
            elif hasattr(field_type, 'from_dict'):
                obj.sequence_no = field_type.from_dict(value)
            else:
                obj.sequence_no = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
