require 'json'

module HakoPdu
  module HakoSrvMsgs
    # ROS message: hako_srv_msgs/SystemControlRequest
    # Generated by hakoniwa-ros2pdu.
    class SystemControlRequest
      attr_accessor :opcode

      def initialize(opcode: 0)

        @opcode = opcode

      end

      def to_h
        {

          'opcode' => self.class.encode_value(@opcode)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          opcode: decode_opcode(hash.fetch('opcode', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_opcode(value)
        value
      end

end
  end
end
