require 'json'

module HakoPdu
  module HakoSrvMsgs
    # ROS message: hako_srv_msgs/SimControlRequest
    # Generated by hakoniwa-ros2pdu.
    class SimControlRequest
      attr_accessor :name, :op

      def initialize(name: "", op: 0)

        @name = name

        @op = op

      end

      def to_h
        {

          'name' => self.class.encode_value(@name),

          'op' => self.class.encode_value(@op)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          name: decode_name(hash.fetch('name', "")),

          op: decode_op(hash.fetch('op', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_name(value)
        value
      end


      def self.decode_op(value)
        value
      end

end
  end
end
