require 'json'

module HakoPdu
  module HakoSrvMsgs
    # ROS message: hako_srv_msgs/GetEventResponse
    # Generated by hakoniwa-ros2pdu.
    class GetEventResponse
      attr_accessor :event_code

      def initialize(event_code: 0)

        @event_code = event_code

      end

      def to_h
        {

          'event_code' => self.class.encode_value(@event_code)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          event_code: decode_event_code(hash.fetch('event_code', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_event_code(value)
        value
      end

end
  end
end
