require 'json'

module HakoPdu
  module HakoSrvMsgs
    # ROS message: hako_srv_msgs/RegisterClientRequest
    # Generated by hakoniwa-ros2pdu.
    class RegisterClientRequest
      attr_accessor :dummy

      def initialize(dummy: 0)

        @dummy = dummy

      end

      def to_h
        {

          'dummy' => self.class.encode_value(@dummy)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          dummy: decode_dummy(hash.fetch('dummy', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_dummy(value)
        value
      end

end
  end
end
