require 'json'

module HakoPdu
  module HakoSrvMsgs
    # ROS message: hako_srv_msgs/AddTwoIntsRequest
    # Generated by hakoniwa-ros2pdu.
    class AddTwoIntsRequest
      attr_accessor :a, :b

      def initialize(a: 0, b: 0)

        @a = a

        @b = b

      end

      def to_h
        {

          'a' => self.class.encode_value(@a),

          'b' => self.class.encode_value(@b)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          a: decode_a(hash.fetch('a', 0)),

          b: decode_b(hash.fetch('b', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_a(value)
        value
      end


      def self.decode_b(value)
        value
      end

end
  end
end
