require_relative '../hako_srv_msgs/pdu_type_LogicalTime'
require 'json'

module HakoPdu
  module HakoSrvMsgs
    # ROS message: hako_srv_msgs/NotifyAssetTimeRequest
    # Generated by hakoniwa-ros2pdu.
    class NotifyAssetTimeRequest
      attr_accessor :session_id, :asset_time

      def initialize(session_id: 0, asset_time: HakoPdu::HakoSrvMsgs::LogicalTime.new)

        @session_id = session_id

        @asset_time = asset_time

      end

      def to_h
        {

          'session_id' => self.class.encode_value(@session_id),

          'asset_time' => self.class.encode_value(@asset_time)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          session_id: decode_session_id(hash.fetch('session_id', 0)),

          asset_time: decode_asset_time(hash.fetch('asset_time', HakoPdu::HakoSrvMsgs::LogicalTime.new))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_session_id(value)
        value
      end


      def self.decode_asset_time(value)
        value.is_a?(Hash) ? HakoPdu::HakoSrvMsgs::LogicalTime.from_h(value) : value
      end

end
  end
end
