require 'json'

module HakoPdu
  module HakoSrvMsgs
    # ROS message: hako_srv_msgs/ServiceRequestHeader
    # Generated by hakoniwa-ros2pdu.
    class ServiceRequestHeader
      attr_accessor :request_id, :service_name, :client_name, :opcode, :status_poll_interval_msec

      def initialize(request_id: 0, service_name: "", client_name: "", opcode: 0, status_poll_interval_msec: 0)

        @request_id = request_id

        @service_name = service_name

        @client_name = client_name

        @opcode = opcode

        @status_poll_interval_msec = status_poll_interval_msec

      end

      def to_h
        {

          'request_id' => self.class.encode_value(@request_id),

          'service_name' => self.class.encode_value(@service_name),

          'client_name' => self.class.encode_value(@client_name),

          'opcode' => self.class.encode_value(@opcode),

          'status_poll_interval_msec' => self.class.encode_value(@status_poll_interval_msec)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          request_id: decode_request_id(hash.fetch('request_id', 0)),

          service_name: decode_service_name(hash.fetch('service_name', "")),

          client_name: decode_client_name(hash.fetch('client_name', "")),

          opcode: decode_opcode(hash.fetch('opcode', 0)),

          status_poll_interval_msec: decode_status_poll_interval_msec(hash.fetch('status_poll_interval_msec', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_request_id(value)
        value
      end


      def self.decode_service_name(value)
        value
      end


      def self.decode_client_name(value)
        value
      end


      def self.decode_opcode(value)
        value
      end


      def self.decode_status_poll_interval_msec(value)
        value
      end

end
  end
end
