require 'json'

module HakoPdu
  module HakoSrvMsgs
    # ROS message: hako_srv_msgs/SystemControlResponse
    # Generated by hakoniwa-ros2pdu.
    class SystemControlResponse
      attr_accessor :status_code, :message

      def initialize(status_code: 0, message: "")

        @status_code = status_code

        @message = message

      end

      def to_h
        {

          'status_code' => self.class.encode_value(@status_code),

          'message' => self.class.encode_value(@message)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          status_code: decode_status_code(hash.fetch('status_code', 0)),

          message: decode_message(hash.fetch('message', ""))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_status_code(value)
        value
      end


      def self.decode_message(value)
        value
      end

end
  end
end
