require 'json'

module HakoPdu
  module HakoSrvMsgs
    # ROS message: hako_srv_msgs/AddTwoIntsResponse
    # Generated by hakoniwa-ros2pdu.
    class AddTwoIntsResponse
      attr_accessor :sum

      def initialize(sum: 0)

        @sum = sum

      end

      def to_h
        {

          'sum' => self.class.encode_value(@sum)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          sum: decode_sum(hash.fetch('sum', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_sum(value)
        value
      end

end
  end
end
