require 'json'

module HakoPdu
  module HakoSrvMsgs
    # ROS message: hako_srv_msgs/NotifyAssetTimeResponse
    # Generated by hakoniwa-ros2pdu.
    class NotifyAssetTimeResponse
      attr_accessor :result_code

      def initialize(result_code: 0)

        @result_code = result_code

      end

      def to_h
        {

          'result_code' => self.class.encode_value(@result_code)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          result_code: decode_result_code(hash.fetch('result_code', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_result_code(value)
        value
      end

end
  end
end
