require 'json'

module HakoPdu
  module HakoSrvMsgs
    # ROS message: hako_srv_msgs/AckEventRequest
    # Generated by hakoniwa-ros2pdu.
    class AckEventRequest
      attr_accessor :name, :event_code, :result_code

      def initialize(name: "", event_code: 0, result_code: 0)

        @name = name

        @event_code = event_code

        @result_code = result_code

      end

      def to_h
        {

          'name' => self.class.encode_value(@name),

          'event_code' => self.class.encode_value(@event_code),

          'result_code' => self.class.encode_value(@result_code)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          name: decode_name(hash.fetch('name', "")),

          event_code: decode_event_code(hash.fetch('event_code', 0)),

          result_code: decode_result_code(hash.fetch('result_code', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_name(value)
        value
      end


      def self.decode_event_code(value)
        value
      end


      def self.decode_result_code(value)
        value
      end

end
  end
end
