import { AckermannDrive } from '../ackermann_msgs/pdu_jstype_AckermannDrive.js';
import { Header } from '../std_msgs/pdu_jstype_Header.js';
import { Time } from '../builtin_interfaces/pdu_jstype_Time.js';


/**
 * ROS message: ackermann_msgs/AckermannDriveStamped
 * Generated by hakoniwa-ros2pdu.
 */
export class AckermannDriveStamped {
/** @type { Header } */
    header;
/** @type { AckermannDrive } */
    drive;


    constructor() {
        this.header = new Header();
        this.drive = new AckermannDrive();
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'header'
            const field_val = this.header;
            if (typeof field_val?.toDict === 'function') {
                d['header'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['header'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['header'] = field_val.toString();
            } else {
                d['header'] = field_val;
            }
        }
        {
            // handle field 'drive'
            const field_val = this.drive;
            if (typeof field_val?.toDict === 'function') {
                d['drive'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['drive'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['drive'] = field_val.toString();
            } else {
                d['drive'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { AckermannDriveStamped }
     */
    static fromDict(d) {
        const obj = new AckermannDriveStamped();
        if (d.hasOwnProperty('header')) {
            const field_class = Header;
            if (d.header) {
                obj.header = field_class.fromDict(d.header);
            }
        }
        if (d.hasOwnProperty('drive')) {
            const field_class = AckermannDrive;
            if (d.drive) {
                obj.drive = field_class.fromDict(d.drive);
            }
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { AckermannDriveStamped }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
