import { Header } from '../std_msgs/pdu_jstype_Header.js';
import { Point32 } from '../geometry_msgs/pdu_jstype_Point32.js';
import { Polygon } from '../geometry_msgs/pdu_jstype_Polygon.js';
import { Time } from '../builtin_interfaces/pdu_jstype_Time.js';


/**
 * ROS message: geometry_msgs/PolygonStamped
 * Generated by hakoniwa-ros2pdu.
 */
export class PolygonStamped {
/** @type { Header } */
    header;
/** @type { Polygon } */
    polygon;


    constructor() {
        this.header = new Header();
        this.polygon = new Polygon();
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'header'
            const field_val = this.header;
            if (typeof field_val?.toDict === 'function') {
                d['header'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['header'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['header'] = field_val;
            }
        }
        {
            // handle field 'polygon'
            const field_val = this.polygon;
            if (typeof field_val?.toDict === 'function') {
                d['polygon'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['polygon'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['polygon'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { PolygonStamped }
     */
    static fromDict(d) {
        const obj = new PolygonStamped();
        if (d.hasOwnProperty('header')) {
            const field_class = Header;
            if (d.header) {
                obj.header = field_class.fromDict(d.header);
            }
        }
        if (d.hasOwnProperty('polygon')) {
            const field_class = Polygon;
            if (d.polygon) {
                obj.polygon = field_class.fromDict(d.polygon);
            }
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { PolygonStamped }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
