import { Header } from '../std_msgs/pdu_jstype_Header.js';
import { Point } from '../geometry_msgs/pdu_jstype_Point.js';
import { Pose } from '../geometry_msgs/pdu_jstype_Pose.js';
import { Quaternion } from '../geometry_msgs/pdu_jstype_Quaternion.js';
import { Time } from '../builtin_interfaces/pdu_jstype_Time.js';


/**
 * ROS message: geometry_msgs/PoseStamped
 * Generated by hakoniwa-ros2pdu.
 */
export class PoseStamped {
/** @type { Header } */
    header;
/** @type { Pose } */
    pose;


    constructor() {
        this.header = new Header();
        this.pose = new Pose();
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'header'
            const field_val = this.header;
            if (typeof field_val?.toDict === 'function') {
                d['header'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['header'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['header'] = field_val;
            }
        }
        {
            // handle field 'pose'
            const field_val = this.pose;
            if (typeof field_val?.toDict === 'function') {
                d['pose'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['pose'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['pose'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { PoseStamped }
     */
    static fromDict(d) {
        const obj = new PoseStamped();
        if (d.hasOwnProperty('header')) {
            const field_class = Header;
            if (d.header) {
                obj.header = field_class.fromDict(d.header);
            }
        }
        if (d.hasOwnProperty('pose')) {
            const field_class = Pose;
            if (d.pose) {
                obj.pose = field_class.fromDict(d.pose);
            }
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { PoseStamped }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
