import { Vector3 } from '../geometry_msgs/pdu_jstype_Vector3.js';


/**
 * ROS message: geometry_msgs/Inertia
 * Generated by hakoniwa-ros2pdu.
 */
export class Inertia {
/** @type { number } */
    m;
/** @type { Vector3 } */
    com;
/** @type { number } */
    ixx;
/** @type { number } */
    ixy;
/** @type { number } */
    ixz;
/** @type { number } */
    iyy;
/** @type { number } */
    iyz;
/** @type { number } */
    izz;


    constructor() {
        this.m = 0.0;
        this.com = new Vector3();
        this.ixx = 0.0;
        this.ixy = 0.0;
        this.ixz = 0.0;
        this.iyy = 0.0;
        this.iyz = 0.0;
        this.izz = 0.0;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'm'
            const field_val = this.m;
            if (typeof field_val?.toDict === 'function') {
                d['m'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['m'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['m'] = field_val;
            }
        }
        {
            // handle field 'com'
            const field_val = this.com;
            if (typeof field_val?.toDict === 'function') {
                d['com'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['com'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['com'] = field_val;
            }
        }
        {
            // handle field 'ixx'
            const field_val = this.ixx;
            if (typeof field_val?.toDict === 'function') {
                d['ixx'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['ixx'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['ixx'] = field_val;
            }
        }
        {
            // handle field 'ixy'
            const field_val = this.ixy;
            if (typeof field_val?.toDict === 'function') {
                d['ixy'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['ixy'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['ixy'] = field_val;
            }
        }
        {
            // handle field 'ixz'
            const field_val = this.ixz;
            if (typeof field_val?.toDict === 'function') {
                d['ixz'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['ixz'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['ixz'] = field_val;
            }
        }
        {
            // handle field 'iyy'
            const field_val = this.iyy;
            if (typeof field_val?.toDict === 'function') {
                d['iyy'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['iyy'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['iyy'] = field_val;
            }
        }
        {
            // handle field 'iyz'
            const field_val = this.iyz;
            if (typeof field_val?.toDict === 'function') {
                d['iyz'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['iyz'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['iyz'] = field_val;
            }
        }
        {
            // handle field 'izz'
            const field_val = this.izz;
            if (typeof field_val?.toDict === 'function') {
                d['izz'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['izz'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['izz'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { Inertia }
     */
    static fromDict(d) {
        const obj = new Inertia();
        if (d.hasOwnProperty('m')) {
            obj.m = d.m;
        }
        if (d.hasOwnProperty('com')) {
            const field_class = Vector3;
            if (d.com) {
                obj.com = field_class.fromDict(d.com);
            }
        }
        if (d.hasOwnProperty('ixx')) {
            obj.ixx = d.ixx;
        }
        if (d.hasOwnProperty('ixy')) {
            obj.ixy = d.ixy;
        }
        if (d.hasOwnProperty('ixz')) {
            obj.ixz = d.ixz;
        }
        if (d.hasOwnProperty('iyy')) {
            obj.iyy = d.iyy;
        }
        if (d.hasOwnProperty('iyz')) {
            obj.iyz = d.iyz;
        }
        if (d.hasOwnProperty('izz')) {
            obj.izz = d.izz;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { Inertia }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
