import { Point32 } from '../geometry_msgs/pdu_jstype_Point32.js';


/**
 * ROS message: geometry_msgs/Polygon
 * Generated by hakoniwa-ros2pdu.
 */
export class Polygon {
/** @type { Array<Point32> } */
    points;


    constructor() {
        this.points = [];
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'points'
            const field_val = this.points;
            if (typeof field_val?.toDict === 'function') {
                d['points'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['points'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['points'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { Polygon }
     */
    static fromDict(d) {
        const obj = new Polygon();
        if (d.hasOwnProperty('points')) {
            const item_class = Point32;
            if (Array.isArray(d.points)) {
                obj.points = d.points.map(item => item_class.fromDict(item));
            }
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { Polygon }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
