import { Header } from '../std_msgs/pdu_jstype_Header.js';
import { Point } from '../geometry_msgs/pdu_jstype_Point.js';
import { Time } from '../builtin_interfaces/pdu_jstype_Time.js';


/**
 * ROS message: geometry_msgs/PointStamped
 * Generated by hakoniwa-ros2pdu.
 */
export class PointStamped {
/** @type { Header } */
    header;
/** @type { Point } */
    point;


    constructor() {
        this.header = new Header();
        this.point = new Point();
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'header'
            const field_val = this.header;
            if (typeof field_val?.toDict === 'function') {
                d['header'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['header'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['header'] = field_val;
            }
        }
        {
            // handle field 'point'
            const field_val = this.point;
            if (typeof field_val?.toDict === 'function') {
                d['point'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['point'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['point'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { PointStamped }
     */
    static fromDict(d) {
        const obj = new PointStamped();
        if (d.hasOwnProperty('header')) {
            const field_class = Header;
            if (d.header) {
                obj.header = field_class.fromDict(d.header);
            }
        }
        if (d.hasOwnProperty('point')) {
            const field_class = Point;
            if (d.point) {
                obj.point = field_class.fromDict(d.point);
            }
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { PointStamped }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
