import { Header } from '../std_msgs/pdu_jstype_Header.js';
import { Time } from '../builtin_interfaces/pdu_jstype_Time.js';
import { Twist } from '../geometry_msgs/pdu_jstype_Twist.js';
import { TwistWithCovariance } from '../geometry_msgs/pdu_jstype_TwistWithCovariance.js';
import { Vector3 } from '../geometry_msgs/pdu_jstype_Vector3.js';


/**
 * ROS message: geometry_msgs/TwistWithCovarianceStamped
 * Generated by hakoniwa-ros2pdu.
 */
export class TwistWithCovarianceStamped {
/** @type { Header } */
    header;
/** @type { TwistWithCovariance } */
    twist;


    constructor() {
        this.header = new Header();
        this.twist = new TwistWithCovariance();
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'header'
            const field_val = this.header;
            if (typeof field_val?.toDict === 'function') {
                d['header'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['header'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['header'] = field_val;
            }
        }
        {
            // handle field 'twist'
            const field_val = this.twist;
            if (typeof field_val?.toDict === 'function') {
                d['twist'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['twist'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['twist'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { TwistWithCovarianceStamped }
     */
    static fromDict(d) {
        const obj = new TwistWithCovarianceStamped();
        if (d.hasOwnProperty('header')) {
            const field_class = Header;
            if (d.header) {
                obj.header = field_class.fromDict(d.header);
            }
        }
        if (d.hasOwnProperty('twist')) {
            const field_class = TwistWithCovariance;
            if (d.twist) {
                obj.twist = field_class.fromDict(d.twist);
            }
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { TwistWithCovarianceStamped }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
