import { MultiArrayDimension } from '../std_msgs/pdu_jstype_MultiArrayDimension.js';
import { MultiArrayLayout } from '../std_msgs/pdu_jstype_MultiArrayLayout.js';


/**
 * ROS message: std_msgs/Int64MultiArray
 * Generated by hakoniwa-ros2pdu.
 */
export class Int64MultiArray {
/** @type { MultiArrayLayout } */
    layout;
/** @type { Array<bigint> } */
    data;


    constructor() {
        this.layout = new MultiArrayLayout();
        this.data = [];
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'layout'
            const field_val = this.layout;
            if (typeof field_val?.toDict === 'function') {
                d['layout'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['layout'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['layout'] = field_val.toString();
            } else {
                d['layout'] = field_val;
            }
        }
        {
            // handle field 'data'
            const field_val = this.data;
            if (typeof field_val?.toDict === 'function') {
                d['data'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['data'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['data'] = field_val.toString();
            } else {
                d['data'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { Int64MultiArray }
     */
    static fromDict(d) {
        const obj = new Int64MultiArray();
        if (d.hasOwnProperty('layout')) {
            const field_class = MultiArrayLayout;
            if (d.layout) {
                obj.layout = field_class.fromDict(d.layout);
            }
        }
        if (d.hasOwnProperty('data')) {
            obj.data = Array.isArray(d.data) ? d.data.map(item => BigInt(item)) : [];
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { Int64MultiArray }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
