require_relative '../std_msgs/pdu_type_Header'
require_relative '../nav_msgs/pdu_type_MapMetaData'
require_relative '../geometry_msgs/pdu_type_Point'
require_relative '../geometry_msgs/pdu_type_Pose'
require_relative '../geometry_msgs/pdu_type_Quaternion'
require_relative '../builtin_interfaces/pdu_type_Time'
require 'json'

module HakoPdu
  module NavMsgs
    # ROS message: nav_msgs/OccupancyGrid
    # Generated by hakoniwa-ros2pdu.
    class OccupancyGrid
      attr_accessor :header, :info, :data

      def initialize(header: HakoPdu::StdMsgs::Header.new, info: HakoPdu::NavMsgs::MapMetaData.new, data: [])

        @header = header

        @info = info

        @data = data

      end

      def to_h
        {

          'header' => self.class.encode_value(@header),

          'info' => self.class.encode_value(@info),

          'data' => self.class.encode_value(@data)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          header: decode_header(hash.fetch('header', HakoPdu::StdMsgs::Header.new)),

          info: decode_info(hash.fetch('info', HakoPdu::NavMsgs::MapMetaData.new)),

          data: decode_data(hash.fetch('data', []))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_header(value)
        value.is_a?(Hash) ? HakoPdu::StdMsgs::Header.from_h(value) : value
      end


      def self.decode_info(value)
        value.is_a?(Hash) ? HakoPdu::NavMsgs::MapMetaData.from_h(value) : value
      end


      def self.decode_data(value)
        value
      end

end
  end
end
