require_relative '../can_msgs/pdu_type_HakoCanBody'
require_relative '../can_msgs/pdu_type_HakoCanHead'
require 'json'

module HakoPdu
  module CanMsgs
    # ROS message: can_msgs/HakoCan
    # Generated by hakoniwa-ros2pdu.
    class HakoCan
      attr_accessor :head, :body

      def initialize(head: HakoPdu::CanMsgs::HakoCanHead.new, body: HakoPdu::CanMsgs::HakoCanBody.new)

        @head = head

        @body = body

      end

      def to_h
        {

          'head' => self.class.encode_value(@head),

          'body' => self.class.encode_value(@body)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          head: decode_head(hash.fetch('head', HakoPdu::CanMsgs::HakoCanHead.new)),

          body: decode_body(hash.fetch('body', HakoPdu::CanMsgs::HakoCanBody.new))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_head(value)
        value.is_a?(Hash) ? HakoPdu::CanMsgs::HakoCanHead.from_h(value) : value
      end


      def self.decode_body(value)
        value.is_a?(Hash) ? HakoPdu::CanMsgs::HakoCanBody.from_h(value) : value
      end

end
  end
end
