require 'json'

module HakoPdu
  module HakoMavlinkMsgs
    # ROS message: hako_mavlink_msgs/HakoHilStateQuaternion
    # Generated by hakoniwa-ros2pdu.
    class HakoHilStateQuaternion
      attr_accessor :time_usec, :attitude_quaternion, :rollspeed, :pitchspeed, :yawspeed, :lat, :lon, :alt, :vx, :vy, :vz, :ind_airspeed, :true_airspeed, :xacc, :yacc, :zacc

      def initialize(time_usec: 0, attitude_quaternion: [], rollspeed: 0.0, pitchspeed: 0.0, yawspeed: 0.0, lat: 0, lon: 0, alt: 0, vx: 0, vy: 0, vz: 0, ind_airspeed: 0, true_airspeed: 0, xacc: 0, yacc: 0, zacc: 0)

        @time_usec = time_usec

        @attitude_quaternion = attitude_quaternion

        @rollspeed = rollspeed

        @pitchspeed = pitchspeed

        @yawspeed = yawspeed

        @lat = lat

        @lon = lon

        @alt = alt

        @vx = vx

        @vy = vy

        @vz = vz

        @ind_airspeed = ind_airspeed

        @true_airspeed = true_airspeed

        @xacc = xacc

        @yacc = yacc

        @zacc = zacc

      end

      def to_h
        {

          'time_usec' => self.class.encode_value(@time_usec),

          'attitude_quaternion' => self.class.encode_value(@attitude_quaternion),

          'rollspeed' => self.class.encode_value(@rollspeed),

          'pitchspeed' => self.class.encode_value(@pitchspeed),

          'yawspeed' => self.class.encode_value(@yawspeed),

          'lat' => self.class.encode_value(@lat),

          'lon' => self.class.encode_value(@lon),

          'alt' => self.class.encode_value(@alt),

          'vx' => self.class.encode_value(@vx),

          'vy' => self.class.encode_value(@vy),

          'vz' => self.class.encode_value(@vz),

          'ind_airspeed' => self.class.encode_value(@ind_airspeed),

          'true_airspeed' => self.class.encode_value(@true_airspeed),

          'xacc' => self.class.encode_value(@xacc),

          'yacc' => self.class.encode_value(@yacc),

          'zacc' => self.class.encode_value(@zacc)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          time_usec: decode_time_usec(hash.fetch('time_usec', 0)),

          attitude_quaternion: decode_attitude_quaternion(hash.fetch('attitude_quaternion', [])),

          rollspeed: decode_rollspeed(hash.fetch('rollspeed', 0.0)),

          pitchspeed: decode_pitchspeed(hash.fetch('pitchspeed', 0.0)),

          yawspeed: decode_yawspeed(hash.fetch('yawspeed', 0.0)),

          lat: decode_lat(hash.fetch('lat', 0)),

          lon: decode_lon(hash.fetch('lon', 0)),

          alt: decode_alt(hash.fetch('alt', 0)),

          vx: decode_vx(hash.fetch('vx', 0)),

          vy: decode_vy(hash.fetch('vy', 0)),

          vz: decode_vz(hash.fetch('vz', 0)),

          ind_airspeed: decode_ind_airspeed(hash.fetch('ind_airspeed', 0)),

          true_airspeed: decode_true_airspeed(hash.fetch('true_airspeed', 0)),

          xacc: decode_xacc(hash.fetch('xacc', 0)),

          yacc: decode_yacc(hash.fetch('yacc', 0)),

          zacc: decode_zacc(hash.fetch('zacc', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_time_usec(value)
        value
      end


      def self.decode_attitude_quaternion(value)
        value
      end


      def self.decode_rollspeed(value)
        value
      end


      def self.decode_pitchspeed(value)
        value
      end


      def self.decode_yawspeed(value)
        value
      end


      def self.decode_lat(value)
        value
      end


      def self.decode_lon(value)
        value
      end


      def self.decode_alt(value)
        value
      end


      def self.decode_vx(value)
        value
      end


      def self.decode_vy(value)
        value
      end


      def self.decode_vz(value)
        value
      end


      def self.decode_ind_airspeed(value)
        value
      end


      def self.decode_true_airspeed(value)
        value
      end


      def self.decode_xacc(value)
        value
      end


      def self.decode_yacc(value)
        value
      end


      def self.decode_zacc(value)
        value
      end

end
  end
end
