require 'json'

module HakoPdu
  module HakoMavlinkMsgs
    # ROS message: hako_mavlink_msgs/HakoHilGps
    # Generated by hakoniwa-ros2pdu.
    class HakoHilGps
      attr_accessor :time_usec, :lat, :lon, :alt, :eph, :epv, :vel, :vn, :ve, :vd, :cog, :satellites_visible, :id, :yaw, :fix_type

      def initialize(time_usec: 0, lat: 0, lon: 0, alt: 0, eph: 0, epv: 0, vel: 0, vn: 0, ve: 0, vd: 0, cog: 0, satellites_visible: 0, id: 0, yaw: 0, fix_type: 0)

        @time_usec = time_usec

        @lat = lat

        @lon = lon

        @alt = alt

        @eph = eph

        @epv = epv

        @vel = vel

        @vn = vn

        @ve = ve

        @vd = vd

        @cog = cog

        @satellites_visible = satellites_visible

        @id = id

        @yaw = yaw

        @fix_type = fix_type

      end

      def to_h
        {

          'time_usec' => self.class.encode_value(@time_usec),

          'lat' => self.class.encode_value(@lat),

          'lon' => self.class.encode_value(@lon),

          'alt' => self.class.encode_value(@alt),

          'eph' => self.class.encode_value(@eph),

          'epv' => self.class.encode_value(@epv),

          'vel' => self.class.encode_value(@vel),

          'vn' => self.class.encode_value(@vn),

          've' => self.class.encode_value(@ve),

          'vd' => self.class.encode_value(@vd),

          'cog' => self.class.encode_value(@cog),

          'satellites_visible' => self.class.encode_value(@satellites_visible),

          'id' => self.class.encode_value(@id),

          'yaw' => self.class.encode_value(@yaw),

          'fix_type' => self.class.encode_value(@fix_type)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          time_usec: decode_time_usec(hash.fetch('time_usec', 0)),

          lat: decode_lat(hash.fetch('lat', 0)),

          lon: decode_lon(hash.fetch('lon', 0)),

          alt: decode_alt(hash.fetch('alt', 0)),

          eph: decode_eph(hash.fetch('eph', 0)),

          epv: decode_epv(hash.fetch('epv', 0)),

          vel: decode_vel(hash.fetch('vel', 0)),

          vn: decode_vn(hash.fetch('vn', 0)),

          ve: decode_ve(hash.fetch('ve', 0)),

          vd: decode_vd(hash.fetch('vd', 0)),

          cog: decode_cog(hash.fetch('cog', 0)),

          satellites_visible: decode_satellites_visible(hash.fetch('satellites_visible', 0)),

          id: decode_id(hash.fetch('id', 0)),

          yaw: decode_yaw(hash.fetch('yaw', 0)),

          fix_type: decode_fix_type(hash.fetch('fix_type', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_time_usec(value)
        value
      end


      def self.decode_lat(value)
        value
      end


      def self.decode_lon(value)
        value
      end


      def self.decode_alt(value)
        value
      end


      def self.decode_eph(value)
        value
      end


      def self.decode_epv(value)
        value
      end


      def self.decode_vel(value)
        value
      end


      def self.decode_vn(value)
        value
      end


      def self.decode_ve(value)
        value
      end


      def self.decode_vd(value)
        value
      end


      def self.decode_cog(value)
        value
      end


      def self.decode_satellites_visible(value)
        value
      end


      def self.decode_id(value)
        value
      end


      def self.decode_yaw(value)
        value
      end


      def self.decode_fix_type(value)
        value
      end

end
  end
end
