require 'json'

module HakoPdu
  module HakoMavlinkMsgs
    # ROS message: hako_mavlink_msgs/HakoHilActuatorControls
    # Generated by hakoniwa-ros2pdu.
    class HakoHilActuatorControls
      attr_accessor :time_usec, :controls, :mode, :flags

      def initialize(time_usec: 0, controls: [], mode: 0, flags: 0)

        @time_usec = time_usec

        @controls = controls

        @mode = mode

        @flags = flags

      end

      def to_h
        {

          'time_usec' => self.class.encode_value(@time_usec),

          'controls' => self.class.encode_value(@controls),

          'mode' => self.class.encode_value(@mode),

          'flags' => self.class.encode_value(@flags)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          time_usec: decode_time_usec(hash.fetch('time_usec', 0)),

          controls: decode_controls(hash.fetch('controls', [])),

          mode: decode_mode(hash.fetch('mode', 0)),

          flags: decode_flags(hash.fetch('flags', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_time_usec(value)
        value
      end


      def self.decode_controls(value)
        value
      end


      def self.decode_mode(value)
        value
      end


      def self.decode_flags(value)
        value
      end

end
  end
end
