require 'json'

module HakoPdu
  module HakoMavlinkMsgs
    # ROS message: hako_mavlink_msgs/HakoAHRS2
    # Generated by hakoniwa-ros2pdu.
    class HakoAHRS2
      attr_accessor :roll, :pitch, :yaw, :altitude, :lat, :lng

      def initialize(roll: 0.0, pitch: 0.0, yaw: 0.0, altitude: 0.0, lat: 0, lng: 0)

        @roll = roll

        @pitch = pitch

        @yaw = yaw

        @altitude = altitude

        @lat = lat

        @lng = lng

      end

      def to_h
        {

          'roll' => self.class.encode_value(@roll),

          'pitch' => self.class.encode_value(@pitch),

          'yaw' => self.class.encode_value(@yaw),

          'altitude' => self.class.encode_value(@altitude),

          'lat' => self.class.encode_value(@lat),

          'lng' => self.class.encode_value(@lng)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          roll: decode_roll(hash.fetch('roll', 0.0)),

          pitch: decode_pitch(hash.fetch('pitch', 0.0)),

          yaw: decode_yaw(hash.fetch('yaw', 0.0)),

          altitude: decode_altitude(hash.fetch('altitude', 0.0)),

          lat: decode_lat(hash.fetch('lat', 0)),

          lng: decode_lng(hash.fetch('lng', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_roll(value)
        value
      end


      def self.decode_pitch(value)
        value
      end


      def self.decode_yaw(value)
        value
      end


      def self.decode_altitude(value)
        value
      end


      def self.decode_lat(value)
        value
      end


      def self.decode_lng(value)
        value
      end

end
  end
end
