require 'json'

module HakoPdu
  module HakoMavlinkMsgs
    # ROS message: hako_mavlink_msgs/HakoGLOBAL_POSITION_INT
    # Generated by hakoniwa-ros2pdu.
    class HakoGLOBAL_POSITION_INT
      attr_accessor :time_boot_ms, :lat, :lon, :alt, :relative_alt, :vx, :vy, :vz, :hdg

      def initialize(time_boot_ms: 0, lat: 0, lon: 0, alt: 0, relative_alt: 0, vx: 0, vy: 0, vz: 0, hdg: 0)

        @time_boot_ms = time_boot_ms

        @lat = lat

        @lon = lon

        @alt = alt

        @relative_alt = relative_alt

        @vx = vx

        @vy = vy

        @vz = vz

        @hdg = hdg

      end

      def to_h
        {

          'time_boot_ms' => self.class.encode_value(@time_boot_ms),

          'lat' => self.class.encode_value(@lat),

          'lon' => self.class.encode_value(@lon),

          'alt' => self.class.encode_value(@alt),

          'relative_alt' => self.class.encode_value(@relative_alt),

          'vx' => self.class.encode_value(@vx),

          'vy' => self.class.encode_value(@vy),

          'vz' => self.class.encode_value(@vz),

          'hdg' => self.class.encode_value(@hdg)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          time_boot_ms: decode_time_boot_ms(hash.fetch('time_boot_ms', 0)),

          lat: decode_lat(hash.fetch('lat', 0)),

          lon: decode_lon(hash.fetch('lon', 0)),

          alt: decode_alt(hash.fetch('alt', 0)),

          relative_alt: decode_relative_alt(hash.fetch('relative_alt', 0)),

          vx: decode_vx(hash.fetch('vx', 0)),

          vy: decode_vy(hash.fetch('vy', 0)),

          vz: decode_vz(hash.fetch('vz', 0)),

          hdg: decode_hdg(hash.fetch('hdg', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_time_boot_ms(value)
        value
      end


      def self.decode_lat(value)
        value
      end


      def self.decode_lon(value)
        value
      end


      def self.decode_alt(value)
        value
      end


      def self.decode_relative_alt(value)
        value
      end


      def self.decode_vx(value)
        value
      end


      def self.decode_vy(value)
        value
      end


      def self.decode_vz(value)
        value
      end


      def self.decode_hdg(value)
        value
      end

end
  end
end
