require 'json'

module HakoPdu
  module HakoMavlinkMsgs
    # ROS message: hako_mavlink_msgs/HakoSystemTime
    # Generated by hakoniwa-ros2pdu.
    class HakoSystemTime
      attr_accessor :time_unix_usec, :time_boot_ms

      def initialize(time_unix_usec: 0, time_boot_ms: 0)

        @time_unix_usec = time_unix_usec

        @time_boot_ms = time_boot_ms

      end

      def to_h
        {

          'time_unix_usec' => self.class.encode_value(@time_unix_usec),

          'time_boot_ms' => self.class.encode_value(@time_boot_ms)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          time_unix_usec: decode_time_unix_usec(hash.fetch('time_unix_usec', 0)),

          time_boot_ms: decode_time_boot_ms(hash.fetch('time_boot_ms', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_time_unix_usec(value)
        value
      end


      def self.decode_time_boot_ms(value)
        value
      end

end
  end
end
