require 'json'

module HakoPdu
  module HakoMavlinkMsgs
    # ROS message: hako_mavlink_msgs/HakoATTITUDE
    # Generated by hakoniwa-ros2pdu.
    class HakoATTITUDE
      attr_accessor :time_boot_ms, :roll, :pitch, :yaw, :rollspeed, :pitchspeed, :yawspeed

      def initialize(time_boot_ms: 0, roll: 0.0, pitch: 0.0, yaw: 0.0, rollspeed: 0.0, pitchspeed: 0.0, yawspeed: 0.0)

        @time_boot_ms = time_boot_ms

        @roll = roll

        @pitch = pitch

        @yaw = yaw

        @rollspeed = rollspeed

        @pitchspeed = pitchspeed

        @yawspeed = yawspeed

      end

      def to_h
        {

          'time_boot_ms' => self.class.encode_value(@time_boot_ms),

          'roll' => self.class.encode_value(@roll),

          'pitch' => self.class.encode_value(@pitch),

          'yaw' => self.class.encode_value(@yaw),

          'rollspeed' => self.class.encode_value(@rollspeed),

          'pitchspeed' => self.class.encode_value(@pitchspeed),

          'yawspeed' => self.class.encode_value(@yawspeed)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          time_boot_ms: decode_time_boot_ms(hash.fetch('time_boot_ms', 0)),

          roll: decode_roll(hash.fetch('roll', 0.0)),

          pitch: decode_pitch(hash.fetch('pitch', 0.0)),

          yaw: decode_yaw(hash.fetch('yaw', 0.0)),

          rollspeed: decode_rollspeed(hash.fetch('rollspeed', 0.0)),

          pitchspeed: decode_pitchspeed(hash.fetch('pitchspeed', 0.0)),

          yawspeed: decode_yawspeed(hash.fetch('yawspeed', 0.0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_time_boot_ms(value)
        value
      end


      def self.decode_roll(value)
        value
      end


      def self.decode_pitch(value)
        value
      end


      def self.decode_yaw(value)
        value
      end


      def self.decode_rollspeed(value)
        value
      end


      def self.decode_pitchspeed(value)
        value
      end


      def self.decode_yawspeed(value)
        value
      end

end
  end
end
