require 'json'

module HakoPdu
  module HakoMavlinkMsgs
    # ROS message: hako_mavlink_msgs/HakoSERVO_OUTPUT_RAW
    # Generated by hakoniwa-ros2pdu.
    class HakoSERVO_OUTPUT_RAW
      attr_accessor :time_usec, :port, :servo1_raw, :servo2_raw, :servo3_raw, :servo4_raw, :servo5_raw, :servo6_raw, :servo7_raw, :servo8_raw

      def initialize(time_usec: 0, port: 0, servo1_raw: 0, servo2_raw: 0, servo3_raw: 0, servo4_raw: 0, servo5_raw: 0, servo6_raw: 0, servo7_raw: 0, servo8_raw: 0)

        @time_usec = time_usec

        @port = port

        @servo1_raw = servo1_raw

        @servo2_raw = servo2_raw

        @servo3_raw = servo3_raw

        @servo4_raw = servo4_raw

        @servo5_raw = servo5_raw

        @servo6_raw = servo6_raw

        @servo7_raw = servo7_raw

        @servo8_raw = servo8_raw

      end

      def to_h
        {

          'time_usec' => self.class.encode_value(@time_usec),

          'port' => self.class.encode_value(@port),

          'servo1_raw' => self.class.encode_value(@servo1_raw),

          'servo2_raw' => self.class.encode_value(@servo2_raw),

          'servo3_raw' => self.class.encode_value(@servo3_raw),

          'servo4_raw' => self.class.encode_value(@servo4_raw),

          'servo5_raw' => self.class.encode_value(@servo5_raw),

          'servo6_raw' => self.class.encode_value(@servo6_raw),

          'servo7_raw' => self.class.encode_value(@servo7_raw),

          'servo8_raw' => self.class.encode_value(@servo8_raw)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          time_usec: decode_time_usec(hash.fetch('time_usec', 0)),

          port: decode_port(hash.fetch('port', 0)),

          servo1_raw: decode_servo1_raw(hash.fetch('servo1_raw', 0)),

          servo2_raw: decode_servo2_raw(hash.fetch('servo2_raw', 0)),

          servo3_raw: decode_servo3_raw(hash.fetch('servo3_raw', 0)),

          servo4_raw: decode_servo4_raw(hash.fetch('servo4_raw', 0)),

          servo5_raw: decode_servo5_raw(hash.fetch('servo5_raw', 0)),

          servo6_raw: decode_servo6_raw(hash.fetch('servo6_raw', 0)),

          servo7_raw: decode_servo7_raw(hash.fetch('servo7_raw', 0)),

          servo8_raw: decode_servo8_raw(hash.fetch('servo8_raw', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_time_usec(value)
        value
      end


      def self.decode_port(value)
        value
      end


      def self.decode_servo1_raw(value)
        value
      end


      def self.decode_servo2_raw(value)
        value
      end


      def self.decode_servo3_raw(value)
        value
      end


      def self.decode_servo4_raw(value)
        value
      end


      def self.decode_servo5_raw(value)
        value
      end


      def self.decode_servo6_raw(value)
        value
      end


      def self.decode_servo7_raw(value)
        value
      end


      def self.decode_servo8_raw(value)
        value
      end

end
  end
end
