defmodule HakoPdu.HakoMavlinkMsgs.HakoHilSensor do
  @moduledoc """
  ROS message: hako_mavlink_msgs/HakoHilSensor

  Generated by hakoniwa-ros2pdu.
  """

  defstruct [

    time_usec: 0,

    xacc: 0.0,

    yacc: 0.0,

    zacc: 0.0,

    xgyro: 0.0,

    ygyro: 0.0,

    zgyro: 0.0,

    xmag: 0.0,

    ymag: 0.0,

    zmag: 0.0,

    abs_pressure: 0.0,

    diff_pressure: 0.0,

    pressure_alt: 0.0,

    temperature: 0.0,

    fields_updated: 0,

    id: 0

  ]

  def new(attrs \\ %{}) when is_map(attrs) do
    struct(__MODULE__, attrs)
  end

  def to_map(%__MODULE__{} = msg) do
    %{

      "time_usec" => encode_value(msg.time_usec),

      "xacc" => encode_value(msg.xacc),

      "yacc" => encode_value(msg.yacc),

      "zacc" => encode_value(msg.zacc),

      "xgyro" => encode_value(msg.xgyro),

      "ygyro" => encode_value(msg.ygyro),

      "zgyro" => encode_value(msg.zgyro),

      "xmag" => encode_value(msg.xmag),

      "ymag" => encode_value(msg.ymag),

      "zmag" => encode_value(msg.zmag),

      "abs_pressure" => encode_value(msg.abs_pressure),

      "diff_pressure" => encode_value(msg.diff_pressure),

      "pressure_alt" => encode_value(msg.pressure_alt),

      "temperature" => encode_value(msg.temperature),

      "fields_updated" => encode_value(msg.fields_updated),

      "id" => encode_value(msg.id)

    }
  end

  def from_map(map) when is_map(map) do
    %__MODULE__{

      time_usec: map |> get_value(:time_usec, "time_usec", 0) |> decode_time_usec(),

      xacc: map |> get_value(:xacc, "xacc", 0.0) |> decode_xacc(),

      yacc: map |> get_value(:yacc, "yacc", 0.0) |> decode_yacc(),

      zacc: map |> get_value(:zacc, "zacc", 0.0) |> decode_zacc(),

      xgyro: map |> get_value(:xgyro, "xgyro", 0.0) |> decode_xgyro(),

      ygyro: map |> get_value(:ygyro, "ygyro", 0.0) |> decode_ygyro(),

      zgyro: map |> get_value(:zgyro, "zgyro", 0.0) |> decode_zgyro(),

      xmag: map |> get_value(:xmag, "xmag", 0.0) |> decode_xmag(),

      ymag: map |> get_value(:ymag, "ymag", 0.0) |> decode_ymag(),

      zmag: map |> get_value(:zmag, "zmag", 0.0) |> decode_zmag(),

      abs_pressure: map |> get_value(:abs_pressure, "abs_pressure", 0.0) |> decode_abs_pressure(),

      diff_pressure: map |> get_value(:diff_pressure, "diff_pressure", 0.0) |> decode_diff_pressure(),

      pressure_alt: map |> get_value(:pressure_alt, "pressure_alt", 0.0) |> decode_pressure_alt(),

      temperature: map |> get_value(:temperature, "temperature", 0.0) |> decode_temperature(),

      fields_updated: map |> get_value(:fields_updated, "fields_updated", 0) |> decode_fields_updated(),

      id: map |> get_value(:id, "id", 0) |> decode_id()

    }
  end

  def to_json(%__MODULE__{} = msg) do
    msg
    |> to_map()
    |> json_encode()
  end

  def from_json(json) when is_binary(json) do
    json
    |> json_decode()
    |> from_map()
  end

  defp get_value(map, atom_key, string_key, default) do
    Map.get(map, atom_key, Map.get(map, string_key, default))
  end

  defp encode_value(values) when is_list(values), do: Enum.map(values, &encode_value/1)
  defp encode_value(%{__struct__: module} = value) do
    if function_exported?(module, :to_map, 1), do: module.to_map(value), else: value
  end
  defp encode_value(value), do: value

  defp json_encode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :encode!, 1) -> apply(Jason, :encode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :encode!, 1) -> apply(JSON, :encode!, [value])
      true -> raise "No JSON encoder found. Add Jason or JSON to use to_json/1."
    end
  end

  defp json_decode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :decode!, 1) -> apply(Jason, :decode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :decode!, 1) -> apply(JSON, :decode!, [value])
      true -> raise "No JSON decoder found. Add Jason or JSON to use from_json/1."
    end
  end


  defp decode_time_usec(value) do
    value
  end


  defp decode_xacc(value) do
    value
  end


  defp decode_yacc(value) do
    value
  end


  defp decode_zacc(value) do
    value
  end


  defp decode_xgyro(value) do
    value
  end


  defp decode_ygyro(value) do
    value
  end


  defp decode_zgyro(value) do
    value
  end


  defp decode_xmag(value) do
    value
  end


  defp decode_ymag(value) do
    value
  end


  defp decode_zmag(value) do
    value
  end


  defp decode_abs_pressure(value) do
    value
  end


  defp decode_diff_pressure(value) do
    value
  end


  defp decode_pressure_alt(value) do
    value
  end


  defp decode_temperature(value) do
    value
  end


  defp decode_fields_updated(value) do
    value
  end


  defp decode_id(value) do
    value
  end

end
