defmodule HakoPdu.HakoMavlinkMsgs.HakoHeartbeat do
  @moduledoc """
  ROS message: hako_mavlink_msgs/HakoHeartbeat

  Generated by hakoniwa-ros2pdu.
  """

  defstruct [

    type: 0,

    autopilot: 0,

    base_mode: 0,

    custom_mode: 0,

    system_status: 0,

    mavlink_version: 0

  ]

  def new(attrs \\ %{}) when is_map(attrs) do
    struct(__MODULE__, attrs)
  end

  def to_map(%__MODULE__{} = msg) do
    %{

      "type" => encode_value(msg.type),

      "autopilot" => encode_value(msg.autopilot),

      "base_mode" => encode_value(msg.base_mode),

      "custom_mode" => encode_value(msg.custom_mode),

      "system_status" => encode_value(msg.system_status),

      "mavlink_version" => encode_value(msg.mavlink_version)

    }
  end

  def from_map(map) when is_map(map) do
    %__MODULE__{

      type: map |> get_value(:type, "type", 0) |> decode_type(),

      autopilot: map |> get_value(:autopilot, "autopilot", 0) |> decode_autopilot(),

      base_mode: map |> get_value(:base_mode, "base_mode", 0) |> decode_base_mode(),

      custom_mode: map |> get_value(:custom_mode, "custom_mode", 0) |> decode_custom_mode(),

      system_status: map |> get_value(:system_status, "system_status", 0) |> decode_system_status(),

      mavlink_version: map |> get_value(:mavlink_version, "mavlink_version", 0) |> decode_mavlink_version()

    }
  end

  def to_json(%__MODULE__{} = msg) do
    msg
    |> to_map()
    |> json_encode()
  end

  def from_json(json) when is_binary(json) do
    json
    |> json_decode()
    |> from_map()
  end

  defp get_value(map, atom_key, string_key, default) do
    Map.get(map, atom_key, Map.get(map, string_key, default))
  end

  defp encode_value(values) when is_list(values), do: Enum.map(values, &encode_value/1)
  defp encode_value(%{__struct__: module} = value) do
    if function_exported?(module, :to_map, 1), do: module.to_map(value), else: value
  end
  defp encode_value(value), do: value

  defp json_encode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :encode!, 1) -> apply(Jason, :encode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :encode!, 1) -> apply(JSON, :encode!, [value])
      true -> raise "No JSON encoder found. Add Jason or JSON to use to_json/1."
    end
  end

  defp json_decode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :decode!, 1) -> apply(Jason, :decode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :decode!, 1) -> apply(JSON, :decode!, [value])
      true -> raise "No JSON decoder found. Add Jason or JSON to use from_json/1."
    end
  end


  defp decode_type(value) do
    value
  end


  defp decode_autopilot(value) do
    value
  end


  defp decode_base_mode(value) do
    value
  end


  defp decode_custom_mode(value) do
    value
  end


  defp decode_system_status(value) do
    value
  end


  defp decode_mavlink_version(value) do
    value
  end

end
