defmodule HakoPdu.HakoMavlinkMsgs.HakoSERVO_OUTPUT_RAW do
  @moduledoc """
  ROS message: hako_mavlink_msgs/HakoSERVO_OUTPUT_RAW

  Generated by hakoniwa-ros2pdu.
  """

  defstruct [

    time_usec: 0,

    port: 0,

    servo1_raw: 0,

    servo2_raw: 0,

    servo3_raw: 0,

    servo4_raw: 0,

    servo5_raw: 0,

    servo6_raw: 0,

    servo7_raw: 0,

    servo8_raw: 0

  ]

  def new(attrs \\ %{}) when is_map(attrs) do
    struct(__MODULE__, attrs)
  end

  def to_map(%__MODULE__{} = msg) do
    %{

      "time_usec" => encode_value(msg.time_usec),

      "port" => encode_value(msg.port),

      "servo1_raw" => encode_value(msg.servo1_raw),

      "servo2_raw" => encode_value(msg.servo2_raw),

      "servo3_raw" => encode_value(msg.servo3_raw),

      "servo4_raw" => encode_value(msg.servo4_raw),

      "servo5_raw" => encode_value(msg.servo5_raw),

      "servo6_raw" => encode_value(msg.servo6_raw),

      "servo7_raw" => encode_value(msg.servo7_raw),

      "servo8_raw" => encode_value(msg.servo8_raw)

    }
  end

  def from_map(map) when is_map(map) do
    %__MODULE__{

      time_usec: map |> get_value(:time_usec, "time_usec", 0) |> decode_time_usec(),

      port: map |> get_value(:port, "port", 0) |> decode_port(),

      servo1_raw: map |> get_value(:servo1_raw, "servo1_raw", 0) |> decode_servo1_raw(),

      servo2_raw: map |> get_value(:servo2_raw, "servo2_raw", 0) |> decode_servo2_raw(),

      servo3_raw: map |> get_value(:servo3_raw, "servo3_raw", 0) |> decode_servo3_raw(),

      servo4_raw: map |> get_value(:servo4_raw, "servo4_raw", 0) |> decode_servo4_raw(),

      servo5_raw: map |> get_value(:servo5_raw, "servo5_raw", 0) |> decode_servo5_raw(),

      servo6_raw: map |> get_value(:servo6_raw, "servo6_raw", 0) |> decode_servo6_raw(),

      servo7_raw: map |> get_value(:servo7_raw, "servo7_raw", 0) |> decode_servo7_raw(),

      servo8_raw: map |> get_value(:servo8_raw, "servo8_raw", 0) |> decode_servo8_raw()

    }
  end

  def to_json(%__MODULE__{} = msg) do
    msg
    |> to_map()
    |> json_encode()
  end

  def from_json(json) when is_binary(json) do
    json
    |> json_decode()
    |> from_map()
  end

  defp get_value(map, atom_key, string_key, default) do
    Map.get(map, atom_key, Map.get(map, string_key, default))
  end

  defp encode_value(values) when is_list(values), do: Enum.map(values, &encode_value/1)
  defp encode_value(%{__struct__: module} = value) do
    if function_exported?(module, :to_map, 1), do: module.to_map(value), else: value
  end
  defp encode_value(value), do: value

  defp json_encode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :encode!, 1) -> apply(Jason, :encode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :encode!, 1) -> apply(JSON, :encode!, [value])
      true -> raise "No JSON encoder found. Add Jason or JSON to use to_json/1."
    end
  end

  defp json_decode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :decode!, 1) -> apply(Jason, :decode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :decode!, 1) -> apply(JSON, :decode!, [value])
      true -> raise "No JSON decoder found. Add Jason or JSON to use from_json/1."
    end
  end


  defp decode_time_usec(value) do
    value
  end


  defp decode_port(value) do
    value
  end


  defp decode_servo1_raw(value) do
    value
  end


  defp decode_servo2_raw(value) do
    value
  end


  defp decode_servo3_raw(value) do
    value
  end


  defp decode_servo4_raw(value) do
    value
  end


  defp decode_servo5_raw(value) do
    value
  end


  defp decode_servo6_raw(value) do
    value
  end


  defp decode_servo7_raw(value) do
    value
  end


  defp decode_servo8_raw(value) do
    value
  end

end
