import { LogicalTime } from '../hako_srv_msgs/pdu_jstype_LogicalTime.js';


/**
 * ROS message: hako_srv_msgs/GetWorldTimeResponse
 * Generated by hakoniwa-ros2pdu.
 */
export class GetWorldTimeResponse {
/** @type { number } */
    result_code;
/** @type { LogicalTime } */
    world_time;


    constructor() {
        this.result_code = 0;
        this.world_time = new LogicalTime();
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'result_code'
            const field_val = this.result_code;
            if (typeof field_val?.toDict === 'function') {
                d['result_code'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['result_code'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['result_code'] = field_val.toString();
            } else {
                d['result_code'] = field_val;
            }
        }
        {
            // handle field 'world_time'
            const field_val = this.world_time;
            if (typeof field_val?.toDict === 'function') {
                d['world_time'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['world_time'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['world_time'] = field_val.toString();
            } else {
                d['world_time'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { GetWorldTimeResponse }
     */
    static fromDict(d) {
        const obj = new GetWorldTimeResponse();
        if (d.hasOwnProperty('result_code')) {
            obj.result_code = d.result_code;
        }
        if (d.hasOwnProperty('world_time')) {
            const field_class = LogicalTime;
            if (d.world_time) {
                obj.world_time = field_class.fromDict(d.world_time);
            }
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { GetWorldTimeResponse }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
