

/**
 * ROS message: hako_srv_msgs/LogicalTime
 * Generated by hakoniwa-ros2pdu.
 */
export class LogicalTime {
/** @type { bigint } */
    generation;
/** @type { bigint } */
    offset_tick;


    constructor() {
        this.generation = 0n;
        this.offset_tick = 0n;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'generation'
            const field_val = this.generation;
            if (typeof field_val?.toDict === 'function') {
                d['generation'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['generation'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['generation'] = field_val.toString();
            } else {
                d['generation'] = field_val;
            }
        }
        {
            // handle field 'offset_tick'
            const field_val = this.offset_tick;
            if (typeof field_val?.toDict === 'function') {
                d['offset_tick'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['offset_tick'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['offset_tick'] = field_val.toString();
            } else {
                d['offset_tick'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { LogicalTime }
     */
    static fromDict(d) {
        const obj = new LogicalTime();
        if (d.hasOwnProperty('generation')) {
            obj.generation = BigInt(d.generation);
        }
        if (d.hasOwnProperty('offset_tick')) {
            obj.offset_tick = BigInt(d.offset_tick);
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { LogicalTime }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
