

/**
 * ROS message: hako_srv_msgs/AddTwoIntsRequest
 * Generated by hakoniwa-ros2pdu.
 */
export class AddTwoIntsRequest {
/** @type { bigint } */
    a;
/** @type { bigint } */
    b;


    constructor() {
        this.a = 0n;
        this.b = 0n;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'a'
            const field_val = this.a;
            if (typeof field_val?.toDict === 'function') {
                d['a'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['a'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['a'] = field_val.toString();
            } else {
                d['a'] = field_val;
            }
        }
        {
            // handle field 'b'
            const field_val = this.b;
            if (typeof field_val?.toDict === 'function') {
                d['b'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['b'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['b'] = field_val.toString();
            } else {
                d['b'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { AddTwoIntsRequest }
     */
    static fromDict(d) {
        const obj = new AddTwoIntsRequest();
        if (d.hasOwnProperty('a')) {
            obj.a = BigInt(d.a);
        }
        if (d.hasOwnProperty('b')) {
            obj.b = BigInt(d.b);
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { AddTwoIntsRequest }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
