import { GetWorldTimeResponse } from '../hako_srv_msgs/pdu_jstype_GetWorldTimeResponse.js';
import { LogicalTime } from '../hako_srv_msgs/pdu_jstype_LogicalTime.js';
import { ServiceResponseHeader } from '../hako_srv_msgs/pdu_jstype_ServiceResponseHeader.js';


/**
 * ROS message: hako_srv_msgs/GetWorldTimeResponsePacket
 * Generated by hakoniwa-ros2pdu.
 */
export class GetWorldTimeResponsePacket {
/** @type { ServiceResponseHeader } */
    header;
/** @type { GetWorldTimeResponse } */
    body;


    constructor() {
        this.header = new ServiceResponseHeader();
        this.body = new GetWorldTimeResponse();
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'header'
            const field_val = this.header;
            if (typeof field_val?.toDict === 'function') {
                d['header'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['header'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['header'] = field_val.toString();
            } else {
                d['header'] = field_val;
            }
        }
        {
            // handle field 'body'
            const field_val = this.body;
            if (typeof field_val?.toDict === 'function') {
                d['body'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['body'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['body'] = field_val.toString();
            } else {
                d['body'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { GetWorldTimeResponsePacket }
     */
    static fromDict(d) {
        const obj = new GetWorldTimeResponsePacket();
        if (d.hasOwnProperty('header')) {
            const field_class = ServiceResponseHeader;
            if (d.header) {
                obj.header = field_class.fromDict(d.header);
            }
        }
        if (d.hasOwnProperty('body')) {
            const field_class = GetWorldTimeResponse;
            if (d.body) {
                obj.body = field_class.fromDict(d.body);
            }
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { GetWorldTimeResponsePacket }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
