

/**
 * ROS message: hako_srv_msgs/SimControlResponse
 * Generated by hakoniwa-ros2pdu.
 */
export class SimControlResponse {
/** @type { number } */
    status_code;
/** @type { string } */
    message;


    constructor() {
        this.status_code = 0;
        this.message = "";
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'status_code'
            const field_val = this.status_code;
            if (typeof field_val?.toDict === 'function') {
                d['status_code'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['status_code'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['status_code'] = field_val.toString();
            } else {
                d['status_code'] = field_val;
            }
        }
        {
            // handle field 'message'
            const field_val = this.message;
            if (typeof field_val?.toDict === 'function') {
                d['message'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['message'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['message'] = field_val.toString();
            } else {
                d['message'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { SimControlResponse }
     */
    static fromDict(d) {
        const obj = new SimControlResponse();
        if (d.hasOwnProperty('status_code')) {
            obj.status_code = d.status_code;
        }
        if (d.hasOwnProperty('message')) {
            obj.message = d.message;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { SimControlResponse }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
