

/**
 * ROS message: hako_srv_msgs/DetachResponse
 * Generated by hakoniwa-ros2pdu.
 */
export class DetachResponse {
/** @type { number } */
    result_code;


    constructor() {
        this.result_code = 0;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'result_code'
            const field_val = this.result_code;
            if (typeof field_val?.toDict === 'function') {
                d['result_code'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['result_code'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['result_code'] = field_val.toString();
            } else {
                d['result_code'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { DetachResponse }
     */
    static fromDict(d) {
        const obj = new DetachResponse();
        if (d.hasOwnProperty('result_code')) {
            obj.result_code = d.result_code;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { DetachResponse }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
