require 'json'

module HakoPdu
  module HakoActionMsgs
    # ROS message: hako_action_msgs/ActionResponseHeader
    # Generated by hakoniwa-ros2pdu.
    class ActionResponseHeader
      attr_accessor :version, :response_kind, :status, :reserved, :goal_id

      def initialize(version: 0, response_kind: 0, status: 0, reserved: 0, goal_id: [])

        @version = version

        @response_kind = response_kind

        @status = status

        @reserved = reserved

        @goal_id = goal_id

      end

      def to_h
        {

          'version' => self.class.encode_value(@version),

          'response_kind' => self.class.encode_value(@response_kind),

          'status' => self.class.encode_value(@status),

          'reserved' => self.class.encode_value(@reserved),

          'goal_id' => self.class.encode_value(@goal_id)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          version: decode_version(hash.fetch('version', 0)),

          response_kind: decode_response_kind(hash.fetch('response_kind', 0)),

          status: decode_status(hash.fetch('status', 0)),

          reserved: decode_reserved(hash.fetch('reserved', 0)),

          goal_id: decode_goal_id(hash.fetch('goal_id', []))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_version(value)
        value
      end


      def self.decode_response_kind(value)
        value
      end


      def self.decode_status(value)
        value
      end


      def self.decode_reserved(value)
        value
      end


      def self.decode_goal_id(value)
        value
      end

end
  end
end
