require 'json'

module HakoPdu
  module HakoActionMsgs
    # ROS message: hako_action_msgs/ActionFeedbackHeader
    # Generated by hakoniwa-ros2pdu.
    class ActionFeedbackHeader
      attr_accessor :version, :reserved, :goal_id, :sequence_no

      def initialize(version: 0, reserved: [], goal_id: [], sequence_no: 0)

        @version = version

        @reserved = reserved

        @goal_id = goal_id

        @sequence_no = sequence_no

      end

      def to_h
        {

          'version' => self.class.encode_value(@version),

          'reserved' => self.class.encode_value(@reserved),

          'goal_id' => self.class.encode_value(@goal_id),

          'sequence_no' => self.class.encode_value(@sequence_no)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          version: decode_version(hash.fetch('version', 0)),

          reserved: decode_reserved(hash.fetch('reserved', [])),

          goal_id: decode_goal_id(hash.fetch('goal_id', [])),

          sequence_no: decode_sequence_no(hash.fetch('sequence_no', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_version(value)
        value
      end


      def self.decode_reserved(value)
        value
      end


      def self.decode_goal_id(value)
        value
      end


      def self.decode_sequence_no(value)
        value
      end

end
  end
end
