from typing import List

# dependencies for the generated Python class
from ..hako_msgs.pdu_pytype_ContactEvent import ContactEvent
from ..geometry_msgs.pdu_pytype_Point import Point
from ..builtin_interfaces.pdu_pytype_Time import Time


# class definition for the ROS message
class ContactEventArray:
    """
    ROS message: hako_msgs/ContactEventArray
    Generated by hakoniwa-ros2pdu.
    """

    events: List[ContactEvent]

    def __init__(self):
        self.events = []

    def __str__(self):
        return f"ContactEventArray(" + ", ".join([
            f"events={self.events}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'events'
        field_val = self.events
        if isinstance(field_val, bytearray):
            d['events'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['events'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['events'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['events'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'events'
        if 'events' in d:
            field_type = cls.__annotations__.get('events')
            value = d['events']
            
            if field_type is bytearray:
                obj.events = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.events = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.events = value
            elif hasattr(field_type, 'from_dict'):
                obj.events = field_type.from_dict(value)
            else:
                obj.events = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
