from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class ExecutionUnitRuntimeStatus:
    """
    ROS message: hako_msgs/ExecutionUnitRuntimeStatus
    Generated by hakoniwa-ros2pdu.
    """

    config_hash: int
    unit_count: int
    status: List[int]
    epoch: List[int]
    curr_owner_node_id: List[int]
    next_owner_node_id: List[int]

    def __init__(self):
        self.config_hash = 0
        self.unit_count = 0
        self.status = []
        self.epoch = []
        self.curr_owner_node_id = []
        self.next_owner_node_id = []

    def __str__(self):
        return f"ExecutionUnitRuntimeStatus(" + ", ".join([
            f"config_hash={self.config_hash}"
            f"unit_count={self.unit_count}"
            f"status={self.status}"
            f"epoch={self.epoch}"
            f"curr_owner_node_id={self.curr_owner_node_id}"
            f"next_owner_node_id={self.next_owner_node_id}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'config_hash'
        field_val = self.config_hash
        if isinstance(field_val, bytearray):
            d['config_hash'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['config_hash'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['config_hash'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['config_hash'] = field_val
        # handle field 'unit_count'
        field_val = self.unit_count
        if isinstance(field_val, bytearray):
            d['unit_count'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['unit_count'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['unit_count'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['unit_count'] = field_val
        # handle field 'status'
        field_val = self.status
        if isinstance(field_val, bytearray):
            d['status'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['status'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['status'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['status'] = field_val
        # handle field 'epoch'
        field_val = self.epoch
        if isinstance(field_val, bytearray):
            d['epoch'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['epoch'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['epoch'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['epoch'] = field_val
        # handle field 'curr_owner_node_id'
        field_val = self.curr_owner_node_id
        if isinstance(field_val, bytearray):
            d['curr_owner_node_id'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['curr_owner_node_id'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['curr_owner_node_id'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['curr_owner_node_id'] = field_val
        # handle field 'next_owner_node_id'
        field_val = self.next_owner_node_id
        if isinstance(field_val, bytearray):
            d['next_owner_node_id'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['next_owner_node_id'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['next_owner_node_id'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['next_owner_node_id'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'config_hash'
        if 'config_hash' in d:
            field_type = cls.__annotations__.get('config_hash')
            value = d['config_hash']
            
            if field_type is bytearray:
                obj.config_hash = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.config_hash = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.config_hash = value
            elif hasattr(field_type, 'from_dict'):
                obj.config_hash = field_type.from_dict(value)
            else:
                obj.config_hash = value
        # handle field 'unit_count'
        if 'unit_count' in d:
            field_type = cls.__annotations__.get('unit_count')
            value = d['unit_count']
            
            if field_type is bytearray:
                obj.unit_count = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.unit_count = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.unit_count = value
            elif hasattr(field_type, 'from_dict'):
                obj.unit_count = field_type.from_dict(value)
            else:
                obj.unit_count = value
        # handle field 'status'
        if 'status' in d:
            field_type = cls.__annotations__.get('status')
            value = d['status']
            
            if field_type is bytearray:
                obj.status = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.status = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.status = value
            elif hasattr(field_type, 'from_dict'):
                obj.status = field_type.from_dict(value)
            else:
                obj.status = value
        # handle field 'epoch'
        if 'epoch' in d:
            field_type = cls.__annotations__.get('epoch')
            value = d['epoch']
            
            if field_type is bytearray:
                obj.epoch = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.epoch = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.epoch = value
            elif hasattr(field_type, 'from_dict'):
                obj.epoch = field_type.from_dict(value)
            else:
                obj.epoch = value
        # handle field 'curr_owner_node_id'
        if 'curr_owner_node_id' in d:
            field_type = cls.__annotations__.get('curr_owner_node_id')
            value = d['curr_owner_node_id']
            
            if field_type is bytearray:
                obj.curr_owner_node_id = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.curr_owner_node_id = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.curr_owner_node_id = value
            elif hasattr(field_type, 'from_dict'):
                obj.curr_owner_node_id = field_type.from_dict(value)
            else:
                obj.curr_owner_node_id = value
        # handle field 'next_owner_node_id'
        if 'next_owner_node_id' in d:
            field_type = cls.__annotations__.get('next_owner_node_id')
            value = d['next_owner_node_id']
            
            if field_type is bytearray:
                obj.next_owner_node_id = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.next_owner_node_id = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.next_owner_node_id = value
            elif hasattr(field_type, 'from_dict'):
                obj.next_owner_node_id = field_type.from_dict(value)
            else:
                obj.next_owner_node_id = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
