require_relative '../hako_msgs/pdu_type_HakoCmdHeader'
require_relative '../geometry_msgs/pdu_type_Vector3'
require 'json'

module HakoPdu
  module HakoMsgs
    # ROS message: hako_msgs/HakoCmdCameraMove
    # Generated by hakoniwa-ros2pdu.
    class HakoCmdCameraMove
      attr_accessor :header, :request_id, :angle

      def initialize(header: HakoPdu::HakoMsgs::HakoCmdHeader.new, request_id: 0, angle: HakoPdu::GeometryMsgs::Vector3.new)

        @header = header

        @request_id = request_id

        @angle = angle

      end

      def to_h
        {

          'header' => self.class.encode_value(@header),

          'request_id' => self.class.encode_value(@request_id),

          'angle' => self.class.encode_value(@angle)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          header: decode_header(hash.fetch('header', HakoPdu::HakoMsgs::HakoCmdHeader.new)),

          request_id: decode_request_id(hash.fetch('request_id', 0)),

          angle: decode_angle(hash.fetch('angle', HakoPdu::GeometryMsgs::Vector3.new))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_header(value)
        value.is_a?(Hash) ? HakoPdu::HakoMsgs::HakoCmdHeader.from_h(value) : value
      end


      def self.decode_request_id(value)
        value
      end


      def self.decode_angle(value)
        value.is_a?(Hash) ? HakoPdu::GeometryMsgs::Vector3.from_h(value) : value
      end

end
  end
end
