require_relative '../hako_msgs/pdu_type_DroneVisualState'
require 'json'

module HakoPdu
  module HakoMsgs
    # ROS message: hako_msgs/DroneVisualStateArray
    # Generated by hakoniwa-ros2pdu.
    class DroneVisualStateArray
      attr_accessor :sequence_id, :chunk_index, :chunk_count, :start_index, :valid_count, :drones

      def initialize(sequence_id: 0, chunk_index: 0, chunk_count: 0, start_index: 0, valid_count: 0, drones: [])

        @sequence_id = sequence_id

        @chunk_index = chunk_index

        @chunk_count = chunk_count

        @start_index = start_index

        @valid_count = valid_count

        @drones = drones

      end

      def to_h
        {

          'sequence_id' => self.class.encode_value(@sequence_id),

          'chunk_index' => self.class.encode_value(@chunk_index),

          'chunk_count' => self.class.encode_value(@chunk_count),

          'start_index' => self.class.encode_value(@start_index),

          'valid_count' => self.class.encode_value(@valid_count),

          'drones' => self.class.encode_value(@drones)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          sequence_id: decode_sequence_id(hash.fetch('sequence_id', 0)),

          chunk_index: decode_chunk_index(hash.fetch('chunk_index', 0)),

          chunk_count: decode_chunk_count(hash.fetch('chunk_count', 0)),

          start_index: decode_start_index(hash.fetch('start_index', 0)),

          valid_count: decode_valid_count(hash.fetch('valid_count', 0)),

          drones: decode_drones(hash.fetch('drones', []))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_sequence_id(value)
        value
      end


      def self.decode_chunk_index(value)
        value
      end


      def self.decode_chunk_count(value)
        value
      end


      def self.decode_start_index(value)
        value
      end


      def self.decode_valid_count(value)
        value
      end


      def self.decode_drones(value)
        return [] if value.nil?
        value.map { |item| HakoPdu::HakoMsgs::DroneVisualState.from_h(item) }
      end

end
  end
end
