require 'json'

module HakoPdu
  module HakoMsgs
    # ROS message: hako_msgs/SimpleVarray
    # Generated by hakoniwa-ros2pdu.
    class SimpleVarray
      attr_accessor :data, :fixed_array, :p_mem1

      def initialize(data: [], fixed_array: [], p_mem1: 0)

        @data = data

        @fixed_array = fixed_array

        @p_mem1 = p_mem1

      end

      def to_h
        {

          'data' => self.class.encode_value(@data),

          'fixed_array' => self.class.encode_value(@fixed_array),

          'p_mem1' => self.class.encode_value(@p_mem1)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          data: decode_data(hash.fetch('data', [])),

          fixed_array: decode_fixed_array(hash.fetch('fixed_array', [])),

          p_mem1: decode_p_mem1(hash.fetch('p_mem1', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_data(value)
        value
      end


      def self.decode_fixed_array(value)
        value
      end


      def self.decode_p_mem1(value)
        value
      end

end
  end
end
