require_relative '../sensor_msgs/pdu_type_CompressedImage'
require_relative '../std_msgs/pdu_type_Header'
require_relative '../builtin_interfaces/pdu_type_Time'
require 'json'

module HakoPdu
  module HakoMsgs
    # ROS message: hako_msgs/MonitorCameraData
    # Generated by hakoniwa-ros2pdu.
    class MonitorCameraData
      attr_accessor :request_id, :image_data_length, :image

      def initialize(request_id: 0, image_data_length: 0, image: HakoPdu::SensorMsgs::CompressedImage.new)

        @request_id = request_id

        @image_data_length = image_data_length

        @image = image

      end

      def to_h
        {

          'request_id' => self.class.encode_value(@request_id),

          'image_data_length' => self.class.encode_value(@image_data_length),

          'image' => self.class.encode_value(@image)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          request_id: decode_request_id(hash.fetch('request_id', 0)),

          image_data_length: decode_image_data_length(hash.fetch('image_data_length', 0)),

          image: decode_image(hash.fetch('image', HakoPdu::SensorMsgs::CompressedImage.new))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_request_id(value)
        value
      end


      def self.decode_image_data_length(value)
        value
      end


      def self.decode_image(value)
        value.is_a?(Hash) ? HakoPdu::SensorMsgs::CompressedImage.from_h(value) : value
      end

end
  end
end
