require 'json'

module HakoPdu
  module HakoMsgs
    # ROS message: hako_msgs/ExecutionUnitRuntimeContext
    # Generated by hakoniwa-ros2pdu.
    class ExecutionUnitRuntimeContext
      attr_accessor :config_hash, :epoch, :owner_id, :context

      def initialize(config_hash: 0, epoch: 0, owner_id: 0, context: [])

        @config_hash = config_hash

        @epoch = epoch

        @owner_id = owner_id

        @context = context

      end

      def to_h
        {

          'config_hash' => self.class.encode_value(@config_hash),

          'epoch' => self.class.encode_value(@epoch),

          'owner_id' => self.class.encode_value(@owner_id),

          'context' => self.class.encode_value(@context)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          config_hash: decode_config_hash(hash.fetch('config_hash', 0)),

          epoch: decode_epoch(hash.fetch('epoch', 0)),

          owner_id: decode_owner_id(hash.fetch('owner_id', 0)),

          context: decode_context(hash.fetch('context', []))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_config_hash(value)
        value
      end


      def self.decode_epoch(value)
        value
      end


      def self.decode_owner_id(value)
        value
      end


      def self.decode_context(value)
        value
      end

end
  end
end
