require 'json'

module HakoPdu
  module HakoMsgs
    # ROS message: hako_msgs/HakoStatusMagnetHolder
    # Generated by hakoniwa-ros2pdu.
    class HakoStatusMagnetHolder
      attr_accessor :magnet_on, :contact_on

      def initialize(magnet_on: false, contact_on: false)

        @magnet_on = magnet_on

        @contact_on = contact_on

      end

      def to_h
        {

          'magnet_on' => self.class.encode_value(@magnet_on),

          'contact_on' => self.class.encode_value(@contact_on)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          magnet_on: decode_magnet_on(hash.fetch('magnet_on', false)),

          contact_on: decode_contact_on(hash.fetch('contact_on', false))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_magnet_on(value)
        value
      end


      def self.decode_contact_on(value)
        value
      end

end
  end
end
