require 'json'

module HakoPdu
  module HakoMsgs
    # ROS message: hako_msgs/ExecutionUnitRuntimeStatus
    # Generated by hakoniwa-ros2pdu.
    class ExecutionUnitRuntimeStatus
      attr_accessor :config_hash, :unit_count, :status, :epoch, :curr_owner_node_id, :next_owner_node_id

      def initialize(config_hash: 0, unit_count: 0, status: [], epoch: [], curr_owner_node_id: [], next_owner_node_id: [])

        @config_hash = config_hash

        @unit_count = unit_count

        @status = status

        @epoch = epoch

        @curr_owner_node_id = curr_owner_node_id

        @next_owner_node_id = next_owner_node_id

      end

      def to_h
        {

          'config_hash' => self.class.encode_value(@config_hash),

          'unit_count' => self.class.encode_value(@unit_count),

          'status' => self.class.encode_value(@status),

          'epoch' => self.class.encode_value(@epoch),

          'curr_owner_node_id' => self.class.encode_value(@curr_owner_node_id),

          'next_owner_node_id' => self.class.encode_value(@next_owner_node_id)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          config_hash: decode_config_hash(hash.fetch('config_hash', 0)),

          unit_count: decode_unit_count(hash.fetch('unit_count', 0)),

          status: decode_status(hash.fetch('status', [])),

          epoch: decode_epoch(hash.fetch('epoch', [])),

          curr_owner_node_id: decode_curr_owner_node_id(hash.fetch('curr_owner_node_id', [])),

          next_owner_node_id: decode_next_owner_node_id(hash.fetch('next_owner_node_id', []))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_config_hash(value)
        value
      end


      def self.decode_unit_count(value)
        value
      end


      def self.decode_status(value)
        value
      end


      def self.decode_epoch(value)
        value
      end


      def self.decode_curr_owner_node_id(value)
        value
      end


      def self.decode_next_owner_node_id(value)
        value
      end

end
  end
end
