require 'json'

module HakoPdu
  module HakoMsgs
    # ROS message: hako_msgs/ShareObjectOwnerResponse
    # Generated by hakoniwa-ros2pdu.
    class ShareObjectOwnerResponse
      attr_accessor :object_name, :request_type, :owner_id, :accepted

      def initialize(object_name: "", request_type: 0, owner_id: 0, accepted: false)

        @object_name = object_name

        @request_type = request_type

        @owner_id = owner_id

        @accepted = accepted

      end

      def to_h
        {

          'object_name' => self.class.encode_value(@object_name),

          'request_type' => self.class.encode_value(@request_type),

          'owner_id' => self.class.encode_value(@owner_id),

          'accepted' => self.class.encode_value(@accepted)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          object_name: decode_object_name(hash.fetch('object_name', "")),

          request_type: decode_request_type(hash.fetch('request_type', 0)),

          owner_id: decode_owner_id(hash.fetch('owner_id', 0)),

          accepted: decode_accepted(hash.fetch('accepted', false))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_object_name(value)
        value
      end


      def self.decode_request_type(value)
        value
      end


      def self.decode_owner_id(value)
        value
      end


      def self.decode_accepted(value)
        value
      end

end
  end
end
