require 'json'

module HakoPdu
  module HakoMsgs
    # ROS message: hako_msgs/SimTime
    # Generated by hakoniwa-ros2pdu.
    class SimTime
      attr_accessor :time_usec

      def initialize(time_usec: 0)

        @time_usec = time_usec

      end

      def to_h
        {

          'time_usec' => self.class.encode_value(@time_usec)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          time_usec: decode_time_usec(hash.fetch('time_usec', 0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_time_usec(value)
        value
      end

end
  end
end
