import { Header } from '../std_msgs/pdu_jstype_Header.js';
import { MapMetaData } from '../nav_msgs/pdu_jstype_MapMetaData.js';
import { Point } from '../geometry_msgs/pdu_jstype_Point.js';
import { Pose } from '../geometry_msgs/pdu_jstype_Pose.js';
import { Quaternion } from '../geometry_msgs/pdu_jstype_Quaternion.js';
import { Time } from '../builtin_interfaces/pdu_jstype_Time.js';


/**
 * ROS message: nav_msgs/OccupancyGrid
 * Generated by hakoniwa-ros2pdu.
 */
export class OccupancyGrid {
/** @type { Header } */
    header;
/** @type { MapMetaData } */
    info;
/** @type { Array<number> } */
    data;


    constructor() {
        this.header = new Header();
        this.info = new MapMetaData();
        this.data = [];
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'header'
            const field_val = this.header;
            if (typeof field_val?.toDict === 'function') {
                d['header'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['header'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['header'] = field_val;
            }
        }
        {
            // handle field 'info'
            const field_val = this.info;
            if (typeof field_val?.toDict === 'function') {
                d['info'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['info'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['info'] = field_val;
            }
        }
        {
            // handle field 'data'
            const field_val = this.data;
            if (typeof field_val?.toDict === 'function') {
                d['data'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['data'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['data'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { OccupancyGrid }
     */
    static fromDict(d) {
        const obj = new OccupancyGrid();
        if (d.hasOwnProperty('header')) {
            const field_class = Header;
            if (d.header) {
                obj.header = field_class.fromDict(d.header);
            }
        }
        if (d.hasOwnProperty('info')) {
            const field_class = MapMetaData;
            if (d.info) {
                obj.info = field_class.fromDict(d.info);
            }
        }
        if (d.hasOwnProperty('data')) {
            obj.data = d.data;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { OccupancyGrid }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
