import { Header } from '../std_msgs/pdu_jstype_Header.js';
import { Point } from '../geometry_msgs/pdu_jstype_Point.js';
import { Time } from '../builtin_interfaces/pdu_jstype_Time.js';


/**
 * ROS message: nav_msgs/GridCells
 * Generated by hakoniwa-ros2pdu.
 */
export class GridCells {
/** @type { Header } */
    header;
/** @type { number } */
    cell_width;
/** @type { number } */
    cell_height;
/** @type { Array<Point> } */
    cells;


    constructor() {
        this.header = new Header();
        this.cell_width = 0.0;
        this.cell_height = 0.0;
        this.cells = [];
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'header'
            const field_val = this.header;
            if (typeof field_val?.toDict === 'function') {
                d['header'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['header'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['header'] = field_val;
            }
        }
        {
            // handle field 'cell_width'
            const field_val = this.cell_width;
            if (typeof field_val?.toDict === 'function') {
                d['cell_width'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['cell_width'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['cell_width'] = field_val;
            }
        }
        {
            // handle field 'cell_height'
            const field_val = this.cell_height;
            if (typeof field_val?.toDict === 'function') {
                d['cell_height'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['cell_height'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['cell_height'] = field_val;
            }
        }
        {
            // handle field 'cells'
            const field_val = this.cells;
            if (typeof field_val?.toDict === 'function') {
                d['cells'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['cells'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['cells'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { GridCells }
     */
    static fromDict(d) {
        const obj = new GridCells();
        if (d.hasOwnProperty('header')) {
            const field_class = Header;
            if (d.header) {
                obj.header = field_class.fromDict(d.header);
            }
        }
        if (d.hasOwnProperty('cell_width')) {
            obj.cell_width = d.cell_width;
        }
        if (d.hasOwnProperty('cell_height')) {
            obj.cell_height = d.cell_height;
        }
        if (d.hasOwnProperty('cells')) {
            const item_class = Point;
            if (Array.isArray(d.cells)) {
                obj.cells = d.cells.map(item => item_class.fromDict(item));
            }
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { GridCells }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
