import { Point } from '../geometry_msgs/pdu_jstype_Point.js';
import { Pose } from '../geometry_msgs/pdu_jstype_Pose.js';
import { Quaternion } from '../geometry_msgs/pdu_jstype_Quaternion.js';
import { Time } from '../builtin_interfaces/pdu_jstype_Time.js';


/**
 * ROS message: nav_msgs/MapMetaData
 * Generated by hakoniwa-ros2pdu.
 */
export class MapMetaData {
/** @type { Time } */
    map_load_time;
/** @type { number } */
    resolution;
/** @type { number } */
    width;
/** @type { number } */
    height;
/** @type { Pose } */
    origin;


    constructor() {
        this.map_load_time = new Time();
        this.resolution = 0.0;
        this.width = 0;
        this.height = 0;
        this.origin = new Pose();
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'map_load_time'
            const field_val = this.map_load_time;
            if (typeof field_val?.toDict === 'function') {
                d['map_load_time'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['map_load_time'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['map_load_time'] = field_val;
            }
        }
        {
            // handle field 'resolution'
            const field_val = this.resolution;
            if (typeof field_val?.toDict === 'function') {
                d['resolution'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['resolution'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['resolution'] = field_val;
            }
        }
        {
            // handle field 'width'
            const field_val = this.width;
            if (typeof field_val?.toDict === 'function') {
                d['width'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['width'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['width'] = field_val;
            }
        }
        {
            // handle field 'height'
            const field_val = this.height;
            if (typeof field_val?.toDict === 'function') {
                d['height'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['height'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['height'] = field_val;
            }
        }
        {
            // handle field 'origin'
            const field_val = this.origin;
            if (typeof field_val?.toDict === 'function') {
                d['origin'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['origin'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['origin'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { MapMetaData }
     */
    static fromDict(d) {
        const obj = new MapMetaData();
        if (d.hasOwnProperty('map_load_time')) {
            const field_class = Time;
            if (d.map_load_time) {
                obj.map_load_time = field_class.fromDict(d.map_load_time);
            }
        }
        if (d.hasOwnProperty('resolution')) {
            obj.resolution = d.resolution;
        }
        if (d.hasOwnProperty('width')) {
            obj.width = d.width;
        }
        if (d.hasOwnProperty('height')) {
            obj.height = d.height;
        }
        if (d.hasOwnProperty('origin')) {
            const field_class = Pose;
            if (d.origin) {
                obj.origin = field_class.fromDict(d.origin);
            }
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { MapMetaData }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
