import { Header } from '../std_msgs/pdu_jstype_Header.js';
import { Point } from '../geometry_msgs/pdu_jstype_Point.js';
import { Pose } from '../geometry_msgs/pdu_jstype_Pose.js';
import { PoseStamped } from '../geometry_msgs/pdu_jstype_PoseStamped.js';
import { Quaternion } from '../geometry_msgs/pdu_jstype_Quaternion.js';
import { Time } from '../builtin_interfaces/pdu_jstype_Time.js';


/**
 * ROS message: nav_msgs/Path
 * Generated by hakoniwa-ros2pdu.
 */
export class Path {
/** @type { Header } */
    header;
/** @type { Array<PoseStamped> } */
    poses;


    constructor() {
        this.header = new Header();
        this.poses = [];
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'header'
            const field_val = this.header;
            if (typeof field_val?.toDict === 'function') {
                d['header'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['header'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['header'] = field_val;
            }
        }
        {
            // handle field 'poses'
            const field_val = this.poses;
            if (typeof field_val?.toDict === 'function') {
                d['poses'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['poses'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['poses'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { Path }
     */
    static fromDict(d) {
        const obj = new Path();
        if (d.hasOwnProperty('header')) {
            const field_class = Header;
            if (d.header) {
                obj.header = field_class.fromDict(d.header);
            }
        }
        if (d.hasOwnProperty('poses')) {
            const item_class = PoseStamped;
            if (Array.isArray(d.poses)) {
                obj.poses = d.poses.map(item => item_class.fromDict(item));
            }
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { Path }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
