require_relative '../std_msgs/pdu_type_Header'
require_relative '../geometry_msgs/pdu_type_Quaternion'
require_relative '../builtin_interfaces/pdu_type_Time'
require_relative '../geometry_msgs/pdu_type_Vector3'
require 'json'

module HakoPdu
  module MavrosMsgs
    # ROS message: mavros_msgs/AttitudeTarget
    # Generated by hakoniwa-ros2pdu.
    class AttitudeTarget
      attr_accessor :header, :type_mask, :orientation, :body_rate, :thrust

      def initialize(header: HakoPdu::StdMsgs::Header.new, type_mask: 0, orientation: HakoPdu::GeometryMsgs::Quaternion.new, body_rate: HakoPdu::GeometryMsgs::Vector3.new, thrust: 0.0)

        @header = header

        @type_mask = type_mask

        @orientation = orientation

        @body_rate = body_rate

        @thrust = thrust

      end

      def to_h
        {

          'header' => self.class.encode_value(@header),

          'type_mask' => self.class.encode_value(@type_mask),

          'orientation' => self.class.encode_value(@orientation),

          'body_rate' => self.class.encode_value(@body_rate),

          'thrust' => self.class.encode_value(@thrust)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          header: decode_header(hash.fetch('header', HakoPdu::StdMsgs::Header.new)),

          type_mask: decode_type_mask(hash.fetch('type_mask', 0)),

          orientation: decode_orientation(hash.fetch('orientation', HakoPdu::GeometryMsgs::Quaternion.new)),

          body_rate: decode_body_rate(hash.fetch('body_rate', HakoPdu::GeometryMsgs::Vector3.new)),

          thrust: decode_thrust(hash.fetch('thrust', 0.0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_header(value)
        value.is_a?(Hash) ? HakoPdu::StdMsgs::Header.from_h(value) : value
      end


      def self.decode_type_mask(value)
        value
      end


      def self.decode_orientation(value)
        value.is_a?(Hash) ? HakoPdu::GeometryMsgs::Quaternion.from_h(value) : value
      end


      def self.decode_body_rate(value)
        value.is_a?(Hash) ? HakoPdu::GeometryMsgs::Vector3.from_h(value) : value
      end


      def self.decode_thrust(value)
        value
      end

end
  end
end
