require_relative '../std_msgs/pdu_type_Header'
require_relative '../builtin_interfaces/pdu_type_Time'
require_relative '../geometry_msgs/pdu_type_Vector3'
require 'json'

module HakoPdu
  module MavrosMsgs
    # ROS message: mavros_msgs/GlobalPositionTarget
    # Generated by hakoniwa-ros2pdu.
    class GlobalPositionTarget
      attr_accessor :header, :coordinate_frame, :type_mask, :latitude, :longitude, :altitude, :velocity, :acceleration_or_force, :yaw, :yaw_rate

      def initialize(header: HakoPdu::StdMsgs::Header.new, coordinate_frame: 0, type_mask: 0, latitude: 0.0, longitude: 0.0, altitude: 0.0, velocity: HakoPdu::GeometryMsgs::Vector3.new, acceleration_or_force: HakoPdu::GeometryMsgs::Vector3.new, yaw: 0.0, yaw_rate: 0.0)

        @header = header

        @coordinate_frame = coordinate_frame

        @type_mask = type_mask

        @latitude = latitude

        @longitude = longitude

        @altitude = altitude

        @velocity = velocity

        @acceleration_or_force = acceleration_or_force

        @yaw = yaw

        @yaw_rate = yaw_rate

      end

      def to_h
        {

          'header' => self.class.encode_value(@header),

          'coordinate_frame' => self.class.encode_value(@coordinate_frame),

          'type_mask' => self.class.encode_value(@type_mask),

          'latitude' => self.class.encode_value(@latitude),

          'longitude' => self.class.encode_value(@longitude),

          'altitude' => self.class.encode_value(@altitude),

          'velocity' => self.class.encode_value(@velocity),

          'acceleration_or_force' => self.class.encode_value(@acceleration_or_force),

          'yaw' => self.class.encode_value(@yaw),

          'yaw_rate' => self.class.encode_value(@yaw_rate)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          header: decode_header(hash.fetch('header', HakoPdu::StdMsgs::Header.new)),

          coordinate_frame: decode_coordinate_frame(hash.fetch('coordinate_frame', 0)),

          type_mask: decode_type_mask(hash.fetch('type_mask', 0)),

          latitude: decode_latitude(hash.fetch('latitude', 0.0)),

          longitude: decode_longitude(hash.fetch('longitude', 0.0)),

          altitude: decode_altitude(hash.fetch('altitude', 0.0)),

          velocity: decode_velocity(hash.fetch('velocity', HakoPdu::GeometryMsgs::Vector3.new)),

          acceleration_or_force: decode_acceleration_or_force(hash.fetch('acceleration_or_force', HakoPdu::GeometryMsgs::Vector3.new)),

          yaw: decode_yaw(hash.fetch('yaw', 0.0)),

          yaw_rate: decode_yaw_rate(hash.fetch('yaw_rate', 0.0))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_header(value)
        value.is_a?(Hash) ? HakoPdu::StdMsgs::Header.from_h(value) : value
      end


      def self.decode_coordinate_frame(value)
        value
      end


      def self.decode_type_mask(value)
        value
      end


      def self.decode_latitude(value)
        value
      end


      def self.decode_longitude(value)
        value
      end


      def self.decode_altitude(value)
        value
      end


      def self.decode_velocity(value)
        value.is_a?(Hash) ? HakoPdu::GeometryMsgs::Vector3.from_h(value) : value
      end


      def self.decode_acceleration_or_force(value)
        value.is_a?(Hash) ? HakoPdu::GeometryMsgs::Vector3.from_h(value) : value
      end


      def self.decode_yaw(value)
        value
      end


      def self.decode_yaw_rate(value)
        value
      end

end
  end
end
