require_relative '../hako_action_msgs/pdu_type_ActionRequestHeader'
require_relative '../sample_action_msgs/pdu_type_FibonacciGoal'
require 'json'

module HakoPdu
  module SampleActionMsgs
    # ROS message: sample_action_msgs/FibonacciActionRequest
    # Generated by hakoniwa-ros2pdu.
    class FibonacciActionRequest
      attr_accessor :header, :body

      def initialize(header: HakoPdu::HakoActionMsgs::ActionRequestHeader.new, body: HakoPdu::SampleActionMsgs::FibonacciGoal.new)

        @header = header

        @body = body

      end

      def to_h
        {

          'header' => self.class.encode_value(@header),

          'body' => self.class.encode_value(@body)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          header: decode_header(hash.fetch('header', HakoPdu::HakoActionMsgs::ActionRequestHeader.new)),

          body: decode_body(hash.fetch('body', HakoPdu::SampleActionMsgs::FibonacciGoal.new))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_header(value)
        value.is_a?(Hash) ? HakoPdu::HakoActionMsgs::ActionRequestHeader.from_h(value) : value
      end


      def self.decode_body(value)
        value.is_a?(Hash) ? HakoPdu::SampleActionMsgs::FibonacciGoal.from_h(value) : value
      end

end
  end
end
