require 'json'

module HakoPdu
  module DroneSrvMsgs
    # ROS message: drone_srv_msgs/CameraCaptureImageRequest
    # Generated by hakoniwa-ros2pdu.
    class CameraCaptureImageRequest
      attr_accessor :drone_name, :image_type

      def initialize(drone_name: "", image_type: "")

        @drone_name = drone_name

        @image_type = image_type

      end

      def to_h
        {

          'drone_name' => self.class.encode_value(@drone_name),

          'image_type' => self.class.encode_value(@image_type)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          drone_name: decode_drone_name(hash.fetch('drone_name', "")),

          image_type: decode_image_type(hash.fetch('image_type', ""))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_drone_name(value)
        value
      end


      def self.decode_image_type(value)
        value
      end

end
  end
end
