require_relative '../std_msgs/pdu_type_Header'
require_relative '../drone_srv_msgs/pdu_type_LiDARScanResponse'
require_relative '../geometry_msgs/pdu_type_Point'
require_relative '../sensor_msgs/pdu_type_PointCloud2'
require_relative '../sensor_msgs/pdu_type_PointField'
require_relative '../geometry_msgs/pdu_type_Pose'
require_relative '../geometry_msgs/pdu_type_Quaternion'
require_relative '../hako_srv_msgs/pdu_type_ServiceResponseHeader'
require_relative '../builtin_interfaces/pdu_type_Time'
require 'json'

module HakoPdu
  module DroneSrvMsgs
    # ROS message: drone_srv_msgs/LiDARScanResponsePacket
    # Generated by hakoniwa-ros2pdu.
    class LiDARScanResponsePacket
      attr_accessor :header, :body

      def initialize(header: HakoPdu::HakoSrvMsgs::ServiceResponseHeader.new, body: HakoPdu::DroneSrvMsgs::LiDARScanResponse.new)

        @header = header

        @body = body

      end

      def to_h
        {

          'header' => self.class.encode_value(@header),

          'body' => self.class.encode_value(@body)

        }
      end

      def to_json(*args)
        to_h.to_json(*args)
      end

      def self.from_h(hash)
        hash = (hash || {}).transform_keys(&:to_s)
        new(

          header: decode_header(hash.fetch('header', HakoPdu::HakoSrvMsgs::ServiceResponseHeader.new)),

          body: decode_body(hash.fetch('body', HakoPdu::DroneSrvMsgs::LiDARScanResponse.new))

        )
      end

      def self.from_json(json)
        from_h(JSON.parse(json))
      end

      def self.encode_value(value)
        if value.is_a?(Array)
          value.map { |item| encode_value(item) }
        elsif value.respond_to?(:to_h)
          value.to_h
        else
          value
        end
      end


      def self.decode_header(value)
        value.is_a?(Hash) ? HakoPdu::HakoSrvMsgs::ServiceResponseHeader.from_h(value) : value
      end


      def self.decode_body(value)
        value.is_a?(Hash) ? HakoPdu::DroneSrvMsgs::LiDARScanResponse.from_h(value) : value
      end

end
  end
end
