

/**
 * ROS message: hako_action_msgs/ActionFeedbackHeader
 * Generated by hakoniwa-ros2pdu.
 */
export class ActionFeedbackHeader {
/** @type { number } */
    version;
/** @type { Array<number> } */
    reserved;
/** @type { Array<number> } */
    goal_id;
/** @type { number } */
    sequence_no;


    constructor() {
        this.version = 0;
        this.reserved = [];
        this.goal_id = [];
        this.sequence_no = 0;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'version'
            const field_val = this.version;
            if (typeof field_val?.toDict === 'function') {
                d['version'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['version'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['version'] = field_val.toString();
            } else {
                d['version'] = field_val;
            }
        }
        {
            // handle field 'reserved'
            const field_val = this.reserved;
            if (typeof field_val?.toDict === 'function') {
                d['reserved'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['reserved'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['reserved'] = field_val.toString();
            } else {
                d['reserved'] = field_val;
            }
        }
        {
            // handle field 'goal_id'
            const field_val = this.goal_id;
            if (typeof field_val?.toDict === 'function') {
                d['goal_id'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['goal_id'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['goal_id'] = field_val.toString();
            } else {
                d['goal_id'] = field_val;
            }
        }
        {
            // handle field 'sequence_no'
            const field_val = this.sequence_no;
            if (typeof field_val?.toDict === 'function') {
                d['sequence_no'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['sequence_no'] = field_val.map(item => {
                    if (typeof item?.toDict === 'function') {
                        return item.toDict();
                    }
                    if (typeof item === 'bigint') {
                        return item.toString();
                    }
                    return item;
                });
            } else if (typeof field_val === 'bigint') {
                d['sequence_no'] = field_val.toString();
            } else {
                d['sequence_no'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { ActionFeedbackHeader }
     */
    static fromDict(d) {
        const obj = new ActionFeedbackHeader();
        if (d.hasOwnProperty('version')) {
            obj.version = d.version;
        }
        if (d.hasOwnProperty('reserved')) {
            obj.reserved = d.reserved;
        }
        if (d.hasOwnProperty('goal_id')) {
            obj.goal_id = d.goal_id;
        }
        if (d.hasOwnProperty('sequence_no')) {
            obj.sequence_no = d.sequence_no;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { ActionFeedbackHeader }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
