defmodule HakoPdu.GeometryMsgs.Transform do
  @moduledoc """
  ROS message: geometry_msgs/Transform

  Generated by hakoniwa-ros2pdu.
  """

  defstruct [

    translation: HakoPdu.GeometryMsgs.Vector3.new(),

    rotation: HakoPdu.GeometryMsgs.Quaternion.new()

  ]

  def new(attrs \\ %{}) when is_map(attrs) do
    struct(__MODULE__, attrs)
  end

  def to_map(%__MODULE__{} = msg) do
    %{

      "translation" => encode_value(msg.translation),

      "rotation" => encode_value(msg.rotation)

    }
  end

  def from_map(map) when is_map(map) do
    %__MODULE__{

      translation: map |> get_value(:translation, "translation", HakoPdu.GeometryMsgs.Vector3.new()) |> decode_translation(),

      rotation: map |> get_value(:rotation, "rotation", HakoPdu.GeometryMsgs.Quaternion.new()) |> decode_rotation()

    }
  end

  def to_json(%__MODULE__{} = msg) do
    msg
    |> to_map()
    |> json_encode()
  end

  def from_json(json) when is_binary(json) do
    json
    |> json_decode()
    |> from_map()
  end

  defp get_value(map, atom_key, string_key, default) do
    Map.get(map, atom_key, Map.get(map, string_key, default))
  end

  defp encode_value(values) when is_list(values), do: Enum.map(values, &encode_value/1)
  defp encode_value(%{__struct__: module} = value) do
    if function_exported?(module, :to_map, 1), do: module.to_map(value), else: value
  end
  defp encode_value(value), do: value

  defp json_encode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :encode!, 1) -> apply(Jason, :encode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :encode!, 1) -> apply(JSON, :encode!, [value])
      true -> raise "No JSON encoder found. Add Jason or JSON to use to_json/1."
    end
  end

  defp json_decode(value) do
    cond do
      Code.ensure_loaded?(Jason) and function_exported?(Jason, :decode!, 1) -> apply(Jason, :decode!, [value])
      Code.ensure_loaded?(JSON) and function_exported?(JSON, :decode!, 1) -> apply(JSON, :decode!, [value])
      true -> raise "No JSON decoder found. Add Jason or JSON to use from_json/1."
    end
  end


  defp decode_translation(value) do
    if is_map(value), do: HakoPdu.GeometryMsgs.Vector3.from_map(value), else: value
  end


  defp decode_rotation(value) do
    if is_map(value), do: HakoPdu.GeometryMsgs.Quaternion.from_map(value), else: value
  end

end
